// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package reposstore

import (
	"context"
	"github.com/bobcob7/loam/internal/db/gen"
	"github.com/jackc/pgx/v5/pgtype"
	"sync"
)

// Ensure, that querierMock does implement querier.
// If this is not the case, regenerate this file with moq.
var _ querier = &querierMock{}

// querierMock is a mock implementation of querier.
//
//	func TestSomethingThatUsesquerier(t *testing.T) {
//
//		// make and configure a mocked querier
//		mockedquerier := &querierMock{
//			AddTargetBranchFunc: func(ctx context.Context, arg gen.AddTargetBranchParams) (gen.RepoTargetBranch, error) {
//				panic("mock out the AddTargetBranch method")
//			},
//			AdvanceIngestedRefFunc: func(ctx context.Context, arg gen.AdvanceIngestedRefParams) (gen.RepoTargetBranch, error) {
//				panic("mock out the AdvanceIngestedRef method")
//			},
//			CountReposFunc: func(ctx context.Context) (int64, error) {
//				panic("mock out the CountRepos method")
//			},
//			CreateRepoFunc: func(ctx context.Context, arg gen.CreateRepoParams) (gen.Repo, error) {
//				panic("mock out the CreateRepo method")
//			},
//			GetRepoByIDFunc: func(ctx context.Context, id pgtype.UUID) (gen.Repo, error) {
//				panic("mock out the GetRepoByID method")
//			},
//			GetRepoByNameFunc: func(ctx context.Context, name string) (gen.Repo, error) {
//				panic("mock out the GetRepoByName method")
//			},
//			GetTargetBranchFunc: func(ctx context.Context, arg gen.GetTargetBranchParams) (gen.RepoTargetBranch, error) {
//				panic("mock out the GetTargetBranch method")
//			},
//			ListRepoNamesFunc: func(ctx context.Context) ([]string, error) {
//				panic("mock out the ListRepoNames method")
//			},
//			ListReposFunc: func(ctx context.Context, arg gen.ListReposParams) ([]gen.Repo, error) {
//				panic("mock out the ListRepos method")
//			},
//			ListTargetBranchesFunc: func(ctx context.Context, repoID pgtype.UUID) ([]gen.RepoTargetBranch, error) {
//				panic("mock out the ListTargetBranches method")
//			},
//			RemoveTargetBranchFunc: func(ctx context.Context, arg gen.RemoveTargetBranchParams) (int64, error) {
//				panic("mock out the RemoveTargetBranch method")
//			},
//			UpdateRepoFunc: func(ctx context.Context, arg gen.UpdateRepoParams) (gen.Repo, error) {
//				panic("mock out the UpdateRepo method")
//			},
//		}
//
//		// use mockedquerier in code that requires querier
//		// and then make assertions.
//
//	}
type querierMock struct {
	// AddTargetBranchFunc mocks the AddTargetBranch method.
	AddTargetBranchFunc func(ctx context.Context, arg gen.AddTargetBranchParams) (gen.RepoTargetBranch, error)

	// AdvanceIngestedRefFunc mocks the AdvanceIngestedRef method.
	AdvanceIngestedRefFunc func(ctx context.Context, arg gen.AdvanceIngestedRefParams) (gen.RepoTargetBranch, error)

	// CountReposFunc mocks the CountRepos method.
	CountReposFunc func(ctx context.Context) (int64, error)

	// CreateRepoFunc mocks the CreateRepo method.
	CreateRepoFunc func(ctx context.Context, arg gen.CreateRepoParams) (gen.Repo, error)

	// GetRepoByIDFunc mocks the GetRepoByID method.
	GetRepoByIDFunc func(ctx context.Context, id pgtype.UUID) (gen.Repo, error)

	// GetRepoByNameFunc mocks the GetRepoByName method.
	GetRepoByNameFunc func(ctx context.Context, name string) (gen.Repo, error)

	// GetTargetBranchFunc mocks the GetTargetBranch method.
	GetTargetBranchFunc func(ctx context.Context, arg gen.GetTargetBranchParams) (gen.RepoTargetBranch, error)

	// ListRepoNamesFunc mocks the ListRepoNames method.
	ListRepoNamesFunc func(ctx context.Context) ([]string, error)

	// ListReposFunc mocks the ListRepos method.
	ListReposFunc func(ctx context.Context, arg gen.ListReposParams) ([]gen.Repo, error)

	// ListTargetBranchesFunc mocks the ListTargetBranches method.
	ListTargetBranchesFunc func(ctx context.Context, repoID pgtype.UUID) ([]gen.RepoTargetBranch, error)

	// RemoveTargetBranchFunc mocks the RemoveTargetBranch method.
	RemoveTargetBranchFunc func(ctx context.Context, arg gen.RemoveTargetBranchParams) (int64, error)

	// UpdateRepoFunc mocks the UpdateRepo method.
	UpdateRepoFunc func(ctx context.Context, arg gen.UpdateRepoParams) (gen.Repo, error)

	// calls tracks calls to the methods.
	calls struct {
		// AddTargetBranch holds details about calls to the AddTargetBranch method.
		AddTargetBranch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg gen.AddTargetBranchParams
		}
		// AdvanceIngestedRef holds details about calls to the AdvanceIngestedRef method.
		AdvanceIngestedRef []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg gen.AdvanceIngestedRefParams
		}
		// CountRepos holds details about calls to the CountRepos method.
		CountRepos []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// CreateRepo holds details about calls to the CreateRepo method.
		CreateRepo []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg gen.CreateRepoParams
		}
		// GetRepoByID holds details about calls to the GetRepoByID method.
		GetRepoByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID pgtype.UUID
		}
		// GetRepoByName holds details about calls to the GetRepoByName method.
		GetRepoByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
		// GetTargetBranch holds details about calls to the GetTargetBranch method.
		GetTargetBranch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg gen.GetTargetBranchParams
		}
		// ListRepoNames holds details about calls to the ListRepoNames method.
		ListRepoNames []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ListRepos holds details about calls to the ListRepos method.
		ListRepos []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg gen.ListReposParams
		}
		// ListTargetBranches holds details about calls to the ListTargetBranches method.
		ListTargetBranches []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RepoID is the repoID argument value.
			RepoID pgtype.UUID
		}
		// RemoveTargetBranch holds details about calls to the RemoveTargetBranch method.
		RemoveTargetBranch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg gen.RemoveTargetBranchParams
		}
		// UpdateRepo holds details about calls to the UpdateRepo method.
		UpdateRepo []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg gen.UpdateRepoParams
		}
	}
	lockAddTargetBranch    sync.RWMutex
	lockAdvanceIngestedRef sync.RWMutex
	lockCountRepos         sync.RWMutex
	lockCreateRepo         sync.RWMutex
	lockGetRepoByID        sync.RWMutex
	lockGetRepoByName      sync.RWMutex
	lockGetTargetBranch    sync.RWMutex
	lockListRepoNames      sync.RWMutex
	lockListRepos          sync.RWMutex
	lockListTargetBranches sync.RWMutex
	lockRemoveTargetBranch sync.RWMutex
	lockUpdateRepo         sync.RWMutex
}

// AddTargetBranch calls AddTargetBranchFunc.
func (mock *querierMock) AddTargetBranch(ctx context.Context, arg gen.AddTargetBranchParams) (gen.RepoTargetBranch, error) {
	if mock.AddTargetBranchFunc == nil {
		panic("querierMock.AddTargetBranchFunc: method is nil but querier.AddTargetBranch was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg gen.AddTargetBranchParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockAddTargetBranch.Lock()
	mock.calls.AddTargetBranch = append(mock.calls.AddTargetBranch, callInfo)
	mock.lockAddTargetBranch.Unlock()
	return mock.AddTargetBranchFunc(ctx, arg)
}

// AddTargetBranchCalls gets all the calls that were made to AddTargetBranch.
// Check the length with:
//
//	len(mockedquerier.AddTargetBranchCalls())
func (mock *querierMock) AddTargetBranchCalls() []struct {
	Ctx context.Context
	Arg gen.AddTargetBranchParams
} {
	var calls []struct {
		Ctx context.Context
		Arg gen.AddTargetBranchParams
	}
	mock.lockAddTargetBranch.RLock()
	calls = mock.calls.AddTargetBranch
	mock.lockAddTargetBranch.RUnlock()
	return calls
}

// AdvanceIngestedRef calls AdvanceIngestedRefFunc.
func (mock *querierMock) AdvanceIngestedRef(ctx context.Context, arg gen.AdvanceIngestedRefParams) (gen.RepoTargetBranch, error) {
	if mock.AdvanceIngestedRefFunc == nil {
		panic("querierMock.AdvanceIngestedRefFunc: method is nil but querier.AdvanceIngestedRef was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg gen.AdvanceIngestedRefParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockAdvanceIngestedRef.Lock()
	mock.calls.AdvanceIngestedRef = append(mock.calls.AdvanceIngestedRef, callInfo)
	mock.lockAdvanceIngestedRef.Unlock()
	return mock.AdvanceIngestedRefFunc(ctx, arg)
}

// AdvanceIngestedRefCalls gets all the calls that were made to AdvanceIngestedRef.
// Check the length with:
//
//	len(mockedquerier.AdvanceIngestedRefCalls())
func (mock *querierMock) AdvanceIngestedRefCalls() []struct {
	Ctx context.Context
	Arg gen.AdvanceIngestedRefParams
} {
	var calls []struct {
		Ctx context.Context
		Arg gen.AdvanceIngestedRefParams
	}
	mock.lockAdvanceIngestedRef.RLock()
	calls = mock.calls.AdvanceIngestedRef
	mock.lockAdvanceIngestedRef.RUnlock()
	return calls
}

// CountRepos calls CountReposFunc.
func (mock *querierMock) CountRepos(ctx context.Context) (int64, error) {
	if mock.CountReposFunc == nil {
		panic("querierMock.CountReposFunc: method is nil but querier.CountRepos was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockCountRepos.Lock()
	mock.calls.CountRepos = append(mock.calls.CountRepos, callInfo)
	mock.lockCountRepos.Unlock()
	return mock.CountReposFunc(ctx)
}

// CountReposCalls gets all the calls that were made to CountRepos.
// Check the length with:
//
//	len(mockedquerier.CountReposCalls())
func (mock *querierMock) CountReposCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockCountRepos.RLock()
	calls = mock.calls.CountRepos
	mock.lockCountRepos.RUnlock()
	return calls
}

// CreateRepo calls CreateRepoFunc.
func (mock *querierMock) CreateRepo(ctx context.Context, arg gen.CreateRepoParams) (gen.Repo, error) {
	if mock.CreateRepoFunc == nil {
		panic("querierMock.CreateRepoFunc: method is nil but querier.CreateRepo was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg gen.CreateRepoParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockCreateRepo.Lock()
	mock.calls.CreateRepo = append(mock.calls.CreateRepo, callInfo)
	mock.lockCreateRepo.Unlock()
	return mock.CreateRepoFunc(ctx, arg)
}

// CreateRepoCalls gets all the calls that were made to CreateRepo.
// Check the length with:
//
//	len(mockedquerier.CreateRepoCalls())
func (mock *querierMock) CreateRepoCalls() []struct {
	Ctx context.Context
	Arg gen.CreateRepoParams
} {
	var calls []struct {
		Ctx context.Context
		Arg gen.CreateRepoParams
	}
	mock.lockCreateRepo.RLock()
	calls = mock.calls.CreateRepo
	mock.lockCreateRepo.RUnlock()
	return calls
}

// GetRepoByID calls GetRepoByIDFunc.
func (mock *querierMock) GetRepoByID(ctx context.Context, id pgtype.UUID) (gen.Repo, error) {
	if mock.GetRepoByIDFunc == nil {
		panic("querierMock.GetRepoByIDFunc: method is nil but querier.GetRepoByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  pgtype.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetRepoByID.Lock()
	mock.calls.GetRepoByID = append(mock.calls.GetRepoByID, callInfo)
	mock.lockGetRepoByID.Unlock()
	return mock.GetRepoByIDFunc(ctx, id)
}

// GetRepoByIDCalls gets all the calls that were made to GetRepoByID.
// Check the length with:
//
//	len(mockedquerier.GetRepoByIDCalls())
func (mock *querierMock) GetRepoByIDCalls() []struct {
	Ctx context.Context
	ID  pgtype.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  pgtype.UUID
	}
	mock.lockGetRepoByID.RLock()
	calls = mock.calls.GetRepoByID
	mock.lockGetRepoByID.RUnlock()
	return calls
}

// GetRepoByName calls GetRepoByNameFunc.
func (mock *querierMock) GetRepoByName(ctx context.Context, name string) (gen.Repo, error) {
	if mock.GetRepoByNameFunc == nil {
		panic("querierMock.GetRepoByNameFunc: method is nil but querier.GetRepoByName was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockGetRepoByName.Lock()
	mock.calls.GetRepoByName = append(mock.calls.GetRepoByName, callInfo)
	mock.lockGetRepoByName.Unlock()
	return mock.GetRepoByNameFunc(ctx, name)
}

// GetRepoByNameCalls gets all the calls that were made to GetRepoByName.
// Check the length with:
//
//	len(mockedquerier.GetRepoByNameCalls())
func (mock *querierMock) GetRepoByNameCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockGetRepoByName.RLock()
	calls = mock.calls.GetRepoByName
	mock.lockGetRepoByName.RUnlock()
	return calls
}

// GetTargetBranch calls GetTargetBranchFunc.
func (mock *querierMock) GetTargetBranch(ctx context.Context, arg gen.GetTargetBranchParams) (gen.RepoTargetBranch, error) {
	if mock.GetTargetBranchFunc == nil {
		panic("querierMock.GetTargetBranchFunc: method is nil but querier.GetTargetBranch was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg gen.GetTargetBranchParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockGetTargetBranch.Lock()
	mock.calls.GetTargetBranch = append(mock.calls.GetTargetBranch, callInfo)
	mock.lockGetTargetBranch.Unlock()
	return mock.GetTargetBranchFunc(ctx, arg)
}

// GetTargetBranchCalls gets all the calls that were made to GetTargetBranch.
// Check the length with:
//
//	len(mockedquerier.GetTargetBranchCalls())
func (mock *querierMock) GetTargetBranchCalls() []struct {
	Ctx context.Context
	Arg gen.GetTargetBranchParams
} {
	var calls []struct {
		Ctx context.Context
		Arg gen.GetTargetBranchParams
	}
	mock.lockGetTargetBranch.RLock()
	calls = mock.calls.GetTargetBranch
	mock.lockGetTargetBranch.RUnlock()
	return calls
}

// ListRepoNames calls ListRepoNamesFunc.
func (mock *querierMock) ListRepoNames(ctx context.Context) ([]string, error) {
	if mock.ListRepoNamesFunc == nil {
		panic("querierMock.ListRepoNamesFunc: method is nil but querier.ListRepoNames was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListRepoNames.Lock()
	mock.calls.ListRepoNames = append(mock.calls.ListRepoNames, callInfo)
	mock.lockListRepoNames.Unlock()
	return mock.ListRepoNamesFunc(ctx)
}

// ListRepoNamesCalls gets all the calls that were made to ListRepoNames.
// Check the length with:
//
//	len(mockedquerier.ListRepoNamesCalls())
func (mock *querierMock) ListRepoNamesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListRepoNames.RLock()
	calls = mock.calls.ListRepoNames
	mock.lockListRepoNames.RUnlock()
	return calls
}

// ListRepos calls ListReposFunc.
func (mock *querierMock) ListRepos(ctx context.Context, arg gen.ListReposParams) ([]gen.Repo, error) {
	if mock.ListReposFunc == nil {
		panic("querierMock.ListReposFunc: method is nil but querier.ListRepos was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg gen.ListReposParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockListRepos.Lock()
	mock.calls.ListRepos = append(mock.calls.ListRepos, callInfo)
	mock.lockListRepos.Unlock()
	return mock.ListReposFunc(ctx, arg)
}

// ListReposCalls gets all the calls that were made to ListRepos.
// Check the length with:
//
//	len(mockedquerier.ListReposCalls())
func (mock *querierMock) ListReposCalls() []struct {
	Ctx context.Context
	Arg gen.ListReposParams
} {
	var calls []struct {
		Ctx context.Context
		Arg gen.ListReposParams
	}
	mock.lockListRepos.RLock()
	calls = mock.calls.ListRepos
	mock.lockListRepos.RUnlock()
	return calls
}

// ListTargetBranches calls ListTargetBranchesFunc.
func (mock *querierMock) ListTargetBranches(ctx context.Context, repoID pgtype.UUID) ([]gen.RepoTargetBranch, error) {
	if mock.ListTargetBranchesFunc == nil {
		panic("querierMock.ListTargetBranchesFunc: method is nil but querier.ListTargetBranches was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		RepoID pgtype.UUID
	}{
		Ctx:    ctx,
		RepoID: repoID,
	}
	mock.lockListTargetBranches.Lock()
	mock.calls.ListTargetBranches = append(mock.calls.ListTargetBranches, callInfo)
	mock.lockListTargetBranches.Unlock()
	return mock.ListTargetBranchesFunc(ctx, repoID)
}

// ListTargetBranchesCalls gets all the calls that were made to ListTargetBranches.
// Check the length with:
//
//	len(mockedquerier.ListTargetBranchesCalls())
func (mock *querierMock) ListTargetBranchesCalls() []struct {
	Ctx    context.Context
	RepoID pgtype.UUID
} {
	var calls []struct {
		Ctx    context.Context
		RepoID pgtype.UUID
	}
	mock.lockListTargetBranches.RLock()
	calls = mock.calls.ListTargetBranches
	mock.lockListTargetBranches.RUnlock()
	return calls
}

// RemoveTargetBranch calls RemoveTargetBranchFunc.
func (mock *querierMock) RemoveTargetBranch(ctx context.Context, arg gen.RemoveTargetBranchParams) (int64, error) {
	if mock.RemoveTargetBranchFunc == nil {
		panic("querierMock.RemoveTargetBranchFunc: method is nil but querier.RemoveTargetBranch was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg gen.RemoveTargetBranchParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockRemoveTargetBranch.Lock()
	mock.calls.RemoveTargetBranch = append(mock.calls.RemoveTargetBranch, callInfo)
	mock.lockRemoveTargetBranch.Unlock()
	return mock.RemoveTargetBranchFunc(ctx, arg)
}

// RemoveTargetBranchCalls gets all the calls that were made to RemoveTargetBranch.
// Check the length with:
//
//	len(mockedquerier.RemoveTargetBranchCalls())
func (mock *querierMock) RemoveTargetBranchCalls() []struct {
	Ctx context.Context
	Arg gen.RemoveTargetBranchParams
} {
	var calls []struct {
		Ctx context.Context
		Arg gen.RemoveTargetBranchParams
	}
	mock.lockRemoveTargetBranch.RLock()
	calls = mock.calls.RemoveTargetBranch
	mock.lockRemoveTargetBranch.RUnlock()
	return calls
}

// UpdateRepo calls UpdateRepoFunc.
func (mock *querierMock) UpdateRepo(ctx context.Context, arg gen.UpdateRepoParams) (gen.Repo, error) {
	if mock.UpdateRepoFunc == nil {
		panic("querierMock.UpdateRepoFunc: method is nil but querier.UpdateRepo was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg gen.UpdateRepoParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockUpdateRepo.Lock()
	mock.calls.UpdateRepo = append(mock.calls.UpdateRepo, callInfo)
	mock.lockUpdateRepo.Unlock()
	return mock.UpdateRepoFunc(ctx, arg)
}

// UpdateRepoCalls gets all the calls that were made to UpdateRepo.
// Check the length with:
//
//	len(mockedquerier.UpdateRepoCalls())
func (mock *querierMock) UpdateRepoCalls() []struct {
	Ctx context.Context
	Arg gen.UpdateRepoParams
} {
	var calls []struct {
		Ctx context.Context
		Arg gen.UpdateRepoParams
	}
	mock.lockUpdateRepo.RLock()
	calls = mock.calls.UpdateRepo
	mock.lockUpdateRepo.RUnlock()
	return calls
}
