// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package chunkstore

import (
	"context"
	"github.com/bobcob7/loam/internal/db/gen"
	"github.com/jackc/pgx/v5/pgconn"
	"sync"
)

// Ensure, that queriesMock does implement queries.
// If this is not the case, regenerate this file with moq.
var _ queries = &queriesMock{}

// queriesMock is a mock implementation of queries.
//
//	func TestSomethingThatUsesqueries(t *testing.T) {
//
//		// make and configure a mocked queries
//		mockedqueries := &queriesMock{
//			CountChunksByFileFunc: func(ctx context.Context, arg gen.CountChunksByFileParams) (int64, error) {
//				panic("mock out the CountChunksByFile method")
//			},
//			DeleteChunksByFileFunc: func(ctx context.Context, arg gen.DeleteChunksByFileParams) error {
//				panic("mock out the DeleteChunksByFile method")
//			},
//			DeleteChunksForRepoBranchFunc: func(ctx context.Context, arg gen.DeleteChunksForRepoBranchParams) error {
//				panic("mock out the DeleteChunksForRepoBranch method")
//			},
//			InsertChunkFunc: func(ctx context.Context, arg gen.InsertChunkParams) (gen.Chunk, error) {
//				panic("mock out the InsertChunk method")
//			},
//			SearchChunksByEmbeddingScopedFunc: func(ctx context.Context, arg gen.SearchChunksByEmbeddingScopedParams) ([]gen.Chunk, error) {
//				panic("mock out the SearchChunksByEmbeddingScoped method")
//			},
//		}
//
//		// use mockedqueries in code that requires queries
//		// and then make assertions.
//
//	}
type queriesMock struct {
	// CountChunksByFileFunc mocks the CountChunksByFile method.
	CountChunksByFileFunc func(ctx context.Context, arg gen.CountChunksByFileParams) (int64, error)

	// DeleteChunksByFileFunc mocks the DeleteChunksByFile method.
	DeleteChunksByFileFunc func(ctx context.Context, arg gen.DeleteChunksByFileParams) error

	// DeleteChunksForRepoBranchFunc mocks the DeleteChunksForRepoBranch method.
	DeleteChunksForRepoBranchFunc func(ctx context.Context, arg gen.DeleteChunksForRepoBranchParams) error

	// InsertChunkFunc mocks the InsertChunk method.
	InsertChunkFunc func(ctx context.Context, arg gen.InsertChunkParams) (gen.Chunk, error)

	// SearchChunksByEmbeddingScopedFunc mocks the SearchChunksByEmbeddingScoped method.
	SearchChunksByEmbeddingScopedFunc func(ctx context.Context, arg gen.SearchChunksByEmbeddingScopedParams) ([]gen.Chunk, error)

	// calls tracks calls to the methods.
	calls struct {
		// CountChunksByFile holds details about calls to the CountChunksByFile method.
		CountChunksByFile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg gen.CountChunksByFileParams
		}
		// DeleteChunksByFile holds details about calls to the DeleteChunksByFile method.
		DeleteChunksByFile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg gen.DeleteChunksByFileParams
		}
		// DeleteChunksForRepoBranch holds details about calls to the DeleteChunksForRepoBranch method.
		DeleteChunksForRepoBranch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg gen.DeleteChunksForRepoBranchParams
		}
		// InsertChunk holds details about calls to the InsertChunk method.
		InsertChunk []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg gen.InsertChunkParams
		}
		// SearchChunksByEmbeddingScoped holds details about calls to the SearchChunksByEmbeddingScoped method.
		SearchChunksByEmbeddingScoped []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg gen.SearchChunksByEmbeddingScopedParams
		}
	}
	lockCountChunksByFile             sync.RWMutex
	lockDeleteChunksByFile            sync.RWMutex
	lockDeleteChunksForRepoBranch     sync.RWMutex
	lockInsertChunk                   sync.RWMutex
	lockSearchChunksByEmbeddingScoped sync.RWMutex
}

// CountChunksByFile calls CountChunksByFileFunc.
func (mock *queriesMock) CountChunksByFile(ctx context.Context, arg gen.CountChunksByFileParams) (int64, error) {
	if mock.CountChunksByFileFunc == nil {
		panic("queriesMock.CountChunksByFileFunc: method is nil but queries.CountChunksByFile was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg gen.CountChunksByFileParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockCountChunksByFile.Lock()
	mock.calls.CountChunksByFile = append(mock.calls.CountChunksByFile, callInfo)
	mock.lockCountChunksByFile.Unlock()
	return mock.CountChunksByFileFunc(ctx, arg)
}

// CountChunksByFileCalls gets all the calls that were made to CountChunksByFile.
// Check the length with:
//
//	len(mockedqueries.CountChunksByFileCalls())
func (mock *queriesMock) CountChunksByFileCalls() []struct {
	Ctx context.Context
	Arg gen.CountChunksByFileParams
} {
	var calls []struct {
		Ctx context.Context
		Arg gen.CountChunksByFileParams
	}
	mock.lockCountChunksByFile.RLock()
	calls = mock.calls.CountChunksByFile
	mock.lockCountChunksByFile.RUnlock()
	return calls
}

// DeleteChunksByFile calls DeleteChunksByFileFunc.
func (mock *queriesMock) DeleteChunksByFile(ctx context.Context, arg gen.DeleteChunksByFileParams) error {
	if mock.DeleteChunksByFileFunc == nil {
		panic("queriesMock.DeleteChunksByFileFunc: method is nil but queries.DeleteChunksByFile was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg gen.DeleteChunksByFileParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockDeleteChunksByFile.Lock()
	mock.calls.DeleteChunksByFile = append(mock.calls.DeleteChunksByFile, callInfo)
	mock.lockDeleteChunksByFile.Unlock()
	return mock.DeleteChunksByFileFunc(ctx, arg)
}

// DeleteChunksByFileCalls gets all the calls that were made to DeleteChunksByFile.
// Check the length with:
//
//	len(mockedqueries.DeleteChunksByFileCalls())
func (mock *queriesMock) DeleteChunksByFileCalls() []struct {
	Ctx context.Context
	Arg gen.DeleteChunksByFileParams
} {
	var calls []struct {
		Ctx context.Context
		Arg gen.DeleteChunksByFileParams
	}
	mock.lockDeleteChunksByFile.RLock()
	calls = mock.calls.DeleteChunksByFile
	mock.lockDeleteChunksByFile.RUnlock()
	return calls
}

// DeleteChunksForRepoBranch calls DeleteChunksForRepoBranchFunc.
func (mock *queriesMock) DeleteChunksForRepoBranch(ctx context.Context, arg gen.DeleteChunksForRepoBranchParams) error {
	if mock.DeleteChunksForRepoBranchFunc == nil {
		panic("queriesMock.DeleteChunksForRepoBranchFunc: method is nil but queries.DeleteChunksForRepoBranch was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg gen.DeleteChunksForRepoBranchParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockDeleteChunksForRepoBranch.Lock()
	mock.calls.DeleteChunksForRepoBranch = append(mock.calls.DeleteChunksForRepoBranch, callInfo)
	mock.lockDeleteChunksForRepoBranch.Unlock()
	return mock.DeleteChunksForRepoBranchFunc(ctx, arg)
}

// DeleteChunksForRepoBranchCalls gets all the calls that were made to DeleteChunksForRepoBranch.
// Check the length with:
//
//	len(mockedqueries.DeleteChunksForRepoBranchCalls())
func (mock *queriesMock) DeleteChunksForRepoBranchCalls() []struct {
	Ctx context.Context
	Arg gen.DeleteChunksForRepoBranchParams
} {
	var calls []struct {
		Ctx context.Context
		Arg gen.DeleteChunksForRepoBranchParams
	}
	mock.lockDeleteChunksForRepoBranch.RLock()
	calls = mock.calls.DeleteChunksForRepoBranch
	mock.lockDeleteChunksForRepoBranch.RUnlock()
	return calls
}

// InsertChunk calls InsertChunkFunc.
func (mock *queriesMock) InsertChunk(ctx context.Context, arg gen.InsertChunkParams) (gen.Chunk, error) {
	if mock.InsertChunkFunc == nil {
		panic("queriesMock.InsertChunkFunc: method is nil but queries.InsertChunk was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg gen.InsertChunkParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockInsertChunk.Lock()
	mock.calls.InsertChunk = append(mock.calls.InsertChunk, callInfo)
	mock.lockInsertChunk.Unlock()
	return mock.InsertChunkFunc(ctx, arg)
}

// InsertChunkCalls gets all the calls that were made to InsertChunk.
// Check the length with:
//
//	len(mockedqueries.InsertChunkCalls())
func (mock *queriesMock) InsertChunkCalls() []struct {
	Ctx context.Context
	Arg gen.InsertChunkParams
} {
	var calls []struct {
		Ctx context.Context
		Arg gen.InsertChunkParams
	}
	mock.lockInsertChunk.RLock()
	calls = mock.calls.InsertChunk
	mock.lockInsertChunk.RUnlock()
	return calls
}

// SearchChunksByEmbeddingScoped calls SearchChunksByEmbeddingScopedFunc.
func (mock *queriesMock) SearchChunksByEmbeddingScoped(ctx context.Context, arg gen.SearchChunksByEmbeddingScopedParams) ([]gen.Chunk, error) {
	if mock.SearchChunksByEmbeddingScopedFunc == nil {
		panic("queriesMock.SearchChunksByEmbeddingScopedFunc: method is nil but queries.SearchChunksByEmbeddingScoped was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg gen.SearchChunksByEmbeddingScopedParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockSearchChunksByEmbeddingScoped.Lock()
	mock.calls.SearchChunksByEmbeddingScoped = append(mock.calls.SearchChunksByEmbeddingScoped, callInfo)
	mock.lockSearchChunksByEmbeddingScoped.Unlock()
	return mock.SearchChunksByEmbeddingScopedFunc(ctx, arg)
}

// SearchChunksByEmbeddingScopedCalls gets all the calls that were made to SearchChunksByEmbeddingScoped.
// Check the length with:
//
//	len(mockedqueries.SearchChunksByEmbeddingScopedCalls())
func (mock *queriesMock) SearchChunksByEmbeddingScopedCalls() []struct {
	Ctx context.Context
	Arg gen.SearchChunksByEmbeddingScopedParams
} {
	var calls []struct {
		Ctx context.Context
		Arg gen.SearchChunksByEmbeddingScopedParams
	}
	mock.lockSearchChunksByEmbeddingScoped.RLock()
	calls = mock.calls.SearchChunksByEmbeddingScoped
	mock.lockSearchChunksByEmbeddingScoped.RUnlock()
	return calls
}

// Ensure, that transactorMock does implement transactor.
// If this is not the case, regenerate this file with moq.
var _ transactor = &transactorMock{}

// transactorMock is a mock implementation of transactor.
//
//	func TestSomethingThatUsestransactor(t *testing.T) {
//
//		// make and configure a mocked transactor
//		mockedtransactor := &transactorMock{
//			withinTxFunc: func(ctx context.Context, fn func(q queries) error) error {
//				panic("mock out the withinTx method")
//			},
//		}
//
//		// use mockedtransactor in code that requires transactor
//		// and then make assertions.
//
//	}
type transactorMock struct {
	// withinTxFunc mocks the withinTx method.
	withinTxFunc func(ctx context.Context, fn func(q queries) error) error

	// calls tracks calls to the methods.
	calls struct {
		// withinTx holds details about calls to the withinTx method.
		withinTx []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Fn is the fn argument value.
			Fn func(q queries) error
		}
	}
	lockwithinTx sync.RWMutex
}

// withinTx calls withinTxFunc.
func (mock *transactorMock) withinTx(ctx context.Context, fn func(q queries) error) error {
	if mock.withinTxFunc == nil {
		panic("transactorMock.withinTxFunc: method is nil but transactor.withinTx was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Fn  func(q queries) error
	}{
		Ctx: ctx,
		Fn:  fn,
	}
	mock.lockwithinTx.Lock()
	mock.calls.withinTx = append(mock.calls.withinTx, callInfo)
	mock.lockwithinTx.Unlock()
	return mock.withinTxFunc(ctx, fn)
}

// withinTxCalls gets all the calls that were made to withinTx.
// Check the length with:
//
//	len(mockedtransactor.withinTxCalls())
func (mock *transactorMock) withinTxCalls() []struct {
	Ctx context.Context
	Fn  func(q queries) error
} {
	var calls []struct {
		Ctx context.Context
		Fn  func(q queries) error
	}
	mock.lockwithinTx.RLock()
	calls = mock.calls.withinTx
	mock.lockwithinTx.RUnlock()
	return calls
}

// Ensure, that savepointExecerMock does implement savepointExecer.
// If this is not the case, regenerate this file with moq.
var _ savepointExecer = &savepointExecerMock{}

// savepointExecerMock is a mock implementation of savepointExecer.
//
//	func TestSomethingThatUsessavepointExecer(t *testing.T) {
//
//		// make and configure a mocked savepointExecer
//		mockedsavepointExecer := &savepointExecerMock{
//			ExecFunc: func(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error) {
//				panic("mock out the Exec method")
//			},
//		}
//
//		// use mockedsavepointExecer in code that requires savepointExecer
//		// and then make assertions.
//
//	}
type savepointExecerMock struct {
	// ExecFunc mocks the Exec method.
	ExecFunc func(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error)

	// calls tracks calls to the methods.
	calls struct {
		// Exec holds details about calls to the Exec method.
		Exec []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SQL is the sql argument value.
			SQL string
			// Args is the args argument value.
			Args []any
		}
	}
	lockExec sync.RWMutex
}

// Exec calls ExecFunc.
func (mock *savepointExecerMock) Exec(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error) {
	if mock.ExecFunc == nil {
		panic("savepointExecerMock.ExecFunc: method is nil but savepointExecer.Exec was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		SQL  string
		Args []any
	}{
		Ctx:  ctx,
		SQL:  sql,
		Args: args,
	}
	mock.lockExec.Lock()
	mock.calls.Exec = append(mock.calls.Exec, callInfo)
	mock.lockExec.Unlock()
	return mock.ExecFunc(ctx, sql, args...)
}

// ExecCalls gets all the calls that were made to Exec.
// Check the length with:
//
//	len(mockedsavepointExecer.ExecCalls())
func (mock *savepointExecerMock) ExecCalls() []struct {
	Ctx  context.Context
	SQL  string
	Args []any
} {
	var calls []struct {
		Ctx  context.Context
		SQL  string
		Args []any
	}
	mock.lockExec.RLock()
	calls = mock.calls.Exec
	mock.lockExec.RUnlock()
	return calls
}

// Ensure, that rejectionQueriesMock does implement rejectionQueries.
// If this is not the case, regenerate this file with moq.
var _ rejectionQueries = &rejectionQueriesMock{}

// rejectionQueriesMock is a mock implementation of rejectionQueries.
//
//	func TestSomethingThatUsesrejectionQueries(t *testing.T) {
//
//		// make and configure a mocked rejectionQueries
//		mockedrejectionQueries := &rejectionQueriesMock{
//			DeleteChunkRejectionsFunc: func(ctx context.Context, arg gen.DeleteChunkRejectionsParams) error {
//				panic("mock out the DeleteChunkRejections method")
//			},
//			DeleteChunkRejectionsForRepoBranchFunc: func(ctx context.Context, arg gen.DeleteChunkRejectionsForRepoBranchParams) error {
//				panic("mock out the DeleteChunkRejectionsForRepoBranch method")
//			},
//			ListChunkRejectionsFunc: func(ctx context.Context, arg gen.ListChunkRejectionsParams) ([]gen.ChunkRejection, error) {
//				panic("mock out the ListChunkRejections method")
//			},
//			RecordChunkRejectionFunc: func(ctx context.Context, arg gen.RecordChunkRejectionParams) error {
//				panic("mock out the RecordChunkRejection method")
//			},
//		}
//
//		// use mockedrejectionQueries in code that requires rejectionQueries
//		// and then make assertions.
//
//	}
type rejectionQueriesMock struct {
	// DeleteChunkRejectionsFunc mocks the DeleteChunkRejections method.
	DeleteChunkRejectionsFunc func(ctx context.Context, arg gen.DeleteChunkRejectionsParams) error

	// DeleteChunkRejectionsForRepoBranchFunc mocks the DeleteChunkRejectionsForRepoBranch method.
	DeleteChunkRejectionsForRepoBranchFunc func(ctx context.Context, arg gen.DeleteChunkRejectionsForRepoBranchParams) error

	// ListChunkRejectionsFunc mocks the ListChunkRejections method.
	ListChunkRejectionsFunc func(ctx context.Context, arg gen.ListChunkRejectionsParams) ([]gen.ChunkRejection, error)

	// RecordChunkRejectionFunc mocks the RecordChunkRejection method.
	RecordChunkRejectionFunc func(ctx context.Context, arg gen.RecordChunkRejectionParams) error

	// calls tracks calls to the methods.
	calls struct {
		// DeleteChunkRejections holds details about calls to the DeleteChunkRejections method.
		DeleteChunkRejections []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg gen.DeleteChunkRejectionsParams
		}
		// DeleteChunkRejectionsForRepoBranch holds details about calls to the DeleteChunkRejectionsForRepoBranch method.
		DeleteChunkRejectionsForRepoBranch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg gen.DeleteChunkRejectionsForRepoBranchParams
		}
		// ListChunkRejections holds details about calls to the ListChunkRejections method.
		ListChunkRejections []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg gen.ListChunkRejectionsParams
		}
		// RecordChunkRejection holds details about calls to the RecordChunkRejection method.
		RecordChunkRejection []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg gen.RecordChunkRejectionParams
		}
	}
	lockDeleteChunkRejections              sync.RWMutex
	lockDeleteChunkRejectionsForRepoBranch sync.RWMutex
	lockListChunkRejections                sync.RWMutex
	lockRecordChunkRejection               sync.RWMutex
}

// DeleteChunkRejections calls DeleteChunkRejectionsFunc.
func (mock *rejectionQueriesMock) DeleteChunkRejections(ctx context.Context, arg gen.DeleteChunkRejectionsParams) error {
	if mock.DeleteChunkRejectionsFunc == nil {
		panic("rejectionQueriesMock.DeleteChunkRejectionsFunc: method is nil but rejectionQueries.DeleteChunkRejections was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg gen.DeleteChunkRejectionsParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockDeleteChunkRejections.Lock()
	mock.calls.DeleteChunkRejections = append(mock.calls.DeleteChunkRejections, callInfo)
	mock.lockDeleteChunkRejections.Unlock()
	return mock.DeleteChunkRejectionsFunc(ctx, arg)
}

// DeleteChunkRejectionsCalls gets all the calls that were made to DeleteChunkRejections.
// Check the length with:
//
//	len(mockedrejectionQueries.DeleteChunkRejectionsCalls())
func (mock *rejectionQueriesMock) DeleteChunkRejectionsCalls() []struct {
	Ctx context.Context
	Arg gen.DeleteChunkRejectionsParams
} {
	var calls []struct {
		Ctx context.Context
		Arg gen.DeleteChunkRejectionsParams
	}
	mock.lockDeleteChunkRejections.RLock()
	calls = mock.calls.DeleteChunkRejections
	mock.lockDeleteChunkRejections.RUnlock()
	return calls
}

// DeleteChunkRejectionsForRepoBranch calls DeleteChunkRejectionsForRepoBranchFunc.
func (mock *rejectionQueriesMock) DeleteChunkRejectionsForRepoBranch(ctx context.Context, arg gen.DeleteChunkRejectionsForRepoBranchParams) error {
	if mock.DeleteChunkRejectionsForRepoBranchFunc == nil {
		panic("rejectionQueriesMock.DeleteChunkRejectionsForRepoBranchFunc: method is nil but rejectionQueries.DeleteChunkRejectionsForRepoBranch was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg gen.DeleteChunkRejectionsForRepoBranchParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockDeleteChunkRejectionsForRepoBranch.Lock()
	mock.calls.DeleteChunkRejectionsForRepoBranch = append(mock.calls.DeleteChunkRejectionsForRepoBranch, callInfo)
	mock.lockDeleteChunkRejectionsForRepoBranch.Unlock()
	return mock.DeleteChunkRejectionsForRepoBranchFunc(ctx, arg)
}

// DeleteChunkRejectionsForRepoBranchCalls gets all the calls that were made to DeleteChunkRejectionsForRepoBranch.
// Check the length with:
//
//	len(mockedrejectionQueries.DeleteChunkRejectionsForRepoBranchCalls())
func (mock *rejectionQueriesMock) DeleteChunkRejectionsForRepoBranchCalls() []struct {
	Ctx context.Context
	Arg gen.DeleteChunkRejectionsForRepoBranchParams
} {
	var calls []struct {
		Ctx context.Context
		Arg gen.DeleteChunkRejectionsForRepoBranchParams
	}
	mock.lockDeleteChunkRejectionsForRepoBranch.RLock()
	calls = mock.calls.DeleteChunkRejectionsForRepoBranch
	mock.lockDeleteChunkRejectionsForRepoBranch.RUnlock()
	return calls
}

// ListChunkRejections calls ListChunkRejectionsFunc.
func (mock *rejectionQueriesMock) ListChunkRejections(ctx context.Context, arg gen.ListChunkRejectionsParams) ([]gen.ChunkRejection, error) {
	if mock.ListChunkRejectionsFunc == nil {
		panic("rejectionQueriesMock.ListChunkRejectionsFunc: method is nil but rejectionQueries.ListChunkRejections was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg gen.ListChunkRejectionsParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockListChunkRejections.Lock()
	mock.calls.ListChunkRejections = append(mock.calls.ListChunkRejections, callInfo)
	mock.lockListChunkRejections.Unlock()
	return mock.ListChunkRejectionsFunc(ctx, arg)
}

// ListChunkRejectionsCalls gets all the calls that were made to ListChunkRejections.
// Check the length with:
//
//	len(mockedrejectionQueries.ListChunkRejectionsCalls())
func (mock *rejectionQueriesMock) ListChunkRejectionsCalls() []struct {
	Ctx context.Context
	Arg gen.ListChunkRejectionsParams
} {
	var calls []struct {
		Ctx context.Context
		Arg gen.ListChunkRejectionsParams
	}
	mock.lockListChunkRejections.RLock()
	calls = mock.calls.ListChunkRejections
	mock.lockListChunkRejections.RUnlock()
	return calls
}

// RecordChunkRejection calls RecordChunkRejectionFunc.
func (mock *rejectionQueriesMock) RecordChunkRejection(ctx context.Context, arg gen.RecordChunkRejectionParams) error {
	if mock.RecordChunkRejectionFunc == nil {
		panic("rejectionQueriesMock.RecordChunkRejectionFunc: method is nil but rejectionQueries.RecordChunkRejection was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg gen.RecordChunkRejectionParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockRecordChunkRejection.Lock()
	mock.calls.RecordChunkRejection = append(mock.calls.RecordChunkRejection, callInfo)
	mock.lockRecordChunkRejection.Unlock()
	return mock.RecordChunkRejectionFunc(ctx, arg)
}

// RecordChunkRejectionCalls gets all the calls that were made to RecordChunkRejection.
// Check the length with:
//
//	len(mockedrejectionQueries.RecordChunkRejectionCalls())
func (mock *rejectionQueriesMock) RecordChunkRejectionCalls() []struct {
	Ctx context.Context
	Arg gen.RecordChunkRejectionParams
} {
	var calls []struct {
		Ctx context.Context
		Arg gen.RecordChunkRejectionParams
	}
	mock.lockRecordChunkRejection.RLock()
	calls = mock.calls.RecordChunkRejection
	mock.lockRecordChunkRejection.RUnlock()
	return calls
}
