// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package vectors

import (
	"context"
	"github.com/bobcob7/loam/internal/chunkstore"
	"github.com/google/uuid"
	"sync"
)

// Ensure, that embedderMock does implement embedder.
// If this is not the case, regenerate this file with moq.
var _ embedder = &embedderMock{}

// embedderMock is a mock implementation of embedder.
//
//	func TestSomethingThatUsesembedder(t *testing.T) {
//
//		// make and configure a mocked embedder
//		mockedembedder := &embedderMock{
//			DimensionFunc: func() int {
//				panic("mock out the Dimension method")
//			},
//			EmbedFunc: func(ctx context.Context, texts []string) ([][]float32, error) {
//				panic("mock out the Embed method")
//			},
//		}
//
//		// use mockedembedder in code that requires embedder
//		// and then make assertions.
//
//	}
type embedderMock struct {
	// DimensionFunc mocks the Dimension method.
	DimensionFunc func() int

	// EmbedFunc mocks the Embed method.
	EmbedFunc func(ctx context.Context, texts []string) ([][]float32, error)

	// calls tracks calls to the methods.
	calls struct {
		// Dimension holds details about calls to the Dimension method.
		Dimension []struct {
		}
		// Embed holds details about calls to the Embed method.
		Embed []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Texts is the texts argument value.
			Texts []string
		}
	}
	lockDimension sync.RWMutex
	lockEmbed     sync.RWMutex
}

// Dimension calls DimensionFunc.
func (mock *embedderMock) Dimension() int {
	if mock.DimensionFunc == nil {
		panic("embedderMock.DimensionFunc: method is nil but embedder.Dimension was just called")
	}
	callInfo := struct {
	}{}
	mock.lockDimension.Lock()
	mock.calls.Dimension = append(mock.calls.Dimension, callInfo)
	mock.lockDimension.Unlock()
	return mock.DimensionFunc()
}

// DimensionCalls gets all the calls that were made to Dimension.
// Check the length with:
//
//	len(mockedembedder.DimensionCalls())
func (mock *embedderMock) DimensionCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockDimension.RLock()
	calls = mock.calls.Dimension
	mock.lockDimension.RUnlock()
	return calls
}

// Embed calls EmbedFunc.
func (mock *embedderMock) Embed(ctx context.Context, texts []string) ([][]float32, error) {
	if mock.EmbedFunc == nil {
		panic("embedderMock.EmbedFunc: method is nil but embedder.Embed was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Texts []string
	}{
		Ctx:   ctx,
		Texts: texts,
	}
	mock.lockEmbed.Lock()
	mock.calls.Embed = append(mock.calls.Embed, callInfo)
	mock.lockEmbed.Unlock()
	return mock.EmbedFunc(ctx, texts)
}

// EmbedCalls gets all the calls that were made to Embed.
// Check the length with:
//
//	len(mockedembedder.EmbedCalls())
func (mock *embedderMock) EmbedCalls() []struct {
	Ctx   context.Context
	Texts []string
} {
	var calls []struct {
		Ctx   context.Context
		Texts []string
	}
	mock.lockEmbed.RLock()
	calls = mock.calls.Embed
	mock.lockEmbed.RUnlock()
	return calls
}

// Ensure, that storeMock does implement store.
// If this is not the case, regenerate this file with moq.
var _ store = &storeMock{}

// storeMock is a mock implementation of store.
//
//	func TestSomethingThatUsesstore(t *testing.T) {
//
//		// make and configure a mocked store
//		mockedstore := &storeMock{
//			ReplaceFileChunksFunc: func(ctx context.Context, repoID uuid.UUID, targetBranch string, file string, inputs []chunkstore.ChunkInput) ([]chunkstore.Chunk, error) {
//				panic("mock out the ReplaceFileChunks method")
//			},
//		}
//
//		// use mockedstore in code that requires store
//		// and then make assertions.
//
//	}
type storeMock struct {
	// ReplaceFileChunksFunc mocks the ReplaceFileChunks method.
	ReplaceFileChunksFunc func(ctx context.Context, repoID uuid.UUID, targetBranch string, file string, inputs []chunkstore.ChunkInput) ([]chunkstore.Chunk, error)

	// calls tracks calls to the methods.
	calls struct {
		// ReplaceFileChunks holds details about calls to the ReplaceFileChunks method.
		ReplaceFileChunks []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RepoID is the repoID argument value.
			RepoID uuid.UUID
			// TargetBranch is the targetBranch argument value.
			TargetBranch string
			// File is the file argument value.
			File string
			// Inputs is the inputs argument value.
			Inputs []chunkstore.ChunkInput
		}
	}
	lockReplaceFileChunks sync.RWMutex
}

// ReplaceFileChunks calls ReplaceFileChunksFunc.
func (mock *storeMock) ReplaceFileChunks(ctx context.Context, repoID uuid.UUID, targetBranch string, file string, inputs []chunkstore.ChunkInput) ([]chunkstore.Chunk, error) {
	if mock.ReplaceFileChunksFunc == nil {
		panic("storeMock.ReplaceFileChunksFunc: method is nil but store.ReplaceFileChunks was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		RepoID       uuid.UUID
		TargetBranch string
		File         string
		Inputs       []chunkstore.ChunkInput
	}{
		Ctx:          ctx,
		RepoID:       repoID,
		TargetBranch: targetBranch,
		File:         file,
		Inputs:       inputs,
	}
	mock.lockReplaceFileChunks.Lock()
	mock.calls.ReplaceFileChunks = append(mock.calls.ReplaceFileChunks, callInfo)
	mock.lockReplaceFileChunks.Unlock()
	return mock.ReplaceFileChunksFunc(ctx, repoID, targetBranch, file, inputs)
}

// ReplaceFileChunksCalls gets all the calls that were made to ReplaceFileChunks.
// Check the length with:
//
//	len(mockedstore.ReplaceFileChunksCalls())
func (mock *storeMock) ReplaceFileChunksCalls() []struct {
	Ctx          context.Context
	RepoID       uuid.UUID
	TargetBranch string
	File         string
	Inputs       []chunkstore.ChunkInput
} {
	var calls []struct {
		Ctx          context.Context
		RepoID       uuid.UUID
		TargetBranch string
		File         string
		Inputs       []chunkstore.ChunkInput
	}
	mock.lockReplaceFileChunks.RLock()
	calls = mock.calls.ReplaceFileChunks
	mock.lockReplaceFileChunks.RUnlock()
	return calls
}
