// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package forge

import (
	"context"
	"sync"
)

// Ensure, that ProviderMock does implement Provider.
// If this is not the case, regenerate this file with moq.
var _ Provider = &ProviderMock{}

// ProviderMock is a mock implementation of Provider.
//
//	func TestSomethingThatUsesProvider(t *testing.T) {
//
//		// make and configure a mocked Provider
//		mockedProvider := &ProviderMock{
//			CheckRepoFunc: func(ctx context.Context, upstreamURL string) error {
//				panic("mock out the CheckRepo method")
//			},
//			ClosePRFunc: func(ctx context.Context, repo string, prNumber int) error {
//				panic("mock out the ClosePR method")
//			},
//			CreatePRFunc: func(ctx context.Context, repo string, headBranch string, targetBranch string, title string, description string) (string, int, error) {
//				panic("mock out the CreatePR method")
//			},
//			GetPRStateFunc: func(ctx context.Context, repo string, prNumber int) (string, error) {
//				panic("mock out the GetPRState method")
//			},
//			GitCredentialsFunc: func(ctx context.Context, token string) (string, string, error) {
//				panic("mock out the GitCredentials method")
//			},
//			ValidateTokenFunc: func(ctx context.Context, host string, token string) error {
//				panic("mock out the ValidateToken method")
//			},
//		}
//
//		// use mockedProvider in code that requires Provider
//		// and then make assertions.
//
//	}
type ProviderMock struct {
	// CheckRepoFunc mocks the CheckRepo method.
	CheckRepoFunc func(ctx context.Context, upstreamURL string) error

	// ClosePRFunc mocks the ClosePR method.
	ClosePRFunc func(ctx context.Context, repo string, prNumber int) error

	// CreatePRFunc mocks the CreatePR method.
	CreatePRFunc func(ctx context.Context, repo string, headBranch string, targetBranch string, title string, description string) (string, int, error)

	// GetPRStateFunc mocks the GetPRState method.
	GetPRStateFunc func(ctx context.Context, repo string, prNumber int) (string, error)

	// GitCredentialsFunc mocks the GitCredentials method.
	GitCredentialsFunc func(ctx context.Context, token string) (string, string, error)

	// ValidateTokenFunc mocks the ValidateToken method.
	ValidateTokenFunc func(ctx context.Context, host string, token string) error

	// calls tracks calls to the methods.
	calls struct {
		// CheckRepo holds details about calls to the CheckRepo method.
		CheckRepo []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UpstreamURL is the upstreamURL argument value.
			UpstreamURL string
		}
		// ClosePR holds details about calls to the ClosePR method.
		ClosePR []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Repo is the repo argument value.
			Repo string
			// PrNumber is the prNumber argument value.
			PrNumber int
		}
		// CreatePR holds details about calls to the CreatePR method.
		CreatePR []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Repo is the repo argument value.
			Repo string
			// HeadBranch is the headBranch argument value.
			HeadBranch string
			// TargetBranch is the targetBranch argument value.
			TargetBranch string
			// Title is the title argument value.
			Title string
			// Description is the description argument value.
			Description string
		}
		// GetPRState holds details about calls to the GetPRState method.
		GetPRState []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Repo is the repo argument value.
			Repo string
			// PrNumber is the prNumber argument value.
			PrNumber int
		}
		// GitCredentials holds details about calls to the GitCredentials method.
		GitCredentials []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Token is the token argument value.
			Token string
		}
		// ValidateToken holds details about calls to the ValidateToken method.
		ValidateToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Host is the host argument value.
			Host string
			// Token is the token argument value.
			Token string
		}
	}
	lockCheckRepo      sync.RWMutex
	lockClosePR        sync.RWMutex
	lockCreatePR       sync.RWMutex
	lockGetPRState     sync.RWMutex
	lockGitCredentials sync.RWMutex
	lockValidateToken  sync.RWMutex
}

// CheckRepo calls CheckRepoFunc.
func (mock *ProviderMock) CheckRepo(ctx context.Context, upstreamURL string) error {
	if mock.CheckRepoFunc == nil {
		panic("ProviderMock.CheckRepoFunc: method is nil but Provider.CheckRepo was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		UpstreamURL string
	}{
		Ctx:         ctx,
		UpstreamURL: upstreamURL,
	}
	mock.lockCheckRepo.Lock()
	mock.calls.CheckRepo = append(mock.calls.CheckRepo, callInfo)
	mock.lockCheckRepo.Unlock()
	return mock.CheckRepoFunc(ctx, upstreamURL)
}

// CheckRepoCalls gets all the calls that were made to CheckRepo.
// Check the length with:
//
//	len(mockedProvider.CheckRepoCalls())
func (mock *ProviderMock) CheckRepoCalls() []struct {
	Ctx         context.Context
	UpstreamURL string
} {
	var calls []struct {
		Ctx         context.Context
		UpstreamURL string
	}
	mock.lockCheckRepo.RLock()
	calls = mock.calls.CheckRepo
	mock.lockCheckRepo.RUnlock()
	return calls
}

// ClosePR calls ClosePRFunc.
func (mock *ProviderMock) ClosePR(ctx context.Context, repo string, prNumber int) error {
	if mock.ClosePRFunc == nil {
		panic("ProviderMock.ClosePRFunc: method is nil but Provider.ClosePR was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Repo     string
		PrNumber int
	}{
		Ctx:      ctx,
		Repo:     repo,
		PrNumber: prNumber,
	}
	mock.lockClosePR.Lock()
	mock.calls.ClosePR = append(mock.calls.ClosePR, callInfo)
	mock.lockClosePR.Unlock()
	return mock.ClosePRFunc(ctx, repo, prNumber)
}

// ClosePRCalls gets all the calls that were made to ClosePR.
// Check the length with:
//
//	len(mockedProvider.ClosePRCalls())
func (mock *ProviderMock) ClosePRCalls() []struct {
	Ctx      context.Context
	Repo     string
	PrNumber int
} {
	var calls []struct {
		Ctx      context.Context
		Repo     string
		PrNumber int
	}
	mock.lockClosePR.RLock()
	calls = mock.calls.ClosePR
	mock.lockClosePR.RUnlock()
	return calls
}

// CreatePR calls CreatePRFunc.
func (mock *ProviderMock) CreatePR(ctx context.Context, repo string, headBranch string, targetBranch string, title string, description string) (string, int, error) {
	if mock.CreatePRFunc == nil {
		panic("ProviderMock.CreatePRFunc: method is nil but Provider.CreatePR was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		Repo         string
		HeadBranch   string
		TargetBranch string
		Title        string
		Description  string
	}{
		Ctx:          ctx,
		Repo:         repo,
		HeadBranch:   headBranch,
		TargetBranch: targetBranch,
		Title:        title,
		Description:  description,
	}
	mock.lockCreatePR.Lock()
	mock.calls.CreatePR = append(mock.calls.CreatePR, callInfo)
	mock.lockCreatePR.Unlock()
	return mock.CreatePRFunc(ctx, repo, headBranch, targetBranch, title, description)
}

// CreatePRCalls gets all the calls that were made to CreatePR.
// Check the length with:
//
//	len(mockedProvider.CreatePRCalls())
func (mock *ProviderMock) CreatePRCalls() []struct {
	Ctx          context.Context
	Repo         string
	HeadBranch   string
	TargetBranch string
	Title        string
	Description  string
} {
	var calls []struct {
		Ctx          context.Context
		Repo         string
		HeadBranch   string
		TargetBranch string
		Title        string
		Description  string
	}
	mock.lockCreatePR.RLock()
	calls = mock.calls.CreatePR
	mock.lockCreatePR.RUnlock()
	return calls
}

// GetPRState calls GetPRStateFunc.
func (mock *ProviderMock) GetPRState(ctx context.Context, repo string, prNumber int) (string, error) {
	if mock.GetPRStateFunc == nil {
		panic("ProviderMock.GetPRStateFunc: method is nil but Provider.GetPRState was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Repo     string
		PrNumber int
	}{
		Ctx:      ctx,
		Repo:     repo,
		PrNumber: prNumber,
	}
	mock.lockGetPRState.Lock()
	mock.calls.GetPRState = append(mock.calls.GetPRState, callInfo)
	mock.lockGetPRState.Unlock()
	return mock.GetPRStateFunc(ctx, repo, prNumber)
}

// GetPRStateCalls gets all the calls that were made to GetPRState.
// Check the length with:
//
//	len(mockedProvider.GetPRStateCalls())
func (mock *ProviderMock) GetPRStateCalls() []struct {
	Ctx      context.Context
	Repo     string
	PrNumber int
} {
	var calls []struct {
		Ctx      context.Context
		Repo     string
		PrNumber int
	}
	mock.lockGetPRState.RLock()
	calls = mock.calls.GetPRState
	mock.lockGetPRState.RUnlock()
	return calls
}

// GitCredentials calls GitCredentialsFunc.
func (mock *ProviderMock) GitCredentials(ctx context.Context, token string) (string, string, error) {
	if mock.GitCredentialsFunc == nil {
		panic("ProviderMock.GitCredentialsFunc: method is nil but Provider.GitCredentials was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Token string
	}{
		Ctx:   ctx,
		Token: token,
	}
	mock.lockGitCredentials.Lock()
	mock.calls.GitCredentials = append(mock.calls.GitCredentials, callInfo)
	mock.lockGitCredentials.Unlock()
	return mock.GitCredentialsFunc(ctx, token)
}

// GitCredentialsCalls gets all the calls that were made to GitCredentials.
// Check the length with:
//
//	len(mockedProvider.GitCredentialsCalls())
func (mock *ProviderMock) GitCredentialsCalls() []struct {
	Ctx   context.Context
	Token string
} {
	var calls []struct {
		Ctx   context.Context
		Token string
	}
	mock.lockGitCredentials.RLock()
	calls = mock.calls.GitCredentials
	mock.lockGitCredentials.RUnlock()
	return calls
}

// ValidateToken calls ValidateTokenFunc.
func (mock *ProviderMock) ValidateToken(ctx context.Context, host string, token string) error {
	if mock.ValidateTokenFunc == nil {
		panic("ProviderMock.ValidateTokenFunc: method is nil but Provider.ValidateToken was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Host  string
		Token string
	}{
		Ctx:   ctx,
		Host:  host,
		Token: token,
	}
	mock.lockValidateToken.Lock()
	mock.calls.ValidateToken = append(mock.calls.ValidateToken, callInfo)
	mock.lockValidateToken.Unlock()
	return mock.ValidateTokenFunc(ctx, host, token)
}

// ValidateTokenCalls gets all the calls that were made to ValidateToken.
// Check the length with:
//
//	len(mockedProvider.ValidateTokenCalls())
func (mock *ProviderMock) ValidateTokenCalls() []struct {
	Ctx   context.Context
	Host  string
	Token string
} {
	var calls []struct {
		Ctx   context.Context
		Host  string
		Token string
	}
	mock.lockValidateToken.RLock()
	calls = mock.calls.ValidateToken
	mock.lockValidateToken.RUnlock()
	return calls
}
