// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package gittransport

import (
	"context"
	"github.com/bobcob7/loam/internal/credentialstore"
	"sync"
)

// Ensure, that credentialSourceMock does implement credentialSource.
// If this is not the case, regenerate this file with moq.
var _ credentialSource = &credentialSourceMock{}

// credentialSourceMock is a mock implementation of credentialSource.
//
//	func TestSomethingThatUsescredentialSource(t *testing.T) {
//
//		// make and configure a mocked credentialSource
//		mockedcredentialSource := &credentialSourceMock{
//			GetByHostFunc: func(ctx context.Context, host string) (credentialstore.Credential, error) {
//				panic("mock out the GetByHost method")
//			},
//		}
//
//		// use mockedcredentialSource in code that requires credentialSource
//		// and then make assertions.
//
//	}
type credentialSourceMock struct {
	// GetByHostFunc mocks the GetByHost method.
	GetByHostFunc func(ctx context.Context, host string) (credentialstore.Credential, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetByHost holds details about calls to the GetByHost method.
		GetByHost []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Host is the host argument value.
			Host string
		}
	}
	lockGetByHost sync.RWMutex
}

// GetByHost calls GetByHostFunc.
func (mock *credentialSourceMock) GetByHost(ctx context.Context, host string) (credentialstore.Credential, error) {
	if mock.GetByHostFunc == nil {
		panic("credentialSourceMock.GetByHostFunc: method is nil but credentialSource.GetByHost was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Host string
	}{
		Ctx:  ctx,
		Host: host,
	}
	mock.lockGetByHost.Lock()
	mock.calls.GetByHost = append(mock.calls.GetByHost, callInfo)
	mock.lockGetByHost.Unlock()
	return mock.GetByHostFunc(ctx, host)
}

// GetByHostCalls gets all the calls that were made to GetByHost.
// Check the length with:
//
//	len(mockedcredentialSource.GetByHostCalls())
func (mock *credentialSourceMock) GetByHostCalls() []struct {
	Ctx  context.Context
	Host string
} {
	var calls []struct {
		Ctx  context.Context
		Host string
	}
	mock.lockGetByHost.RLock()
	calls = mock.calls.GetByHost
	mock.lockGetByHost.RUnlock()
	return calls
}

// Ensure, that gitCredentialConverterMock does implement gitCredentialConverter.
// If this is not the case, regenerate this file with moq.
var _ gitCredentialConverter = &gitCredentialConverterMock{}

// gitCredentialConverterMock is a mock implementation of gitCredentialConverter.
//
//	func TestSomethingThatUsesgitCredentialConverter(t *testing.T) {
//
//		// make and configure a mocked gitCredentialConverter
//		mockedgitCredentialConverter := &gitCredentialConverterMock{
//			GitCredentialsFunc: func(ctx context.Context, token string) (string, string, error) {
//				panic("mock out the GitCredentials method")
//			},
//		}
//
//		// use mockedgitCredentialConverter in code that requires gitCredentialConverter
//		// and then make assertions.
//
//	}
type gitCredentialConverterMock struct {
	// GitCredentialsFunc mocks the GitCredentials method.
	GitCredentialsFunc func(ctx context.Context, token string) (string, string, error)

	// calls tracks calls to the methods.
	calls struct {
		// GitCredentials holds details about calls to the GitCredentials method.
		GitCredentials []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Token is the token argument value.
			Token string
		}
	}
	lockGitCredentials sync.RWMutex
}

// GitCredentials calls GitCredentialsFunc.
func (mock *gitCredentialConverterMock) GitCredentials(ctx context.Context, token string) (string, string, error) {
	if mock.GitCredentialsFunc == nil {
		panic("gitCredentialConverterMock.GitCredentialsFunc: method is nil but gitCredentialConverter.GitCredentials was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Token string
	}{
		Ctx:   ctx,
		Token: token,
	}
	mock.lockGitCredentials.Lock()
	mock.calls.GitCredentials = append(mock.calls.GitCredentials, callInfo)
	mock.lockGitCredentials.Unlock()
	return mock.GitCredentialsFunc(ctx, token)
}

// GitCredentialsCalls gets all the calls that were made to GitCredentials.
// Check the length with:
//
//	len(mockedgitCredentialConverter.GitCredentialsCalls())
func (mock *gitCredentialConverterMock) GitCredentialsCalls() []struct {
	Ctx   context.Context
	Token string
} {
	var calls []struct {
		Ctx   context.Context
		Token string
	}
	mock.lockGitCredentials.RLock()
	calls = mock.calls.GitCredentials
	mock.lockGitCredentials.RUnlock()
	return calls
}
