// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package search

import (
	"context"
	"github.com/bobcob7/loam/internal/chunkstore"
	"github.com/google/uuid"
	"sync"
)

// Ensure, that ChunkStoreMock does implement ChunkStore.
// If this is not the case, regenerate this file with moq.
var _ ChunkStore = &ChunkStoreMock{}

// ChunkStoreMock is a mock implementation of ChunkStore.
//
//	func TestSomethingThatUsesChunkStore(t *testing.T) {
//
//		// make and configure a mocked ChunkStore
//		mockedChunkStore := &ChunkStoreMock{
//			SearchFunc: func(ctx context.Context, repoIDs []uuid.UUID, targetBranch string, embedding []float32, limit int) ([]chunkstore.Chunk, error) {
//				panic("mock out the Search method")
//			},
//		}
//
//		// use mockedChunkStore in code that requires ChunkStore
//		// and then make assertions.
//
//	}
type ChunkStoreMock struct {
	// SearchFunc mocks the Search method.
	SearchFunc func(ctx context.Context, repoIDs []uuid.UUID, targetBranch string, embedding []float32, limit int) ([]chunkstore.Chunk, error)

	// calls tracks calls to the methods.
	calls struct {
		// Search holds details about calls to the Search method.
		Search []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RepoIDs is the repoIDs argument value.
			RepoIDs []uuid.UUID
			// TargetBranch is the targetBranch argument value.
			TargetBranch string
			// Embedding is the embedding argument value.
			Embedding []float32
			// Limit is the limit argument value.
			Limit int
		}
	}
	lockSearch sync.RWMutex
}

// Search calls SearchFunc.
func (mock *ChunkStoreMock) Search(ctx context.Context, repoIDs []uuid.UUID, targetBranch string, embedding []float32, limit int) ([]chunkstore.Chunk, error) {
	if mock.SearchFunc == nil {
		panic("ChunkStoreMock.SearchFunc: method is nil but ChunkStore.Search was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		RepoIDs      []uuid.UUID
		TargetBranch string
		Embedding    []float32
		Limit        int
	}{
		Ctx:          ctx,
		RepoIDs:      repoIDs,
		TargetBranch: targetBranch,
		Embedding:    embedding,
		Limit:        limit,
	}
	mock.lockSearch.Lock()
	mock.calls.Search = append(mock.calls.Search, callInfo)
	mock.lockSearch.Unlock()
	return mock.SearchFunc(ctx, repoIDs, targetBranch, embedding, limit)
}

// SearchCalls gets all the calls that were made to Search.
// Check the length with:
//
//	len(mockedChunkStore.SearchCalls())
func (mock *ChunkStoreMock) SearchCalls() []struct {
	Ctx          context.Context
	RepoIDs      []uuid.UUID
	TargetBranch string
	Embedding    []float32
	Limit        int
} {
	var calls []struct {
		Ctx          context.Context
		RepoIDs      []uuid.UUID
		TargetBranch string
		Embedding    []float32
		Limit        int
	}
	mock.lockSearch.RLock()
	calls = mock.calls.Search
	mock.lockSearch.RUnlock()
	return calls
}

// Ensure, that EmbedderMock does implement Embedder.
// If this is not the case, regenerate this file with moq.
var _ Embedder = &EmbedderMock{}

// EmbedderMock is a mock implementation of Embedder.
//
//	func TestSomethingThatUsesEmbedder(t *testing.T) {
//
//		// make and configure a mocked Embedder
//		mockedEmbedder := &EmbedderMock{
//			EmbedFunc: func(ctx context.Context, texts []string) ([][]float32, error) {
//				panic("mock out the Embed method")
//			},
//		}
//
//		// use mockedEmbedder in code that requires Embedder
//		// and then make assertions.
//
//	}
type EmbedderMock struct {
	// EmbedFunc mocks the Embed method.
	EmbedFunc func(ctx context.Context, texts []string) ([][]float32, error)

	// calls tracks calls to the methods.
	calls struct {
		// Embed holds details about calls to the Embed method.
		Embed []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Texts is the texts argument value.
			Texts []string
		}
	}
	lockEmbed sync.RWMutex
}

// Embed calls EmbedFunc.
func (mock *EmbedderMock) Embed(ctx context.Context, texts []string) ([][]float32, error) {
	if mock.EmbedFunc == nil {
		panic("EmbedderMock.EmbedFunc: method is nil but Embedder.Embed was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Texts []string
	}{
		Ctx:   ctx,
		Texts: texts,
	}
	mock.lockEmbed.Lock()
	mock.calls.Embed = append(mock.calls.Embed, callInfo)
	mock.lockEmbed.Unlock()
	return mock.EmbedFunc(ctx, texts)
}

// EmbedCalls gets all the calls that were made to Embed.
// Check the length with:
//
//	len(mockedEmbedder.EmbedCalls())
func (mock *EmbedderMock) EmbedCalls() []struct {
	Ctx   context.Context
	Texts []string
} {
	var calls []struct {
		Ctx   context.Context
		Texts []string
	}
	mock.lockEmbed.RLock()
	calls = mock.calls.Embed
	mock.lockEmbed.RUnlock()
	return calls
}
