// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package git

import (
	"context"
	"github.com/bobcob7/loam/internal/reposstore"
	"sync"
)

// Ensure, that RepoStoreMock does implement RepoStore.
// If this is not the case, regenerate this file with moq.
var _ RepoStore = &RepoStoreMock{}

// RepoStoreMock is a mock implementation of RepoStore.
//
//	func TestSomethingThatUsesRepoStore(t *testing.T) {
//
//		// make and configure a mocked RepoStore
//		mockedRepoStore := &RepoStoreMock{
//			GetRepoByNameFunc: func(ctx context.Context, name string) (reposstore.Repo, error) {
//				panic("mock out the GetRepoByName method")
//			},
//		}
//
//		// use mockedRepoStore in code that requires RepoStore
//		// and then make assertions.
//
//	}
type RepoStoreMock struct {
	// GetRepoByNameFunc mocks the GetRepoByName method.
	GetRepoByNameFunc func(ctx context.Context, name string) (reposstore.Repo, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetRepoByName holds details about calls to the GetRepoByName method.
		GetRepoByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
	}
	lockGetRepoByName sync.RWMutex
}

// GetRepoByName calls GetRepoByNameFunc.
func (mock *RepoStoreMock) GetRepoByName(ctx context.Context, name string) (reposstore.Repo, error) {
	if mock.GetRepoByNameFunc == nil {
		panic("RepoStoreMock.GetRepoByNameFunc: method is nil but RepoStore.GetRepoByName was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockGetRepoByName.Lock()
	mock.calls.GetRepoByName = append(mock.calls.GetRepoByName, callInfo)
	mock.lockGetRepoByName.Unlock()
	return mock.GetRepoByNameFunc(ctx, name)
}

// GetRepoByNameCalls gets all the calls that were made to GetRepoByName.
// Check the length with:
//
//	len(mockedRepoStore.GetRepoByNameCalls())
func (mock *RepoStoreMock) GetRepoByNameCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockGetRepoByName.RLock()
	calls = mock.calls.GetRepoByName
	mock.lockGetRepoByName.RUnlock()
	return calls
}
