// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package health

import (
	"context"
	"sync"
)

// Ensure, that PingerMock does implement Pinger.
// If this is not the case, regenerate this file with moq.
var _ Pinger = &PingerMock{}

// PingerMock is a mock implementation of Pinger.
//
//	func TestSomethingThatUsesPinger(t *testing.T) {
//
//		// make and configure a mocked Pinger
//		mockedPinger := &PingerMock{
//			PingFunc: func(ctx context.Context) error {
//				panic("mock out the Ping method")
//			},
//		}
//
//		// use mockedPinger in code that requires Pinger
//		// and then make assertions.
//
//	}
type PingerMock struct {
	// PingFunc mocks the Ping method.
	PingFunc func(ctx context.Context) error

	// calls tracks calls to the methods.
	calls struct {
		// Ping holds details about calls to the Ping method.
		Ping []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockPing sync.RWMutex
}

// Ping calls PingFunc.
func (mock *PingerMock) Ping(ctx context.Context) error {
	if mock.PingFunc == nil {
		panic("PingerMock.PingFunc: method is nil but Pinger.Ping was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockPing.Lock()
	mock.calls.Ping = append(mock.calls.Ping, callInfo)
	mock.lockPing.Unlock()
	return mock.PingFunc(ctx)
}

// PingCalls gets all the calls that were made to Ping.
// Check the length with:
//
//	len(mockedPinger.PingCalls())
func (mock *PingerMock) PingCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockPing.RLock()
	calls = mock.calls.Ping
	mock.lockPing.RUnlock()
	return calls
}

// Ensure, that SchemaCheckerMock does implement SchemaChecker.
// If this is not the case, regenerate this file with moq.
var _ SchemaChecker = &SchemaCheckerMock{}

// SchemaCheckerMock is a mock implementation of SchemaChecker.
//
//	func TestSomethingThatUsesSchemaChecker(t *testing.T) {
//
//		// make and configure a mocked SchemaChecker
//		mockedSchemaChecker := &SchemaCheckerMock{
//			CheckSchemaFunc: func(ctx context.Context) error {
//				panic("mock out the CheckSchema method")
//			},
//		}
//
//		// use mockedSchemaChecker in code that requires SchemaChecker
//		// and then make assertions.
//
//	}
type SchemaCheckerMock struct {
	// CheckSchemaFunc mocks the CheckSchema method.
	CheckSchemaFunc func(ctx context.Context) error

	// calls tracks calls to the methods.
	calls struct {
		// CheckSchema holds details about calls to the CheckSchema method.
		CheckSchema []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockCheckSchema sync.RWMutex
}

// CheckSchema calls CheckSchemaFunc.
func (mock *SchemaCheckerMock) CheckSchema(ctx context.Context) error {
	if mock.CheckSchemaFunc == nil {
		panic("SchemaCheckerMock.CheckSchemaFunc: method is nil but SchemaChecker.CheckSchema was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockCheckSchema.Lock()
	mock.calls.CheckSchema = append(mock.calls.CheckSchema, callInfo)
	mock.lockCheckSchema.Unlock()
	return mock.CheckSchemaFunc(ctx)
}

// CheckSchemaCalls gets all the calls that were made to CheckSchema.
// Check the length with:
//
//	len(mockedSchemaChecker.CheckSchemaCalls())
func (mock *SchemaCheckerMock) CheckSchemaCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockCheckSchema.RLock()
	calls = mock.calls.CheckSchema
	mock.lockCheckSchema.RUnlock()
	return calls
}
