// Package workbranch implements loam.v1.WorkBranchService: the lifecycle
// half (loam-ofg.8) -- CreateWorkBranch, UpdateWorkBranch, RequestReview,
// ListWorkBranches, GetWorkBranch, GetWorkBranchDiff -- and the review half
// (loam-ofg.9) -- ListComments, ListVerdicts, SubmitVerdict, ReplyToThread
// -- on one Handler struct sharing one set of store seams, rather than two
// packages duplicating them.
package workbranch

import (
	"context"

	"github.com/google/uuid"

	"github.com/bobcob7/loam/internal/reposstore"
	"github.com/bobcob7/loam/internal/reviewpublish"
	"github.com/bobcob7/loam/internal/reviewstore"
	"github.com/bobcob7/loam/internal/workbranchstore"
)

//go:generate go tool moq -out moq_test.go . WorkBranchStore RepoStore RoundStore DiffComputer WorkBranchRefWriter ThreadStore VerdictStore VerdictPublisher

// WorkBranchStore is the internal/workbranchstore.Store surface this
// package's lifecycle RPCs need, defined here at the consumer per repo
// convention. *workbranchstore.Store satisfies it directly in production;
// tests drive a moq mock instead.
type WorkBranchStore interface {
	// Create inserts a new draft work branch. name is generated by the
	// caller (randomWorkBranchName in this package), never by the store.
	Create(ctx context.Context, repoID uuid.UUID, name, target, author string) (workbranchstore.WorkBranch, error)
	// GetByName resolves the (repoID, name) identity every RPC but List and
	// Create is keyed on.
	GetByName(ctx context.Context, repoID uuid.UUID, name string) (workbranchstore.WorkBranch, error)
	// List returns filter's matching work branches, offset-paginated, plus
	// the total count matching the same filter for PageInfo.total.
	List(ctx context.Context, filter workbranchstore.ListFilter, limit, offset int32) ([]workbranchstore.WorkBranch, int64, error)
	// SetTitleDescription is UpdateWorkBranch's full-replace write; the
	// handler reads the current row first (GetByName) so an unset request
	// field passes the current value straight through, per
	// SetTitleDescription's own "full replace, not a partial patch"
	// contract.
	SetTitleDescription(ctx context.Context, id uuid.UUID, title, description string) (workbranchstore.WorkBranch, error)
	// UpdateState is RequestReview's draft/reviewed -> reviewable
	// transition; the store's own guarded UPDATE enforces both the
	// legal-from-state check and the title/description precondition
	// atomically, surfacing either as workbranchstore.ErrIllegalTransition.
	UpdateState(ctx context.Context, id uuid.UUID, to workbranchstore.State) (workbranchstore.WorkBranch, error)
}

// RepoStore is the internal/reposstore.Store surface this package needs to
// resolve a repo name to the id downstream queries key on (and back, for
// ListWorkBranches' cross-repo results), and to validate CreateWorkBranch's
// target branch, defined here at the consumer. *reposstore.Store satisfies
// it directly in production.
type RepoStore interface {
	GetRepoByName(ctx context.Context, name string) (reposstore.Repo, error)
	GetRepoByID(ctx context.Context, id uuid.UUID) (reposstore.Repo, error)
	ListTargetBranches(ctx context.Context, repoID uuid.UUID) ([]reposstore.TargetBranch, error)
}

// RoundStore is the internal/reviewstore.RoundStore surface RequestReview
// needs: OpenRound so "every transition into reviewable opens a numbered
// review round" (docs/cli-spec.md -> "Work Branches") actually happens --
// without it, loam-ofg.9's SubmitVerdict would have no round to attach a
// verdict to, and a re-review's prior verdicts -- compared by round number,
// never a stored flag (docs/web-spec.md -> ProposalService: "`stale` is
// derived") -- would never go stale; and CurrentRound so RequestReview can
// self-heal (see below). Defined here at the consumer; *reviewstore.RoundStore
// satisfies it directly in production.
//
// RequestReview calls WorkBranchStore.UpdateState then RoundStore.OpenRound
// as two separate, non-atomic store writes, not one pgx.Tx -- true
// cross-store atomicity (the pattern every *StoreInTx constructor and
// internal/storetx's integration test exist to demonstrate) would require
// this handler to also hold a transaction-opening seam, filed as a
// follow-up rather than built here. That gap is NOT merely a rare race: a
// connect-go request context is cancelled on ordinary client disconnect or
// deadline (ctrl-C, a CLI timeout) between the two round-trips -- no crash
// needed -- and UpdateState has already autocommitted by the time OpenRound
// would run, so this is routinely reachable. Left unhandled, the resulting
// state is not just inconsistent but VISIBLE and UNRECOVERABLE: the branch
// is reviewable with no round, so it satisfies every reviewer's
// awaiting-review filter (workbranchstore's NOT EXISTS-on-current-round
// predicate is vacuously true with zero rounds) while rejecting every
// verdict (loam-ofg.9's SubmitVerdict resolves a round via CurrentRound,
// which returns reviewstore.ErrNoCurrentRound) -- and UpdateWorkBranchState
// has no reviewable->reviewable transition, so a bare retry answers
// ErrIllegalTransition (misreported to the caller as "missing title or
// description," the opposite of the truth) forever, with no agent-facing
// recovery path at all.
//
// RequestReview therefore self-heals: when UpdateState fails with
// workbranchstore.ErrIllegalTransition and the work branch was ALREADY
// reviewable before the call (read via resolveWorkBranch, before
// UpdateState ever ran), that is exactly the interrupted-retry shape above,
// distinguished from a genuine reviewable->reviewable rejection by asking
// CurrentRound: no round at all means the previous attempt's OpenRound
// never landed, so this call opens one now and reports success; an
// existing round means the branch is legitimately, unambiguously already
// under review, and the illegal-transition error stands.
type RoundStore interface {
	OpenRound(ctx context.Context, workBranchID uuid.UUID, requestedBy string) (reviewstore.Round, error)
	CurrentRound(ctx context.Context, workBranchID uuid.UUID) (reviewstore.Round, error)
}

// DiffComputer computes a work branch's unified diff against its target
// branch (docs/cli-spec.md -> "diff": "the unified diff of the work branch
// against its target branch"): the three-dot `git diff <target>...<name>`
// range, i.e. the diff from target and name's merge base -- what the work
// branch itself changed, not everything target has done since. Defined
// here at the consumer, per repo convention. Implemented by
// internal/gitdiff.Computer (loam-fwk), which shells out to real git
// against the repo's bare mirror on disk; wired in
// cmd/server/main.go's registerWorkBranchService. Before loam-fwk, no
// package in this repo computed a diff at all (confirmed by grep: no
// exec.Command("git", "diff", ...) or equivalent existed anywhere in
// internal/, despite docs/git-spec.md -> "Enforcement Mechanics" asserting
// in passing that "the server already shells out to git for sync, diffs,
// and ingest" -- that line did not match this tree's actual history and
// should not be read as evidence the plumbing predates loam-fwk). This is
// a distinct piece of git plumbing from loam-ofg.16 (the git smart-HTTP
// transport handler -- upload-pack/receive-pack framing only, per its own
// DESCRIPTION; it never covered diff computation).
type DiffComputer interface {
	Diff(ctx context.Context, workBranch workbranchstore.WorkBranch) (string, error)
}

// WorkBranchRefWriter creates the server-side git ref a work branch OWES
// its existence to. docs/git-spec.md -> Ref Policy: work-branch refs are
// "created server-side by `work start` only, never by push", and the
// pre-receive hook enforces the other half by rejecting a push that tries
// to create one. Defined here at the consumer; implemented by
// internal/gitref.Creator, wired in cmd/server/main.go.
//
// Before loam-5iu this seam did not exist and neither did the ref:
// CreateWorkBranch inserted the work_branches row and stopped, so
// GetWorkBranchDiff answered gitdiff.ErrRefMissing -> FailedPrecondition
// for essentially every work branch (the error path was the common case,
// not an edge case) and `loam clone` of a freshly started branch had no
// ref to fetch.
//
// Delete exists for exactly one caller -- CreateWorkBranch's compensating
// rollback -- and its contract is that an already-absent ref is not an
// error. See CreateWorkBranch for why the ref is written BEFORE the row.
type WorkBranchRefWriter interface {
	// CreateWorkBranchRef creates the work branch's ref in repoName's bare
	// mirror at whatever the target branch `from` currently resolves to.
	// It must refuse to move an existing ref rather than overwrite one.
	CreateWorkBranchRef(ctx context.Context, repoName, name, from string) error
	// DeleteWorkBranchRef removes the work branch's ref. Absent is not an
	// error.
	DeleteWorkBranchRef(ctx context.Context, repoName, name string) error
}

// ThreadStore is the internal/reviewstore.ThreadStore surface the review
// RPCs need, defined here at the consumer per repo convention.
// *reviewstore.ThreadStore satisfies it directly in production; tests drive
// a moq mock instead.
//
// Only the two READ-and-immediate-write operations live here. The batch
// publish SubmitVerdict performs does NOT: it must be one transaction
// spanning threads, verdicts, and work_branches, so it is a single seam of
// its own (VerdictPublisher) rather than several calls this handler would
// have to sequence outside any transaction.
type ThreadStore interface {
	// List returns the work branch's PUBLISHED threads with their
	// comments, offset-paginated by thread, plus the total thread count
	// for PageInfo.total. Staged comments are never here -- they live in
	// the CLI's .loam until a verdict publishes them.
	List(ctx context.Context, workBranchID uuid.UUID, limit, offset int32) ([]reviewstore.ThreadWithComments, int64, error)
	// Get resolves a thread id scoped to workBranchID, so ReplyToThread
	// can reject a thread belonging to another work branch as
	// reviewstore.ErrThreadNotFound before writing anything.
	Get(ctx context.Context, workBranchID, id uuid.UUID) (reviewstore.Thread, error)
	// Reply appends a comment to an existing thread immediately -- never
	// staged (docs/cli-spec.md -> "reply"). roundID/roundNumber is the
	// branch's CURRENT round at the moment of the reply, which may be a
	// later round than the thread's own.
	Reply(ctx context.Context, threadID, roundID uuid.UUID, roundNumber int32, author, body string) (reviewstore.Comment, error)
}

// VerdictStore is the internal/reviewstore.VerdictStore surface
// ListVerdicts needs, defined here at the consumer.
// *reviewstore.VerdictStore satisfies it directly in production.
type VerdictStore interface {
	// List returns every verdict across every round for the work branch,
	// newest round first, each decorated with whether its round is the
	// branch's CURRENT one. Staleness is that flag's negation and is
	// derived from round numbers by the query itself -- there is no stored
	// stale column anywhere in this system, and this handler must not
	// invent a second mechanism for it.
	List(ctx context.Context, workBranchID uuid.UUID) ([]reviewstore.VerdictRecord, error)
}

// VerdictPublisher is the atomic verdict publish SubmitVerdict performs,
// defined here at the consumer. *reviewpublish.Publisher satisfies it in
// production, opening one pgx.Tx per call so the published comments, the
// thread resolutions, the verdict, and the reviewable -> reviewed flip
// commit together or not at all.
//
// It is deliberately ONE method rather than a set of finer-grained store
// calls this handler would orchestrate: the atomicity is the contract
// (docs/cli-spec.md -> "verdict": "in one atomic action"), and a handler
// sequencing three store calls could not provide it no matter how careful
// the ordering. The work-branch state gate lives inside the transaction
// too, so it cannot be raced by a concurrent transition.
type VerdictPublisher interface {
	Publish(ctx context.Context, req reviewpublish.Request) (reviewpublish.Result, error)
}
