// Package workbranch implements the lifecycle half of loam.v1.WorkBranchService
// (loam-ofg.8): CreateWorkBranch, UpdateWorkBranch, RequestReview,
// ListWorkBranches, GetWorkBranch, and GetWorkBranchDiff. The other half --
// ListComments, ListVerdicts, SubmitVerdict, ReplyToThread -- belongs to
// loam-ofg.9, which shares this package's Handler struct and store seams
// rather than duplicating them.
package workbranch

import (
	"context"

	"github.com/google/uuid"

	"github.com/bobcob7/loam/internal/reposstore"
	"github.com/bobcob7/loam/internal/reviewstore"
	"github.com/bobcob7/loam/internal/workbranchstore"
)

//go:generate go tool moq -out moq_test.go . WorkBranchStore RepoStore RoundOpener DiffComputer

// WorkBranchStore is the internal/workbranchstore.Store surface this
// package's lifecycle RPCs need, defined here at the consumer per repo
// convention. *workbranchstore.Store satisfies it directly in production;
// tests drive a moq mock instead.
type WorkBranchStore interface {
	// Create inserts a new draft work branch. name is generated by the
	// caller (randomWorkBranchName in this package), never by the store.
	Create(ctx context.Context, repoID uuid.UUID, name, target, author string) (workbranchstore.WorkBranch, error)
	// GetByName resolves the (repoID, name) identity every RPC but List and
	// Create is keyed on.
	GetByName(ctx context.Context, repoID uuid.UUID, name string) (workbranchstore.WorkBranch, error)
	// List returns filter's matching work branches, offset-paginated, plus
	// the total count matching the same filter for PageInfo.total.
	List(ctx context.Context, filter workbranchstore.ListFilter, limit, offset int32) ([]workbranchstore.WorkBranch, int64, error)
	// SetTitleDescription is UpdateWorkBranch's full-replace write; the
	// handler reads the current row first (GetByName) so an unset request
	// field passes the current value straight through, per
	// SetTitleDescription's own "full replace, not a partial patch"
	// contract.
	SetTitleDescription(ctx context.Context, id uuid.UUID, title, description string) (workbranchstore.WorkBranch, error)
	// UpdateState is RequestReview's draft/reviewed -> reviewable
	// transition; the store's own guarded UPDATE enforces both the
	// legal-from-state check and the title/description precondition
	// atomically, surfacing either as workbranchstore.ErrIllegalTransition.
	UpdateState(ctx context.Context, id uuid.UUID, to workbranchstore.State) (workbranchstore.WorkBranch, error)
}

// RepoStore is the internal/reposstore.Store surface this package needs to
// resolve a repo name to the id downstream queries key on (and back, for
// ListWorkBranches' cross-repo results), and to validate CreateWorkBranch's
// target branch, defined here at the consumer. *reposstore.Store satisfies
// it directly in production.
type RepoStore interface {
	GetRepoByName(ctx context.Context, name string) (reposstore.Repo, error)
	GetRepoByID(ctx context.Context, id uuid.UUID) (reposstore.Repo, error)
	ListTargetBranches(ctx context.Context, repoID uuid.UUID) ([]reposstore.TargetBranch, error)
}

// RoundOpener opens a new review round -- the internal/reviewstore.RoundStore
// surface RequestReview needs so "every transition into reviewable opens a
// numbered review round" (docs/cli-spec.md -> "Work Branches") actually
// happens: without it, loam-ofg.9's SubmitVerdict would have no round to
// attach a verdict to, and a re-review's prior verdicts -- compared by round
// number, never a stored flag (docs/web-spec.md -> ProposalService:
// "`stale` is derived") -- would never go stale. Defined here at the
// consumer; *reviewstore.RoundStore satisfies it directly in production.
//
// RequestReview calls WorkBranchStore.UpdateState then RoundOpener.OpenRound
// as two separate, non-atomic store writes: this package's declared seams
// are each ordinary pool-backed interfaces, not a shared pgx.Tx, and wiring
// true cross-store atomicity (the pattern every *StoreInTx constructor and
// internal/storetx's integration test exist to demonstrate) would require
// this handler to also hold a transaction-opening seam -- out of this
// bead's declared scope ("Consume a work-branch store seam, a role store
// seam, and a git/diff seam"). A crash between the two writes would leave a
// reviewable branch with no current round; rare, since both calls land
// back-to-back against the same pool with nothing that can block between
// them, but real. Flagged here rather than silently assumed away; a
// follow-up bead can promote this to one transaction if it matters in
// practice.
type RoundOpener interface {
	OpenRound(ctx context.Context, workBranchID uuid.UUID, requestedBy string) (reviewstore.Round, error)
}

// DiffComputer computes a work branch's unified diff against its target
// branch (docs/cli-spec.md -> "diff": "the unified diff of the work branch
// against its target branch"). Defined here at the consumer -- but nothing
// in this tree implements it yet. Locating a repo's bare-mirror path on
// disk and shelling out to `git diff <target>...<name>` against it belongs
// to the git-transport plumbing loam-ofg.16 has not landed; no other
// package in this repo computes a diff either (confirmed by grep: no
// exec.Command("git", "diff", ...) or equivalent exists anywhere in
// internal/ as of this bead, despite docs/git-spec.md -> "Enforcement
// Mechanics" asserting in passing that "the server already shells out to
// git for sync, diffs, and ingest" -- that line does not match this tree's
// actual state and should not be read as evidence the plumbing exists).
// cmd/server/main.go wires a not-implemented stand-in
// (notImplementedDiffComputer) so GetWorkBranchDiff is genuinely
// reachable and fails loudly, not silently, until the real plumbing
// exists -- the same choice notImplementedOrchestrator already makes there
// for the ingest pipeline.
type DiffComputer interface {
	Diff(ctx context.Context, workBranch workbranchstore.WorkBranch) (string, error)
}
