// Package workbranch implements the lifecycle half of loam.v1.WorkBranchService
// (loam-ofg.8): CreateWorkBranch, UpdateWorkBranch, RequestReview,
// ListWorkBranches, GetWorkBranch, and GetWorkBranchDiff. The other half --
// ListComments, ListVerdicts, SubmitVerdict, ReplyToThread -- belongs to
// loam-ofg.9, which shares this package's Handler struct and store seams
// rather than duplicating them.
package workbranch

import (
	"context"

	"github.com/google/uuid"

	"github.com/bobcob7/loam/internal/reposstore"
	"github.com/bobcob7/loam/internal/reviewstore"
	"github.com/bobcob7/loam/internal/workbranchstore"
)

//go:generate go tool moq -out moq_test.go . WorkBranchStore RepoStore RoundStore DiffComputer

// WorkBranchStore is the internal/workbranchstore.Store surface this
// package's lifecycle RPCs need, defined here at the consumer per repo
// convention. *workbranchstore.Store satisfies it directly in production;
// tests drive a moq mock instead.
type WorkBranchStore interface {
	// Create inserts a new draft work branch. name is generated by the
	// caller (randomWorkBranchName in this package), never by the store.
	Create(ctx context.Context, repoID uuid.UUID, name, target, author string) (workbranchstore.WorkBranch, error)
	// GetByName resolves the (repoID, name) identity every RPC but List and
	// Create is keyed on.
	GetByName(ctx context.Context, repoID uuid.UUID, name string) (workbranchstore.WorkBranch, error)
	// List returns filter's matching work branches, offset-paginated, plus
	// the total count matching the same filter for PageInfo.total.
	List(ctx context.Context, filter workbranchstore.ListFilter, limit, offset int32) ([]workbranchstore.WorkBranch, int64, error)
	// SetTitleDescription is UpdateWorkBranch's full-replace write; the
	// handler reads the current row first (GetByName) so an unset request
	// field passes the current value straight through, per
	// SetTitleDescription's own "full replace, not a partial patch"
	// contract.
	SetTitleDescription(ctx context.Context, id uuid.UUID, title, description string) (workbranchstore.WorkBranch, error)
	// UpdateState is RequestReview's draft/reviewed -> reviewable
	// transition; the store's own guarded UPDATE enforces both the
	// legal-from-state check and the title/description precondition
	// atomically, surfacing either as workbranchstore.ErrIllegalTransition.
	UpdateState(ctx context.Context, id uuid.UUID, to workbranchstore.State) (workbranchstore.WorkBranch, error)
}

// RepoStore is the internal/reposstore.Store surface this package needs to
// resolve a repo name to the id downstream queries key on (and back, for
// ListWorkBranches' cross-repo results), and to validate CreateWorkBranch's
// target branch, defined here at the consumer. *reposstore.Store satisfies
// it directly in production.
type RepoStore interface {
	GetRepoByName(ctx context.Context, name string) (reposstore.Repo, error)
	GetRepoByID(ctx context.Context, id uuid.UUID) (reposstore.Repo, error)
	ListTargetBranches(ctx context.Context, repoID uuid.UUID) ([]reposstore.TargetBranch, error)
}

// RoundStore is the internal/reviewstore.RoundStore surface RequestReview
// needs: OpenRound so "every transition into reviewable opens a numbered
// review round" (docs/cli-spec.md -> "Work Branches") actually happens --
// without it, loam-ofg.9's SubmitVerdict would have no round to attach a
// verdict to, and a re-review's prior verdicts -- compared by round number,
// never a stored flag (docs/web-spec.md -> ProposalService: "`stale` is
// derived") -- would never go stale; and CurrentRound so RequestReview can
// self-heal (see below). Defined here at the consumer; *reviewstore.RoundStore
// satisfies it directly in production.
//
// RequestReview calls WorkBranchStore.UpdateState then RoundStore.OpenRound
// as two separate, non-atomic store writes, not one pgx.Tx -- true
// cross-store atomicity (the pattern every *StoreInTx constructor and
// internal/storetx's integration test exist to demonstrate) would require
// this handler to also hold a transaction-opening seam, filed as a
// follow-up rather than built here. That gap is NOT merely a rare race: a
// connect-go request context is cancelled on ordinary client disconnect or
// deadline (ctrl-C, a CLI timeout) between the two round-trips -- no crash
// needed -- and UpdateState has already autocommitted by the time OpenRound
// would run, so this is routinely reachable. Left unhandled, the resulting
// state is not just inconsistent but VISIBLE and UNRECOVERABLE: the branch
// is reviewable with no round, so it satisfies every reviewer's
// awaiting-review filter (workbranchstore's NOT EXISTS-on-current-round
// predicate is vacuously true with zero rounds) while rejecting every
// verdict (loam-ofg.9's SubmitVerdict resolves a round via CurrentRound,
// which returns reviewstore.ErrNoCurrentRound) -- and UpdateWorkBranchState
// has no reviewable->reviewable transition, so a bare retry answers
// ErrIllegalTransition (misreported to the caller as "missing title or
// description," the opposite of the truth) forever, with no agent-facing
// recovery path at all.
//
// RequestReview therefore self-heals: when UpdateState fails with
// workbranchstore.ErrIllegalTransition and the work branch was ALREADY
// reviewable before the call (read via resolveWorkBranch, before
// UpdateState ever ran), that is exactly the interrupted-retry shape above,
// distinguished from a genuine reviewable->reviewable rejection by asking
// CurrentRound: no round at all means the previous attempt's OpenRound
// never landed, so this call opens one now and reports success; an
// existing round means the branch is legitimately, unambiguously already
// under review, and the illegal-transition error stands.
type RoundStore interface {
	OpenRound(ctx context.Context, workBranchID uuid.UUID, requestedBy string) (reviewstore.Round, error)
	CurrentRound(ctx context.Context, workBranchID uuid.UUID) (reviewstore.Round, error)
}

// DiffComputer computes a work branch's unified diff against its target
// branch (docs/cli-spec.md -> "diff": "the unified diff of the work branch
// against its target branch"): the three-dot `git diff <target>...<name>`
// range, i.e. the diff from target and name's merge base -- what the work
// branch itself changed, not everything target has done since. Defined
// here at the consumer, per repo convention. Implemented by
// internal/gitdiff.Computer (loam-fwk), which shells out to real git
// against the repo's bare mirror on disk; wired in
// cmd/server/main.go's registerWorkBranchService. Before loam-fwk, no
// package in this repo computed a diff at all (confirmed by grep: no
// exec.Command("git", "diff", ...) or equivalent existed anywhere in
// internal/, despite docs/git-spec.md -> "Enforcement Mechanics" asserting
// in passing that "the server already shells out to git for sync, diffs,
// and ingest" -- that line did not match this tree's actual history and
// should not be read as evidence the plumbing predates loam-fwk). This is
// a distinct piece of git plumbing from loam-ofg.16 (the git smart-HTTP
// transport handler -- upload-pack/receive-pack framing only, per its own
// DESCRIPTION; it never covered diff computation).
type DiffComputer interface {
	Diff(ctx context.Context, workBranch workbranchstore.WorkBranch) (string, error)
}
