// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package workbranch

import (
	"context"
	"github.com/bobcob7/loam/internal/reposstore"
	"github.com/bobcob7/loam/internal/reviewstore"
	"github.com/bobcob7/loam/internal/workbranchstore"
	"github.com/google/uuid"
	"sync"
)

// Ensure, that WorkBranchStoreMock does implement WorkBranchStore.
// If this is not the case, regenerate this file with moq.
var _ WorkBranchStore = &WorkBranchStoreMock{}

// WorkBranchStoreMock is a mock implementation of WorkBranchStore.
//
//	func TestSomethingThatUsesWorkBranchStore(t *testing.T) {
//
//		// make and configure a mocked WorkBranchStore
//		mockedWorkBranchStore := &WorkBranchStoreMock{
//			CreateFunc: func(ctx context.Context, repoID uuid.UUID, name string, target string, author string) (workbranchstore.WorkBranch, error) {
//				panic("mock out the Create method")
//			},
//			GetByNameFunc: func(ctx context.Context, repoID uuid.UUID, name string) (workbranchstore.WorkBranch, error) {
//				panic("mock out the GetByName method")
//			},
//			ListFunc: func(ctx context.Context, filter workbranchstore.ListFilter, limit int32, offset int32) ([]workbranchstore.WorkBranch, int64, error) {
//				panic("mock out the List method")
//			},
//			SetTitleDescriptionFunc: func(ctx context.Context, id uuid.UUID, title string, description string) (workbranchstore.WorkBranch, error) {
//				panic("mock out the SetTitleDescription method")
//			},
//			UpdateStateFunc: func(ctx context.Context, id uuid.UUID, to workbranchstore.State) (workbranchstore.WorkBranch, error) {
//				panic("mock out the UpdateState method")
//			},
//		}
//
//		// use mockedWorkBranchStore in code that requires WorkBranchStore
//		// and then make assertions.
//
//	}
type WorkBranchStoreMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, repoID uuid.UUID, name string, target string, author string) (workbranchstore.WorkBranch, error)

	// GetByNameFunc mocks the GetByName method.
	GetByNameFunc func(ctx context.Context, repoID uuid.UUID, name string) (workbranchstore.WorkBranch, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, filter workbranchstore.ListFilter, limit int32, offset int32) ([]workbranchstore.WorkBranch, int64, error)

	// SetTitleDescriptionFunc mocks the SetTitleDescription method.
	SetTitleDescriptionFunc func(ctx context.Context, id uuid.UUID, title string, description string) (workbranchstore.WorkBranch, error)

	// UpdateStateFunc mocks the UpdateState method.
	UpdateStateFunc func(ctx context.Context, id uuid.UUID, to workbranchstore.State) (workbranchstore.WorkBranch, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RepoID is the repoID argument value.
			RepoID uuid.UUID
			// Name is the name argument value.
			Name string
			// Target is the target argument value.
			Target string
			// Author is the author argument value.
			Author string
		}
		// GetByName holds details about calls to the GetByName method.
		GetByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RepoID is the repoID argument value.
			RepoID uuid.UUID
			// Name is the name argument value.
			Name string
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Filter is the filter argument value.
			Filter workbranchstore.ListFilter
			// Limit is the limit argument value.
			Limit int32
			// Offset is the offset argument value.
			Offset int32
		}
		// SetTitleDescription holds details about calls to the SetTitleDescription method.
		SetTitleDescription []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
			// Title is the title argument value.
			Title string
			// Description is the description argument value.
			Description string
		}
		// UpdateState holds details about calls to the UpdateState method.
		UpdateState []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
			// To is the to argument value.
			To workbranchstore.State
		}
	}
	lockCreate              sync.RWMutex
	lockGetByName           sync.RWMutex
	lockList                sync.RWMutex
	lockSetTitleDescription sync.RWMutex
	lockUpdateState         sync.RWMutex
}

// Create calls CreateFunc.
func (mock *WorkBranchStoreMock) Create(ctx context.Context, repoID uuid.UUID, name string, target string, author string) (workbranchstore.WorkBranch, error) {
	if mock.CreateFunc == nil {
		panic("WorkBranchStoreMock.CreateFunc: method is nil but WorkBranchStore.Create was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		RepoID uuid.UUID
		Name   string
		Target string
		Author string
	}{
		Ctx:    ctx,
		RepoID: repoID,
		Name:   name,
		Target: target,
		Author: author,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, repoID, name, target, author)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedWorkBranchStore.CreateCalls())
func (mock *WorkBranchStoreMock) CreateCalls() []struct {
	Ctx    context.Context
	RepoID uuid.UUID
	Name   string
	Target string
	Author string
} {
	var calls []struct {
		Ctx    context.Context
		RepoID uuid.UUID
		Name   string
		Target string
		Author string
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// GetByName calls GetByNameFunc.
func (mock *WorkBranchStoreMock) GetByName(ctx context.Context, repoID uuid.UUID, name string) (workbranchstore.WorkBranch, error) {
	if mock.GetByNameFunc == nil {
		panic("WorkBranchStoreMock.GetByNameFunc: method is nil but WorkBranchStore.GetByName was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		RepoID uuid.UUID
		Name   string
	}{
		Ctx:    ctx,
		RepoID: repoID,
		Name:   name,
	}
	mock.lockGetByName.Lock()
	mock.calls.GetByName = append(mock.calls.GetByName, callInfo)
	mock.lockGetByName.Unlock()
	return mock.GetByNameFunc(ctx, repoID, name)
}

// GetByNameCalls gets all the calls that were made to GetByName.
// Check the length with:
//
//	len(mockedWorkBranchStore.GetByNameCalls())
func (mock *WorkBranchStoreMock) GetByNameCalls() []struct {
	Ctx    context.Context
	RepoID uuid.UUID
	Name   string
} {
	var calls []struct {
		Ctx    context.Context
		RepoID uuid.UUID
		Name   string
	}
	mock.lockGetByName.RLock()
	calls = mock.calls.GetByName
	mock.lockGetByName.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *WorkBranchStoreMock) List(ctx context.Context, filter workbranchstore.ListFilter, limit int32, offset int32) ([]workbranchstore.WorkBranch, int64, error) {
	if mock.ListFunc == nil {
		panic("WorkBranchStoreMock.ListFunc: method is nil but WorkBranchStore.List was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Filter workbranchstore.ListFilter
		Limit  int32
		Offset int32
	}{
		Ctx:    ctx,
		Filter: filter,
		Limit:  limit,
		Offset: offset,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, filter, limit, offset)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedWorkBranchStore.ListCalls())
func (mock *WorkBranchStoreMock) ListCalls() []struct {
	Ctx    context.Context
	Filter workbranchstore.ListFilter
	Limit  int32
	Offset int32
} {
	var calls []struct {
		Ctx    context.Context
		Filter workbranchstore.ListFilter
		Limit  int32
		Offset int32
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// SetTitleDescription calls SetTitleDescriptionFunc.
func (mock *WorkBranchStoreMock) SetTitleDescription(ctx context.Context, id uuid.UUID, title string, description string) (workbranchstore.WorkBranch, error) {
	if mock.SetTitleDescriptionFunc == nil {
		panic("WorkBranchStoreMock.SetTitleDescriptionFunc: method is nil but WorkBranchStore.SetTitleDescription was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		ID          uuid.UUID
		Title       string
		Description string
	}{
		Ctx:         ctx,
		ID:          id,
		Title:       title,
		Description: description,
	}
	mock.lockSetTitleDescription.Lock()
	mock.calls.SetTitleDescription = append(mock.calls.SetTitleDescription, callInfo)
	mock.lockSetTitleDescription.Unlock()
	return mock.SetTitleDescriptionFunc(ctx, id, title, description)
}

// SetTitleDescriptionCalls gets all the calls that were made to SetTitleDescription.
// Check the length with:
//
//	len(mockedWorkBranchStore.SetTitleDescriptionCalls())
func (mock *WorkBranchStoreMock) SetTitleDescriptionCalls() []struct {
	Ctx         context.Context
	ID          uuid.UUID
	Title       string
	Description string
} {
	var calls []struct {
		Ctx         context.Context
		ID          uuid.UUID
		Title       string
		Description string
	}
	mock.lockSetTitleDescription.RLock()
	calls = mock.calls.SetTitleDescription
	mock.lockSetTitleDescription.RUnlock()
	return calls
}

// UpdateState calls UpdateStateFunc.
func (mock *WorkBranchStoreMock) UpdateState(ctx context.Context, id uuid.UUID, to workbranchstore.State) (workbranchstore.WorkBranch, error) {
	if mock.UpdateStateFunc == nil {
		panic("WorkBranchStoreMock.UpdateStateFunc: method is nil but WorkBranchStore.UpdateState was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
		To  workbranchstore.State
	}{
		Ctx: ctx,
		ID:  id,
		To:  to,
	}
	mock.lockUpdateState.Lock()
	mock.calls.UpdateState = append(mock.calls.UpdateState, callInfo)
	mock.lockUpdateState.Unlock()
	return mock.UpdateStateFunc(ctx, id, to)
}

// UpdateStateCalls gets all the calls that were made to UpdateState.
// Check the length with:
//
//	len(mockedWorkBranchStore.UpdateStateCalls())
func (mock *WorkBranchStoreMock) UpdateStateCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
	To  workbranchstore.State
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
		To  workbranchstore.State
	}
	mock.lockUpdateState.RLock()
	calls = mock.calls.UpdateState
	mock.lockUpdateState.RUnlock()
	return calls
}

// Ensure, that RepoStoreMock does implement RepoStore.
// If this is not the case, regenerate this file with moq.
var _ RepoStore = &RepoStoreMock{}

// RepoStoreMock is a mock implementation of RepoStore.
//
//	func TestSomethingThatUsesRepoStore(t *testing.T) {
//
//		// make and configure a mocked RepoStore
//		mockedRepoStore := &RepoStoreMock{
//			GetRepoByIDFunc: func(ctx context.Context, id uuid.UUID) (reposstore.Repo, error) {
//				panic("mock out the GetRepoByID method")
//			},
//			GetRepoByNameFunc: func(ctx context.Context, name string) (reposstore.Repo, error) {
//				panic("mock out the GetRepoByName method")
//			},
//			ListTargetBranchesFunc: func(ctx context.Context, repoID uuid.UUID) ([]reposstore.TargetBranch, error) {
//				panic("mock out the ListTargetBranches method")
//			},
//		}
//
//		// use mockedRepoStore in code that requires RepoStore
//		// and then make assertions.
//
//	}
type RepoStoreMock struct {
	// GetRepoByIDFunc mocks the GetRepoByID method.
	GetRepoByIDFunc func(ctx context.Context, id uuid.UUID) (reposstore.Repo, error)

	// GetRepoByNameFunc mocks the GetRepoByName method.
	GetRepoByNameFunc func(ctx context.Context, name string) (reposstore.Repo, error)

	// ListTargetBranchesFunc mocks the ListTargetBranches method.
	ListTargetBranchesFunc func(ctx context.Context, repoID uuid.UUID) ([]reposstore.TargetBranch, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetRepoByID holds details about calls to the GetRepoByID method.
		GetRepoByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// GetRepoByName holds details about calls to the GetRepoByName method.
		GetRepoByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
		// ListTargetBranches holds details about calls to the ListTargetBranches method.
		ListTargetBranches []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RepoID is the repoID argument value.
			RepoID uuid.UUID
		}
	}
	lockGetRepoByID        sync.RWMutex
	lockGetRepoByName      sync.RWMutex
	lockListTargetBranches sync.RWMutex
}

// GetRepoByID calls GetRepoByIDFunc.
func (mock *RepoStoreMock) GetRepoByID(ctx context.Context, id uuid.UUID) (reposstore.Repo, error) {
	if mock.GetRepoByIDFunc == nil {
		panic("RepoStoreMock.GetRepoByIDFunc: method is nil but RepoStore.GetRepoByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetRepoByID.Lock()
	mock.calls.GetRepoByID = append(mock.calls.GetRepoByID, callInfo)
	mock.lockGetRepoByID.Unlock()
	return mock.GetRepoByIDFunc(ctx, id)
}

// GetRepoByIDCalls gets all the calls that were made to GetRepoByID.
// Check the length with:
//
//	len(mockedRepoStore.GetRepoByIDCalls())
func (mock *RepoStoreMock) GetRepoByIDCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockGetRepoByID.RLock()
	calls = mock.calls.GetRepoByID
	mock.lockGetRepoByID.RUnlock()
	return calls
}

// GetRepoByName calls GetRepoByNameFunc.
func (mock *RepoStoreMock) GetRepoByName(ctx context.Context, name string) (reposstore.Repo, error) {
	if mock.GetRepoByNameFunc == nil {
		panic("RepoStoreMock.GetRepoByNameFunc: method is nil but RepoStore.GetRepoByName was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockGetRepoByName.Lock()
	mock.calls.GetRepoByName = append(mock.calls.GetRepoByName, callInfo)
	mock.lockGetRepoByName.Unlock()
	return mock.GetRepoByNameFunc(ctx, name)
}

// GetRepoByNameCalls gets all the calls that were made to GetRepoByName.
// Check the length with:
//
//	len(mockedRepoStore.GetRepoByNameCalls())
func (mock *RepoStoreMock) GetRepoByNameCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockGetRepoByName.RLock()
	calls = mock.calls.GetRepoByName
	mock.lockGetRepoByName.RUnlock()
	return calls
}

// ListTargetBranches calls ListTargetBranchesFunc.
func (mock *RepoStoreMock) ListTargetBranches(ctx context.Context, repoID uuid.UUID) ([]reposstore.TargetBranch, error) {
	if mock.ListTargetBranchesFunc == nil {
		panic("RepoStoreMock.ListTargetBranchesFunc: method is nil but RepoStore.ListTargetBranches was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		RepoID uuid.UUID
	}{
		Ctx:    ctx,
		RepoID: repoID,
	}
	mock.lockListTargetBranches.Lock()
	mock.calls.ListTargetBranches = append(mock.calls.ListTargetBranches, callInfo)
	mock.lockListTargetBranches.Unlock()
	return mock.ListTargetBranchesFunc(ctx, repoID)
}

// ListTargetBranchesCalls gets all the calls that were made to ListTargetBranches.
// Check the length with:
//
//	len(mockedRepoStore.ListTargetBranchesCalls())
func (mock *RepoStoreMock) ListTargetBranchesCalls() []struct {
	Ctx    context.Context
	RepoID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		RepoID uuid.UUID
	}
	mock.lockListTargetBranches.RLock()
	calls = mock.calls.ListTargetBranches
	mock.lockListTargetBranches.RUnlock()
	return calls
}

// Ensure, that RoundStoreMock does implement RoundStore.
// If this is not the case, regenerate this file with moq.
var _ RoundStore = &RoundStoreMock{}

// RoundStoreMock is a mock implementation of RoundStore.
//
//	func TestSomethingThatUsesRoundStore(t *testing.T) {
//
//		// make and configure a mocked RoundStore
//		mockedRoundStore := &RoundStoreMock{
//			CurrentRoundFunc: func(ctx context.Context, workBranchID uuid.UUID) (reviewstore.Round, error) {
//				panic("mock out the CurrentRound method")
//			},
//			OpenRoundFunc: func(ctx context.Context, workBranchID uuid.UUID, requestedBy string) (reviewstore.Round, error) {
//				panic("mock out the OpenRound method")
//			},
//		}
//
//		// use mockedRoundStore in code that requires RoundStore
//		// and then make assertions.
//
//	}
type RoundStoreMock struct {
	// CurrentRoundFunc mocks the CurrentRound method.
	CurrentRoundFunc func(ctx context.Context, workBranchID uuid.UUID) (reviewstore.Round, error)

	// OpenRoundFunc mocks the OpenRound method.
	OpenRoundFunc func(ctx context.Context, workBranchID uuid.UUID, requestedBy string) (reviewstore.Round, error)

	// calls tracks calls to the methods.
	calls struct {
		// CurrentRound holds details about calls to the CurrentRound method.
		CurrentRound []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// WorkBranchID is the workBranchID argument value.
			WorkBranchID uuid.UUID
		}
		// OpenRound holds details about calls to the OpenRound method.
		OpenRound []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// WorkBranchID is the workBranchID argument value.
			WorkBranchID uuid.UUID
			// RequestedBy is the requestedBy argument value.
			RequestedBy string
		}
	}
	lockCurrentRound sync.RWMutex
	lockOpenRound    sync.RWMutex
}

// CurrentRound calls CurrentRoundFunc.
func (mock *RoundStoreMock) CurrentRound(ctx context.Context, workBranchID uuid.UUID) (reviewstore.Round, error) {
	if mock.CurrentRoundFunc == nil {
		panic("RoundStoreMock.CurrentRoundFunc: method is nil but RoundStore.CurrentRound was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		WorkBranchID uuid.UUID
	}{
		Ctx:          ctx,
		WorkBranchID: workBranchID,
	}
	mock.lockCurrentRound.Lock()
	mock.calls.CurrentRound = append(mock.calls.CurrentRound, callInfo)
	mock.lockCurrentRound.Unlock()
	return mock.CurrentRoundFunc(ctx, workBranchID)
}

// CurrentRoundCalls gets all the calls that were made to CurrentRound.
// Check the length with:
//
//	len(mockedRoundStore.CurrentRoundCalls())
func (mock *RoundStoreMock) CurrentRoundCalls() []struct {
	Ctx          context.Context
	WorkBranchID uuid.UUID
} {
	var calls []struct {
		Ctx          context.Context
		WorkBranchID uuid.UUID
	}
	mock.lockCurrentRound.RLock()
	calls = mock.calls.CurrentRound
	mock.lockCurrentRound.RUnlock()
	return calls
}

// OpenRound calls OpenRoundFunc.
func (mock *RoundStoreMock) OpenRound(ctx context.Context, workBranchID uuid.UUID, requestedBy string) (reviewstore.Round, error) {
	if mock.OpenRoundFunc == nil {
		panic("RoundStoreMock.OpenRoundFunc: method is nil but RoundStore.OpenRound was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		WorkBranchID uuid.UUID
		RequestedBy  string
	}{
		Ctx:          ctx,
		WorkBranchID: workBranchID,
		RequestedBy:  requestedBy,
	}
	mock.lockOpenRound.Lock()
	mock.calls.OpenRound = append(mock.calls.OpenRound, callInfo)
	mock.lockOpenRound.Unlock()
	return mock.OpenRoundFunc(ctx, workBranchID, requestedBy)
}

// OpenRoundCalls gets all the calls that were made to OpenRound.
// Check the length with:
//
//	len(mockedRoundStore.OpenRoundCalls())
func (mock *RoundStoreMock) OpenRoundCalls() []struct {
	Ctx          context.Context
	WorkBranchID uuid.UUID
	RequestedBy  string
} {
	var calls []struct {
		Ctx          context.Context
		WorkBranchID uuid.UUID
		RequestedBy  string
	}
	mock.lockOpenRound.RLock()
	calls = mock.calls.OpenRound
	mock.lockOpenRound.RUnlock()
	return calls
}

// Ensure, that DiffComputerMock does implement DiffComputer.
// If this is not the case, regenerate this file with moq.
var _ DiffComputer = &DiffComputerMock{}

// DiffComputerMock is a mock implementation of DiffComputer.
//
//	func TestSomethingThatUsesDiffComputer(t *testing.T) {
//
//		// make and configure a mocked DiffComputer
//		mockedDiffComputer := &DiffComputerMock{
//			DiffFunc: func(ctx context.Context, workBranch workbranchstore.WorkBranch) (string, error) {
//				panic("mock out the Diff method")
//			},
//		}
//
//		// use mockedDiffComputer in code that requires DiffComputer
//		// and then make assertions.
//
//	}
type DiffComputerMock struct {
	// DiffFunc mocks the Diff method.
	DiffFunc func(ctx context.Context, workBranch workbranchstore.WorkBranch) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// Diff holds details about calls to the Diff method.
		Diff []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// WorkBranch is the workBranch argument value.
			WorkBranch workbranchstore.WorkBranch
		}
	}
	lockDiff sync.RWMutex
}

// Diff calls DiffFunc.
func (mock *DiffComputerMock) Diff(ctx context.Context, workBranch workbranchstore.WorkBranch) (string, error) {
	if mock.DiffFunc == nil {
		panic("DiffComputerMock.DiffFunc: method is nil but DiffComputer.Diff was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		WorkBranch workbranchstore.WorkBranch
	}{
		Ctx:        ctx,
		WorkBranch: workBranch,
	}
	mock.lockDiff.Lock()
	mock.calls.Diff = append(mock.calls.Diff, callInfo)
	mock.lockDiff.Unlock()
	return mock.DiffFunc(ctx, workBranch)
}

// DiffCalls gets all the calls that were made to Diff.
// Check the length with:
//
//	len(mockedDiffComputer.DiffCalls())
func (mock *DiffComputerMock) DiffCalls() []struct {
	Ctx        context.Context
	WorkBranch workbranchstore.WorkBranch
} {
	var calls []struct {
		Ctx        context.Context
		WorkBranch workbranchstore.WorkBranch
	}
	mock.lockDiff.RLock()
	calls = mock.calls.Diff
	mock.lockDiff.RUnlock()
	return calls
}
