// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package role

import (
	"context"
	"github.com/bobcob7/loam/internal/rolestore"
	"sync"
)

// Ensure, that roleStoreMock does implement roleStore.
// If this is not the case, regenerate this file with moq.
var _ roleStore = &roleStoreMock{}

// roleStoreMock is a mock implementation of roleStore.
//
//	func TestSomethingThatUsesroleStore(t *testing.T) {
//
//		// make and configure a mocked roleStore
//		mockedroleStore := &roleStoreMock{
//			CreateRoleFunc: func(ctx context.Context, params rolestore.RoleParams) (rolestore.Role, error) {
//				panic("mock out the CreateRole method")
//			},
//			DeleteRoleFunc: func(ctx context.Context, name string) error {
//				panic("mock out the DeleteRole method")
//			},
//			GetRoleFunc: func(ctx context.Context, name string) (rolestore.Role, error) {
//				panic("mock out the GetRole method")
//			},
//			ListRolesFunc: func(ctx context.Context) ([]rolestore.Role, error) {
//				panic("mock out the ListRoles method")
//			},
//			UpdateRoleFunc: func(ctx context.Context, params rolestore.RoleParams) (rolestore.Role, error) {
//				panic("mock out the UpdateRole method")
//			},
//		}
//
//		// use mockedroleStore in code that requires roleStore
//		// and then make assertions.
//
//	}
type roleStoreMock struct {
	// CreateRoleFunc mocks the CreateRole method.
	CreateRoleFunc func(ctx context.Context, params rolestore.RoleParams) (rolestore.Role, error)

	// DeleteRoleFunc mocks the DeleteRole method.
	DeleteRoleFunc func(ctx context.Context, name string) error

	// GetRoleFunc mocks the GetRole method.
	GetRoleFunc func(ctx context.Context, name string) (rolestore.Role, error)

	// ListRolesFunc mocks the ListRoles method.
	ListRolesFunc func(ctx context.Context) ([]rolestore.Role, error)

	// UpdateRoleFunc mocks the UpdateRole method.
	UpdateRoleFunc func(ctx context.Context, params rolestore.RoleParams) (rolestore.Role, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateRole holds details about calls to the CreateRole method.
		CreateRole []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params rolestore.RoleParams
		}
		// DeleteRole holds details about calls to the DeleteRole method.
		DeleteRole []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
		// GetRole holds details about calls to the GetRole method.
		GetRole []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
		// ListRoles holds details about calls to the ListRoles method.
		ListRoles []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// UpdateRole holds details about calls to the UpdateRole method.
		UpdateRole []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params rolestore.RoleParams
		}
	}
	lockCreateRole sync.RWMutex
	lockDeleteRole sync.RWMutex
	lockGetRole    sync.RWMutex
	lockListRoles  sync.RWMutex
	lockUpdateRole sync.RWMutex
}

// CreateRole calls CreateRoleFunc.
func (mock *roleStoreMock) CreateRole(ctx context.Context, params rolestore.RoleParams) (rolestore.Role, error) {
	if mock.CreateRoleFunc == nil {
		panic("roleStoreMock.CreateRoleFunc: method is nil but roleStore.CreateRole was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params rolestore.RoleParams
	}{
		Ctx:    ctx,
		Params: params,
	}
	mock.lockCreateRole.Lock()
	mock.calls.CreateRole = append(mock.calls.CreateRole, callInfo)
	mock.lockCreateRole.Unlock()
	return mock.CreateRoleFunc(ctx, params)
}

// CreateRoleCalls gets all the calls that were made to CreateRole.
// Check the length with:
//
//	len(mockedroleStore.CreateRoleCalls())
func (mock *roleStoreMock) CreateRoleCalls() []struct {
	Ctx    context.Context
	Params rolestore.RoleParams
} {
	var calls []struct {
		Ctx    context.Context
		Params rolestore.RoleParams
	}
	mock.lockCreateRole.RLock()
	calls = mock.calls.CreateRole
	mock.lockCreateRole.RUnlock()
	return calls
}

// DeleteRole calls DeleteRoleFunc.
func (mock *roleStoreMock) DeleteRole(ctx context.Context, name string) error {
	if mock.DeleteRoleFunc == nil {
		panic("roleStoreMock.DeleteRoleFunc: method is nil but roleStore.DeleteRole was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockDeleteRole.Lock()
	mock.calls.DeleteRole = append(mock.calls.DeleteRole, callInfo)
	mock.lockDeleteRole.Unlock()
	return mock.DeleteRoleFunc(ctx, name)
}

// DeleteRoleCalls gets all the calls that were made to DeleteRole.
// Check the length with:
//
//	len(mockedroleStore.DeleteRoleCalls())
func (mock *roleStoreMock) DeleteRoleCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockDeleteRole.RLock()
	calls = mock.calls.DeleteRole
	mock.lockDeleteRole.RUnlock()
	return calls
}

// GetRole calls GetRoleFunc.
func (mock *roleStoreMock) GetRole(ctx context.Context, name string) (rolestore.Role, error) {
	if mock.GetRoleFunc == nil {
		panic("roleStoreMock.GetRoleFunc: method is nil but roleStore.GetRole was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockGetRole.Lock()
	mock.calls.GetRole = append(mock.calls.GetRole, callInfo)
	mock.lockGetRole.Unlock()
	return mock.GetRoleFunc(ctx, name)
}

// GetRoleCalls gets all the calls that were made to GetRole.
// Check the length with:
//
//	len(mockedroleStore.GetRoleCalls())
func (mock *roleStoreMock) GetRoleCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockGetRole.RLock()
	calls = mock.calls.GetRole
	mock.lockGetRole.RUnlock()
	return calls
}

// ListRoles calls ListRolesFunc.
func (mock *roleStoreMock) ListRoles(ctx context.Context) ([]rolestore.Role, error) {
	if mock.ListRolesFunc == nil {
		panic("roleStoreMock.ListRolesFunc: method is nil but roleStore.ListRoles was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListRoles.Lock()
	mock.calls.ListRoles = append(mock.calls.ListRoles, callInfo)
	mock.lockListRoles.Unlock()
	return mock.ListRolesFunc(ctx)
}

// ListRolesCalls gets all the calls that were made to ListRoles.
// Check the length with:
//
//	len(mockedroleStore.ListRolesCalls())
func (mock *roleStoreMock) ListRolesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListRoles.RLock()
	calls = mock.calls.ListRoles
	mock.lockListRoles.RUnlock()
	return calls
}

// UpdateRole calls UpdateRoleFunc.
func (mock *roleStoreMock) UpdateRole(ctx context.Context, params rolestore.RoleParams) (rolestore.Role, error) {
	if mock.UpdateRoleFunc == nil {
		panic("roleStoreMock.UpdateRoleFunc: method is nil but roleStore.UpdateRole was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params rolestore.RoleParams
	}{
		Ctx:    ctx,
		Params: params,
	}
	mock.lockUpdateRole.Lock()
	mock.calls.UpdateRole = append(mock.calls.UpdateRole, callInfo)
	mock.lockUpdateRole.Unlock()
	return mock.UpdateRoleFunc(ctx, params)
}

// UpdateRoleCalls gets all the calls that were made to UpdateRole.
// Check the length with:
//
//	len(mockedroleStore.UpdateRoleCalls())
func (mock *roleStoreMock) UpdateRoleCalls() []struct {
	Ctx    context.Context
	Params rolestore.RoleParams
} {
	var calls []struct {
		Ctx    context.Context
		Params rolestore.RoleParams
	}
	mock.lockUpdateRole.RLock()
	calls = mock.calls.UpdateRole
	mock.lockUpdateRole.RUnlock()
	return calls
}
