// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package cli

import (
	"sync"
)

// Ensure, that ConfigMock does implement Config.
// If this is not the case, regenerate this file with moq.
var _ Config = &ConfigMock{}

// ConfigMock is a mock implementation of Config.
//
//	func TestSomethingThatUsesConfig(t *testing.T) {
//
//		// make and configure a mocked Config
//		mockedConfig := &ConfigMock{
//			AgentIDFunc: func() string {
//				panic("mock out the AgentID method")
//			},
//			AgentNameFunc: func() string {
//				panic("mock out the AgentName method")
//			},
//			AgentRoleFunc: func() string {
//				panic("mock out the AgentRole method")
//			},
//			OutputFormatFunc: func() string {
//				panic("mock out the OutputFormat method")
//			},
//			ServerURLFunc: func() string {
//				panic("mock out the ServerURL method")
//			},
//		}
//
//		// use mockedConfig in code that requires Config
//		// and then make assertions.
//
//	}
type ConfigMock struct {
	// AgentIDFunc mocks the AgentID method.
	AgentIDFunc func() string

	// AgentNameFunc mocks the AgentName method.
	AgentNameFunc func() string

	// AgentRoleFunc mocks the AgentRole method.
	AgentRoleFunc func() string

	// OutputFormatFunc mocks the OutputFormat method.
	OutputFormatFunc func() string

	// ServerURLFunc mocks the ServerURL method.
	ServerURLFunc func() string

	// calls tracks calls to the methods.
	calls struct {
		// AgentID holds details about calls to the AgentID method.
		AgentID []struct {
		}
		// AgentName holds details about calls to the AgentName method.
		AgentName []struct {
		}
		// AgentRole holds details about calls to the AgentRole method.
		AgentRole []struct {
		}
		// OutputFormat holds details about calls to the OutputFormat method.
		OutputFormat []struct {
		}
		// ServerURL holds details about calls to the ServerURL method.
		ServerURL []struct {
		}
	}
	lockAgentID      sync.RWMutex
	lockAgentName    sync.RWMutex
	lockAgentRole    sync.RWMutex
	lockOutputFormat sync.RWMutex
	lockServerURL    sync.RWMutex
}

// AgentID calls AgentIDFunc.
func (mock *ConfigMock) AgentID() string {
	if mock.AgentIDFunc == nil {
		panic("ConfigMock.AgentIDFunc: method is nil but Config.AgentID was just called")
	}
	callInfo := struct {
	}{}
	mock.lockAgentID.Lock()
	mock.calls.AgentID = append(mock.calls.AgentID, callInfo)
	mock.lockAgentID.Unlock()
	return mock.AgentIDFunc()
}

// AgentIDCalls gets all the calls that were made to AgentID.
// Check the length with:
//
//	len(mockedConfig.AgentIDCalls())
func (mock *ConfigMock) AgentIDCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockAgentID.RLock()
	calls = mock.calls.AgentID
	mock.lockAgentID.RUnlock()
	return calls
}

// AgentName calls AgentNameFunc.
func (mock *ConfigMock) AgentName() string {
	if mock.AgentNameFunc == nil {
		panic("ConfigMock.AgentNameFunc: method is nil but Config.AgentName was just called")
	}
	callInfo := struct {
	}{}
	mock.lockAgentName.Lock()
	mock.calls.AgentName = append(mock.calls.AgentName, callInfo)
	mock.lockAgentName.Unlock()
	return mock.AgentNameFunc()
}

// AgentNameCalls gets all the calls that were made to AgentName.
// Check the length with:
//
//	len(mockedConfig.AgentNameCalls())
func (mock *ConfigMock) AgentNameCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockAgentName.RLock()
	calls = mock.calls.AgentName
	mock.lockAgentName.RUnlock()
	return calls
}

// AgentRole calls AgentRoleFunc.
func (mock *ConfigMock) AgentRole() string {
	if mock.AgentRoleFunc == nil {
		panic("ConfigMock.AgentRoleFunc: method is nil but Config.AgentRole was just called")
	}
	callInfo := struct {
	}{}
	mock.lockAgentRole.Lock()
	mock.calls.AgentRole = append(mock.calls.AgentRole, callInfo)
	mock.lockAgentRole.Unlock()
	return mock.AgentRoleFunc()
}

// AgentRoleCalls gets all the calls that were made to AgentRole.
// Check the length with:
//
//	len(mockedConfig.AgentRoleCalls())
func (mock *ConfigMock) AgentRoleCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockAgentRole.RLock()
	calls = mock.calls.AgentRole
	mock.lockAgentRole.RUnlock()
	return calls
}

// OutputFormat calls OutputFormatFunc.
func (mock *ConfigMock) OutputFormat() string {
	if mock.OutputFormatFunc == nil {
		panic("ConfigMock.OutputFormatFunc: method is nil but Config.OutputFormat was just called")
	}
	callInfo := struct {
	}{}
	mock.lockOutputFormat.Lock()
	mock.calls.OutputFormat = append(mock.calls.OutputFormat, callInfo)
	mock.lockOutputFormat.Unlock()
	return mock.OutputFormatFunc()
}

// OutputFormatCalls gets all the calls that were made to OutputFormat.
// Check the length with:
//
//	len(mockedConfig.OutputFormatCalls())
func (mock *ConfigMock) OutputFormatCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockOutputFormat.RLock()
	calls = mock.calls.OutputFormat
	mock.lockOutputFormat.RUnlock()
	return calls
}

// ServerURL calls ServerURLFunc.
func (mock *ConfigMock) ServerURL() string {
	if mock.ServerURLFunc == nil {
		panic("ConfigMock.ServerURLFunc: method is nil but Config.ServerURL was just called")
	}
	callInfo := struct {
	}{}
	mock.lockServerURL.Lock()
	mock.calls.ServerURL = append(mock.calls.ServerURL, callInfo)
	mock.lockServerURL.Unlock()
	return mock.ServerURLFunc()
}

// ServerURLCalls gets all the calls that were made to ServerURL.
// Check the length with:
//
//	len(mockedConfig.ServerURLCalls())
func (mock *ConfigMock) ServerURLCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockServerURL.RLock()
	calls = mock.calls.ServerURL
	mock.lockServerURL.RUnlock()
	return calls
}

// Ensure, that OutputEncoderMock does implement OutputEncoder.
// If this is not the case, regenerate this file with moq.
var _ OutputEncoder = &OutputEncoderMock{}

// OutputEncoderMock is a mock implementation of OutputEncoder.
//
//	func TestSomethingThatUsesOutputEncoder(t *testing.T) {
//
//		// make and configure a mocked OutputEncoder
//		mockedOutputEncoder := &OutputEncoderMock{
//			EncodeFunc: func(v any) error {
//				panic("mock out the Encode method")
//			},
//		}
//
//		// use mockedOutputEncoder in code that requires OutputEncoder
//		// and then make assertions.
//
//	}
type OutputEncoderMock struct {
	// EncodeFunc mocks the Encode method.
	EncodeFunc func(v any) error

	// calls tracks calls to the methods.
	calls struct {
		// Encode holds details about calls to the Encode method.
		Encode []struct {
			// V is the v argument value.
			V any
		}
	}
	lockEncode sync.RWMutex
}

// Encode calls EncodeFunc.
func (mock *OutputEncoderMock) Encode(v any) error {
	if mock.EncodeFunc == nil {
		panic("OutputEncoderMock.EncodeFunc: method is nil but OutputEncoder.Encode was just called")
	}
	callInfo := struct {
		V any
	}{
		V: v,
	}
	mock.lockEncode.Lock()
	mock.calls.Encode = append(mock.calls.Encode, callInfo)
	mock.lockEncode.Unlock()
	return mock.EncodeFunc(v)
}

// EncodeCalls gets all the calls that were made to Encode.
// Check the length with:
//
//	len(mockedOutputEncoder.EncodeCalls())
func (mock *OutputEncoderMock) EncodeCalls() []struct {
	V any
} {
	var calls []struct {
		V any
	}
	mock.lockEncode.RLock()
	calls = mock.calls.Encode
	mock.lockEncode.RUnlock()
	return calls
}

// Ensure, that ErrorMapperMock does implement ErrorMapper.
// If this is not the case, regenerate this file with moq.
var _ ErrorMapper = &ErrorMapperMock{}

// ErrorMapperMock is a mock implementation of ErrorMapper.
//
//	func TestSomethingThatUsesErrorMapper(t *testing.T) {
//
//		// make and configure a mocked ErrorMapper
//		mockedErrorMapper := &ErrorMapperMock{
//			ExitCodeFunc: func(err error) int {
//				panic("mock out the ExitCode method")
//			},
//		}
//
//		// use mockedErrorMapper in code that requires ErrorMapper
//		// and then make assertions.
//
//	}
type ErrorMapperMock struct {
	// ExitCodeFunc mocks the ExitCode method.
	ExitCodeFunc func(err error) int

	// calls tracks calls to the methods.
	calls struct {
		// ExitCode holds details about calls to the ExitCode method.
		ExitCode []struct {
			// Err is the err argument value.
			Err error
		}
	}
	lockExitCode sync.RWMutex
}

// ExitCode calls ExitCodeFunc.
func (mock *ErrorMapperMock) ExitCode(err error) int {
	if mock.ExitCodeFunc == nil {
		panic("ErrorMapperMock.ExitCodeFunc: method is nil but ErrorMapper.ExitCode was just called")
	}
	callInfo := struct {
		Err error
	}{
		Err: err,
	}
	mock.lockExitCode.Lock()
	mock.calls.ExitCode = append(mock.calls.ExitCode, callInfo)
	mock.lockExitCode.Unlock()
	return mock.ExitCodeFunc(err)
}

// ExitCodeCalls gets all the calls that were made to ExitCode.
// Check the length with:
//
//	len(mockedErrorMapper.ExitCodeCalls())
func (mock *ErrorMapperMock) ExitCodeCalls() []struct {
	Err error
} {
	var calls []struct {
		Err error
	}
	mock.lockExitCode.RLock()
	calls = mock.calls.ExitCode
	mock.lockExitCode.RUnlock()
	return calls
}

// Ensure, that WorkspaceResolverMock does implement WorkspaceResolver.
// If this is not the case, regenerate this file with moq.
var _ WorkspaceResolver = &WorkspaceResolverMock{}

// WorkspaceResolverMock is a mock implementation of WorkspaceResolver.
//
//	func TestSomethingThatUsesWorkspaceResolver(t *testing.T) {
//
//		// make and configure a mocked WorkspaceResolver
//		mockedWorkspaceResolver := &WorkspaceResolverMock{
//			ResolveRepoFunc: func() (string, error) {
//				panic("mock out the ResolveRepo method")
//			},
//			ResolveWorkBranchFunc: func() (string, error) {
//				panic("mock out the ResolveWorkBranch method")
//			},
//		}
//
//		// use mockedWorkspaceResolver in code that requires WorkspaceResolver
//		// and then make assertions.
//
//	}
type WorkspaceResolverMock struct {
	// ResolveRepoFunc mocks the ResolveRepo method.
	ResolveRepoFunc func() (string, error)

	// ResolveWorkBranchFunc mocks the ResolveWorkBranch method.
	ResolveWorkBranchFunc func() (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// ResolveRepo holds details about calls to the ResolveRepo method.
		ResolveRepo []struct {
		}
		// ResolveWorkBranch holds details about calls to the ResolveWorkBranch method.
		ResolveWorkBranch []struct {
		}
	}
	lockResolveRepo       sync.RWMutex
	lockResolveWorkBranch sync.RWMutex
}

// ResolveRepo calls ResolveRepoFunc.
func (mock *WorkspaceResolverMock) ResolveRepo() (string, error) {
	if mock.ResolveRepoFunc == nil {
		panic("WorkspaceResolverMock.ResolveRepoFunc: method is nil but WorkspaceResolver.ResolveRepo was just called")
	}
	callInfo := struct {
	}{}
	mock.lockResolveRepo.Lock()
	mock.calls.ResolveRepo = append(mock.calls.ResolveRepo, callInfo)
	mock.lockResolveRepo.Unlock()
	return mock.ResolveRepoFunc()
}

// ResolveRepoCalls gets all the calls that were made to ResolveRepo.
// Check the length with:
//
//	len(mockedWorkspaceResolver.ResolveRepoCalls())
func (mock *WorkspaceResolverMock) ResolveRepoCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockResolveRepo.RLock()
	calls = mock.calls.ResolveRepo
	mock.lockResolveRepo.RUnlock()
	return calls
}

// ResolveWorkBranch calls ResolveWorkBranchFunc.
func (mock *WorkspaceResolverMock) ResolveWorkBranch() (string, error) {
	if mock.ResolveWorkBranchFunc == nil {
		panic("WorkspaceResolverMock.ResolveWorkBranchFunc: method is nil but WorkspaceResolver.ResolveWorkBranch was just called")
	}
	callInfo := struct {
	}{}
	mock.lockResolveWorkBranch.Lock()
	mock.calls.ResolveWorkBranch = append(mock.calls.ResolveWorkBranch, callInfo)
	mock.lockResolveWorkBranch.Unlock()
	return mock.ResolveWorkBranchFunc()
}

// ResolveWorkBranchCalls gets all the calls that were made to ResolveWorkBranch.
// Check the length with:
//
//	len(mockedWorkspaceResolver.ResolveWorkBranchCalls())
func (mock *WorkspaceResolverMock) ResolveWorkBranchCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockResolveWorkBranch.RLock()
	calls = mock.calls.ResolveWorkBranch
	mock.lockResolveWorkBranch.RUnlock()
	return calls
}
