// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package embed

import (
	"context"
	"sync"
)

// Ensure, that EmbedderMock does implement Embedder.
// If this is not the case, regenerate this file with moq.
var _ Embedder = &EmbedderMock{}

// EmbedderMock is a mock implementation of Embedder.
//
//	func TestSomethingThatUsesEmbedder(t *testing.T) {
//
//		// make and configure a mocked Embedder
//		mockedEmbedder := &EmbedderMock{
//			ContextWindowFunc: func() int {
//				panic("mock out the ContextWindow method")
//			},
//			DimensionFunc: func() int {
//				panic("mock out the Dimension method")
//			},
//			EmbedFunc: func(ctx context.Context, texts []string) ([][]float32, error) {
//				panic("mock out the Embed method")
//			},
//			ModelIDFunc: func() string {
//				panic("mock out the ModelID method")
//			},
//		}
//
//		// use mockedEmbedder in code that requires Embedder
//		// and then make assertions.
//
//	}
type EmbedderMock struct {
	// ContextWindowFunc mocks the ContextWindow method.
	ContextWindowFunc func() int

	// DimensionFunc mocks the Dimension method.
	DimensionFunc func() int

	// EmbedFunc mocks the Embed method.
	EmbedFunc func(ctx context.Context, texts []string) ([][]float32, error)

	// ModelIDFunc mocks the ModelID method.
	ModelIDFunc func() string

	// calls tracks calls to the methods.
	calls struct {
		// ContextWindow holds details about calls to the ContextWindow method.
		ContextWindow []struct {
		}
		// Dimension holds details about calls to the Dimension method.
		Dimension []struct {
		}
		// Embed holds details about calls to the Embed method.
		Embed []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Texts is the texts argument value.
			Texts []string
		}
		// ModelID holds details about calls to the ModelID method.
		ModelID []struct {
		}
	}
	lockContextWindow sync.RWMutex
	lockDimension     sync.RWMutex
	lockEmbed         sync.RWMutex
	lockModelID       sync.RWMutex
}

// ContextWindow calls ContextWindowFunc.
func (mock *EmbedderMock) ContextWindow() int {
	if mock.ContextWindowFunc == nil {
		panic("EmbedderMock.ContextWindowFunc: method is nil but Embedder.ContextWindow was just called")
	}
	callInfo := struct {
	}{}
	mock.lockContextWindow.Lock()
	mock.calls.ContextWindow = append(mock.calls.ContextWindow, callInfo)
	mock.lockContextWindow.Unlock()
	return mock.ContextWindowFunc()
}

// ContextWindowCalls gets all the calls that were made to ContextWindow.
// Check the length with:
//
//	len(mockedEmbedder.ContextWindowCalls())
func (mock *EmbedderMock) ContextWindowCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockContextWindow.RLock()
	calls = mock.calls.ContextWindow
	mock.lockContextWindow.RUnlock()
	return calls
}

// Dimension calls DimensionFunc.
func (mock *EmbedderMock) Dimension() int {
	if mock.DimensionFunc == nil {
		panic("EmbedderMock.DimensionFunc: method is nil but Embedder.Dimension was just called")
	}
	callInfo := struct {
	}{}
	mock.lockDimension.Lock()
	mock.calls.Dimension = append(mock.calls.Dimension, callInfo)
	mock.lockDimension.Unlock()
	return mock.DimensionFunc()
}

// DimensionCalls gets all the calls that were made to Dimension.
// Check the length with:
//
//	len(mockedEmbedder.DimensionCalls())
func (mock *EmbedderMock) DimensionCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockDimension.RLock()
	calls = mock.calls.Dimension
	mock.lockDimension.RUnlock()
	return calls
}

// Embed calls EmbedFunc.
func (mock *EmbedderMock) Embed(ctx context.Context, texts []string) ([][]float32, error) {
	if mock.EmbedFunc == nil {
		panic("EmbedderMock.EmbedFunc: method is nil but Embedder.Embed was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Texts []string
	}{
		Ctx:   ctx,
		Texts: texts,
	}
	mock.lockEmbed.Lock()
	mock.calls.Embed = append(mock.calls.Embed, callInfo)
	mock.lockEmbed.Unlock()
	return mock.EmbedFunc(ctx, texts)
}

// EmbedCalls gets all the calls that were made to Embed.
// Check the length with:
//
//	len(mockedEmbedder.EmbedCalls())
func (mock *EmbedderMock) EmbedCalls() []struct {
	Ctx   context.Context
	Texts []string
} {
	var calls []struct {
		Ctx   context.Context
		Texts []string
	}
	mock.lockEmbed.RLock()
	calls = mock.calls.Embed
	mock.lockEmbed.RUnlock()
	return calls
}

// ModelID calls ModelIDFunc.
func (mock *EmbedderMock) ModelID() string {
	if mock.ModelIDFunc == nil {
		panic("EmbedderMock.ModelIDFunc: method is nil but Embedder.ModelID was just called")
	}
	callInfo := struct {
	}{}
	mock.lockModelID.Lock()
	mock.calls.ModelID = append(mock.calls.ModelID, callInfo)
	mock.lockModelID.Unlock()
	return mock.ModelIDFunc()
}

// ModelIDCalls gets all the calls that were made to ModelID.
// Check the length with:
//
//	len(mockedEmbedder.ModelIDCalls())
func (mock *EmbedderMock) ModelIDCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockModelID.RLock()
	calls = mock.calls.ModelID
	mock.lockModelID.RUnlock()
	return calls
}
