// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package graph

import (
	"context"
	"github.com/bobcob7/loam/internal/codegraph"
	"github.com/bobcob7/loam/internal/parser"
	"github.com/google/uuid"
	"sync"
)

// Ensure, that fileParserMock does implement fileParser.
// If this is not the case, regenerate this file with moq.
var _ fileParser = &fileParserMock{}

// fileParserMock is a mock implementation of fileParser.
//
//	func TestSomethingThatUsesfileParser(t *testing.T) {
//
//		// make and configure a mocked fileParser
//		mockedfileParser := &fileParserMock{
//			ParseFunc: func(ctx context.Context, lang parser.Language, src []byte) (*parser.Tree, error) {
//				panic("mock out the Parse method")
//			},
//		}
//
//		// use mockedfileParser in code that requires fileParser
//		// and then make assertions.
//
//	}
type fileParserMock struct {
	// ParseFunc mocks the Parse method.
	ParseFunc func(ctx context.Context, lang parser.Language, src []byte) (*parser.Tree, error)

	// calls tracks calls to the methods.
	calls struct {
		// Parse holds details about calls to the Parse method.
		Parse []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Lang is the lang argument value.
			Lang parser.Language
			// Src is the src argument value.
			Src []byte
		}
	}
	lockParse sync.RWMutex
}

// Parse calls ParseFunc.
func (mock *fileParserMock) Parse(ctx context.Context, lang parser.Language, src []byte) (*parser.Tree, error) {
	if mock.ParseFunc == nil {
		panic("fileParserMock.ParseFunc: method is nil but fileParser.Parse was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Lang parser.Language
		Src  []byte
	}{
		Ctx:  ctx,
		Lang: lang,
		Src:  src,
	}
	mock.lockParse.Lock()
	mock.calls.Parse = append(mock.calls.Parse, callInfo)
	mock.lockParse.Unlock()
	return mock.ParseFunc(ctx, lang, src)
}

// ParseCalls gets all the calls that were made to Parse.
// Check the length with:
//
//	len(mockedfileParser.ParseCalls())
func (mock *fileParserMock) ParseCalls() []struct {
	Ctx  context.Context
	Lang parser.Language
	Src  []byte
} {
	var calls []struct {
		Ctx  context.Context
		Lang parser.Language
		Src  []byte
	}
	mock.lockParse.RLock()
	calls = mock.calls.Parse
	mock.lockParse.RUnlock()
	return calls
}

// Ensure, that storeMock does implement store.
// If this is not the case, regenerate this file with moq.
var _ store = &storeMock{}

// storeMock is a mock implementation of store.
//
//	func TestSomethingThatUsesstore(t *testing.T) {
//
//		// make and configure a mocked store
//		mockedstore := &storeMock{
//			RecomputeGraphEdgesFunc: func(ctx context.Context, repoID uuid.UUID, targetBranch string) (int64, error) {
//				panic("mock out the RecomputeGraphEdges method")
//			},
//			ReplaceFileReferencesFunc: func(ctx context.Context, repoID uuid.UUID, targetBranch string, file string, refs []codegraph.ReferenceInput) (int64, error) {
//				panic("mock out the ReplaceFileReferences method")
//			},
//			ReplaceFileSymbolsFunc: func(ctx context.Context, repoID uuid.UUID, targetBranch string, file string, symbols []codegraph.SymbolInput) ([]codegraph.Symbol, error) {
//				panic("mock out the ReplaceFileSymbols method")
//			},
//		}
//
//		// use mockedstore in code that requires store
//		// and then make assertions.
//
//	}
type storeMock struct {
	// RecomputeGraphEdgesFunc mocks the RecomputeGraphEdges method.
	RecomputeGraphEdgesFunc func(ctx context.Context, repoID uuid.UUID, targetBranch string) (int64, error)

	// ReplaceFileReferencesFunc mocks the ReplaceFileReferences method.
	ReplaceFileReferencesFunc func(ctx context.Context, repoID uuid.UUID, targetBranch string, file string, refs []codegraph.ReferenceInput) (int64, error)

	// ReplaceFileSymbolsFunc mocks the ReplaceFileSymbols method.
	ReplaceFileSymbolsFunc func(ctx context.Context, repoID uuid.UUID, targetBranch string, file string, symbols []codegraph.SymbolInput) ([]codegraph.Symbol, error)

	// calls tracks calls to the methods.
	calls struct {
		// RecomputeGraphEdges holds details about calls to the RecomputeGraphEdges method.
		RecomputeGraphEdges []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RepoID is the repoID argument value.
			RepoID uuid.UUID
			// TargetBranch is the targetBranch argument value.
			TargetBranch string
		}
		// ReplaceFileReferences holds details about calls to the ReplaceFileReferences method.
		ReplaceFileReferences []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RepoID is the repoID argument value.
			RepoID uuid.UUID
			// TargetBranch is the targetBranch argument value.
			TargetBranch string
			// File is the file argument value.
			File string
			// Refs is the refs argument value.
			Refs []codegraph.ReferenceInput
		}
		// ReplaceFileSymbols holds details about calls to the ReplaceFileSymbols method.
		ReplaceFileSymbols []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RepoID is the repoID argument value.
			RepoID uuid.UUID
			// TargetBranch is the targetBranch argument value.
			TargetBranch string
			// File is the file argument value.
			File string
			// Symbols is the symbols argument value.
			Symbols []codegraph.SymbolInput
		}
	}
	lockRecomputeGraphEdges   sync.RWMutex
	lockReplaceFileReferences sync.RWMutex
	lockReplaceFileSymbols    sync.RWMutex
}

// RecomputeGraphEdges calls RecomputeGraphEdgesFunc.
func (mock *storeMock) RecomputeGraphEdges(ctx context.Context, repoID uuid.UUID, targetBranch string) (int64, error) {
	if mock.RecomputeGraphEdgesFunc == nil {
		panic("storeMock.RecomputeGraphEdgesFunc: method is nil but store.RecomputeGraphEdges was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		RepoID       uuid.UUID
		TargetBranch string
	}{
		Ctx:          ctx,
		RepoID:       repoID,
		TargetBranch: targetBranch,
	}
	mock.lockRecomputeGraphEdges.Lock()
	mock.calls.RecomputeGraphEdges = append(mock.calls.RecomputeGraphEdges, callInfo)
	mock.lockRecomputeGraphEdges.Unlock()
	return mock.RecomputeGraphEdgesFunc(ctx, repoID, targetBranch)
}

// RecomputeGraphEdgesCalls gets all the calls that were made to RecomputeGraphEdges.
// Check the length with:
//
//	len(mockedstore.RecomputeGraphEdgesCalls())
func (mock *storeMock) RecomputeGraphEdgesCalls() []struct {
	Ctx          context.Context
	RepoID       uuid.UUID
	TargetBranch string
} {
	var calls []struct {
		Ctx          context.Context
		RepoID       uuid.UUID
		TargetBranch string
	}
	mock.lockRecomputeGraphEdges.RLock()
	calls = mock.calls.RecomputeGraphEdges
	mock.lockRecomputeGraphEdges.RUnlock()
	return calls
}

// ReplaceFileReferences calls ReplaceFileReferencesFunc.
func (mock *storeMock) ReplaceFileReferences(ctx context.Context, repoID uuid.UUID, targetBranch string, file string, refs []codegraph.ReferenceInput) (int64, error) {
	if mock.ReplaceFileReferencesFunc == nil {
		panic("storeMock.ReplaceFileReferencesFunc: method is nil but store.ReplaceFileReferences was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		RepoID       uuid.UUID
		TargetBranch string
		File         string
		Refs         []codegraph.ReferenceInput
	}{
		Ctx:          ctx,
		RepoID:       repoID,
		TargetBranch: targetBranch,
		File:         file,
		Refs:         refs,
	}
	mock.lockReplaceFileReferences.Lock()
	mock.calls.ReplaceFileReferences = append(mock.calls.ReplaceFileReferences, callInfo)
	mock.lockReplaceFileReferences.Unlock()
	return mock.ReplaceFileReferencesFunc(ctx, repoID, targetBranch, file, refs)
}

// ReplaceFileReferencesCalls gets all the calls that were made to ReplaceFileReferences.
// Check the length with:
//
//	len(mockedstore.ReplaceFileReferencesCalls())
func (mock *storeMock) ReplaceFileReferencesCalls() []struct {
	Ctx          context.Context
	RepoID       uuid.UUID
	TargetBranch string
	File         string
	Refs         []codegraph.ReferenceInput
} {
	var calls []struct {
		Ctx          context.Context
		RepoID       uuid.UUID
		TargetBranch string
		File         string
		Refs         []codegraph.ReferenceInput
	}
	mock.lockReplaceFileReferences.RLock()
	calls = mock.calls.ReplaceFileReferences
	mock.lockReplaceFileReferences.RUnlock()
	return calls
}

// ReplaceFileSymbols calls ReplaceFileSymbolsFunc.
func (mock *storeMock) ReplaceFileSymbols(ctx context.Context, repoID uuid.UUID, targetBranch string, file string, symbols []codegraph.SymbolInput) ([]codegraph.Symbol, error) {
	if mock.ReplaceFileSymbolsFunc == nil {
		panic("storeMock.ReplaceFileSymbolsFunc: method is nil but store.ReplaceFileSymbols was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		RepoID       uuid.UUID
		TargetBranch string
		File         string
		Symbols      []codegraph.SymbolInput
	}{
		Ctx:          ctx,
		RepoID:       repoID,
		TargetBranch: targetBranch,
		File:         file,
		Symbols:      symbols,
	}
	mock.lockReplaceFileSymbols.Lock()
	mock.calls.ReplaceFileSymbols = append(mock.calls.ReplaceFileSymbols, callInfo)
	mock.lockReplaceFileSymbols.Unlock()
	return mock.ReplaceFileSymbolsFunc(ctx, repoID, targetBranch, file, symbols)
}

// ReplaceFileSymbolsCalls gets all the calls that were made to ReplaceFileSymbols.
// Check the length with:
//
//	len(mockedstore.ReplaceFileSymbolsCalls())
func (mock *storeMock) ReplaceFileSymbolsCalls() []struct {
	Ctx          context.Context
	RepoID       uuid.UUID
	TargetBranch string
	File         string
	Symbols      []codegraph.SymbolInput
} {
	var calls []struct {
		Ctx          context.Context
		RepoID       uuid.UUID
		TargetBranch string
		File         string
		Symbols      []codegraph.SymbolInput
	}
	mock.lockReplaceFileSymbols.RLock()
	calls = mock.calls.ReplaceFileSymbols
	mock.lockReplaceFileSymbols.RUnlock()
	return calls
}
