// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package meta

import (
	"context"
	"github.com/bobcob7/loam/internal/handler"
	"sync"
)

// Ensure, that RoleStoreMock does implement RoleStore.
// If this is not the case, regenerate this file with moq.
var _ RoleStore = &RoleStoreMock{}

// RoleStoreMock is a mock implementation of RoleStore.
//
//	func TestSomethingThatUsesRoleStore(t *testing.T) {
//
//		// make and configure a mocked RoleStore
//		mockedRoleStore := &RoleStoreMock{
//			RoleCapabilitiesFunc: func(ctx context.Context, role string) ([]handler.Capability, error) {
//				panic("mock out the RoleCapabilities method")
//			},
//			RoleInstructionsFunc: func(ctx context.Context, role string) (string, error) {
//				panic("mock out the RoleInstructions method")
//			},
//		}
//
//		// use mockedRoleStore in code that requires RoleStore
//		// and then make assertions.
//
//	}
type RoleStoreMock struct {
	// RoleCapabilitiesFunc mocks the RoleCapabilities method.
	RoleCapabilitiesFunc func(ctx context.Context, role string) ([]handler.Capability, error)

	// RoleInstructionsFunc mocks the RoleInstructions method.
	RoleInstructionsFunc func(ctx context.Context, role string) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// RoleCapabilities holds details about calls to the RoleCapabilities method.
		RoleCapabilities []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Role is the role argument value.
			Role string
		}
		// RoleInstructions holds details about calls to the RoleInstructions method.
		RoleInstructions []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Role is the role argument value.
			Role string
		}
	}
	lockRoleCapabilities sync.RWMutex
	lockRoleInstructions sync.RWMutex
}

// RoleCapabilities calls RoleCapabilitiesFunc.
func (mock *RoleStoreMock) RoleCapabilities(ctx context.Context, role string) ([]handler.Capability, error) {
	if mock.RoleCapabilitiesFunc == nil {
		panic("RoleStoreMock.RoleCapabilitiesFunc: method is nil but RoleStore.RoleCapabilities was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Role string
	}{
		Ctx:  ctx,
		Role: role,
	}
	mock.lockRoleCapabilities.Lock()
	mock.calls.RoleCapabilities = append(mock.calls.RoleCapabilities, callInfo)
	mock.lockRoleCapabilities.Unlock()
	return mock.RoleCapabilitiesFunc(ctx, role)
}

// RoleCapabilitiesCalls gets all the calls that were made to RoleCapabilities.
// Check the length with:
//
//	len(mockedRoleStore.RoleCapabilitiesCalls())
func (mock *RoleStoreMock) RoleCapabilitiesCalls() []struct {
	Ctx  context.Context
	Role string
} {
	var calls []struct {
		Ctx  context.Context
		Role string
	}
	mock.lockRoleCapabilities.RLock()
	calls = mock.calls.RoleCapabilities
	mock.lockRoleCapabilities.RUnlock()
	return calls
}

// RoleInstructions calls RoleInstructionsFunc.
func (mock *RoleStoreMock) RoleInstructions(ctx context.Context, role string) (string, error) {
	if mock.RoleInstructionsFunc == nil {
		panic("RoleStoreMock.RoleInstructionsFunc: method is nil but RoleStore.RoleInstructions was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Role string
	}{
		Ctx:  ctx,
		Role: role,
	}
	mock.lockRoleInstructions.Lock()
	mock.calls.RoleInstructions = append(mock.calls.RoleInstructions, callInfo)
	mock.lockRoleInstructions.Unlock()
	return mock.RoleInstructionsFunc(ctx, role)
}

// RoleInstructionsCalls gets all the calls that were made to RoleInstructions.
// Check the length with:
//
//	len(mockedRoleStore.RoleInstructionsCalls())
func (mock *RoleStoreMock) RoleInstructionsCalls() []struct {
	Ctx  context.Context
	Role string
} {
	var calls []struct {
		Ctx  context.Context
		Role string
	}
	mock.lockRoleInstructions.RLock()
	calls = mock.calls.RoleInstructions
	mock.lockRoleInstructions.RUnlock()
	return calls
}
