// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package credentialstore

import (
	"context"
	"github.com/bobcob7/loam/internal/db/gen"
	"sync"
)

// Ensure, that querierMock does implement querier.
// If this is not the case, regenerate this file with moq.
var _ querier = &querierMock{}

// querierMock is a mock implementation of querier.
//
//	func TestSomethingThatUsesquerier(t *testing.T) {
//
//		// make and configure a mocked querier
//		mockedquerier := &querierMock{
//			GetCredentialByHostFunc: func(ctx context.Context, host string) (gen.Credential, error) {
//				panic("mock out the GetCredentialByHost method")
//			},
//			GetCredentialStatusFunc: func(ctx context.Context, host string) (gen.GetCredentialStatusRow, error) {
//				panic("mock out the GetCredentialStatus method")
//			},
//			ListCredentialStatusesFunc: func(ctx context.Context) ([]gen.ListCredentialStatusesRow, error) {
//				panic("mock out the ListCredentialStatuses method")
//			},
//			SetCredentialValidatedFunc: func(ctx context.Context, arg gen.SetCredentialValidatedParams) (gen.SetCredentialValidatedRow, error) {
//				panic("mock out the SetCredentialValidated method")
//			},
//			UpsertCredentialTokenFunc: func(ctx context.Context, arg gen.UpsertCredentialTokenParams) (gen.Credential, error) {
//				panic("mock out the UpsertCredentialToken method")
//			},
//		}
//
//		// use mockedquerier in code that requires querier
//		// and then make assertions.
//
//	}
type querierMock struct {
	// GetCredentialByHostFunc mocks the GetCredentialByHost method.
	GetCredentialByHostFunc func(ctx context.Context, host string) (gen.Credential, error)

	// GetCredentialStatusFunc mocks the GetCredentialStatus method.
	GetCredentialStatusFunc func(ctx context.Context, host string) (gen.GetCredentialStatusRow, error)

	// ListCredentialStatusesFunc mocks the ListCredentialStatuses method.
	ListCredentialStatusesFunc func(ctx context.Context) ([]gen.ListCredentialStatusesRow, error)

	// SetCredentialValidatedFunc mocks the SetCredentialValidated method.
	SetCredentialValidatedFunc func(ctx context.Context, arg gen.SetCredentialValidatedParams) (gen.SetCredentialValidatedRow, error)

	// UpsertCredentialTokenFunc mocks the UpsertCredentialToken method.
	UpsertCredentialTokenFunc func(ctx context.Context, arg gen.UpsertCredentialTokenParams) (gen.Credential, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetCredentialByHost holds details about calls to the GetCredentialByHost method.
		GetCredentialByHost []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Host is the host argument value.
			Host string
		}
		// GetCredentialStatus holds details about calls to the GetCredentialStatus method.
		GetCredentialStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Host is the host argument value.
			Host string
		}
		// ListCredentialStatuses holds details about calls to the ListCredentialStatuses method.
		ListCredentialStatuses []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// SetCredentialValidated holds details about calls to the SetCredentialValidated method.
		SetCredentialValidated []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg gen.SetCredentialValidatedParams
		}
		// UpsertCredentialToken holds details about calls to the UpsertCredentialToken method.
		UpsertCredentialToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg gen.UpsertCredentialTokenParams
		}
	}
	lockGetCredentialByHost    sync.RWMutex
	lockGetCredentialStatus    sync.RWMutex
	lockListCredentialStatuses sync.RWMutex
	lockSetCredentialValidated sync.RWMutex
	lockUpsertCredentialToken  sync.RWMutex
}

// GetCredentialByHost calls GetCredentialByHostFunc.
func (mock *querierMock) GetCredentialByHost(ctx context.Context, host string) (gen.Credential, error) {
	if mock.GetCredentialByHostFunc == nil {
		panic("querierMock.GetCredentialByHostFunc: method is nil but querier.GetCredentialByHost was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Host string
	}{
		Ctx:  ctx,
		Host: host,
	}
	mock.lockGetCredentialByHost.Lock()
	mock.calls.GetCredentialByHost = append(mock.calls.GetCredentialByHost, callInfo)
	mock.lockGetCredentialByHost.Unlock()
	return mock.GetCredentialByHostFunc(ctx, host)
}

// GetCredentialByHostCalls gets all the calls that were made to GetCredentialByHost.
// Check the length with:
//
//	len(mockedquerier.GetCredentialByHostCalls())
func (mock *querierMock) GetCredentialByHostCalls() []struct {
	Ctx  context.Context
	Host string
} {
	var calls []struct {
		Ctx  context.Context
		Host string
	}
	mock.lockGetCredentialByHost.RLock()
	calls = mock.calls.GetCredentialByHost
	mock.lockGetCredentialByHost.RUnlock()
	return calls
}

// GetCredentialStatus calls GetCredentialStatusFunc.
func (mock *querierMock) GetCredentialStatus(ctx context.Context, host string) (gen.GetCredentialStatusRow, error) {
	if mock.GetCredentialStatusFunc == nil {
		panic("querierMock.GetCredentialStatusFunc: method is nil but querier.GetCredentialStatus was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Host string
	}{
		Ctx:  ctx,
		Host: host,
	}
	mock.lockGetCredentialStatus.Lock()
	mock.calls.GetCredentialStatus = append(mock.calls.GetCredentialStatus, callInfo)
	mock.lockGetCredentialStatus.Unlock()
	return mock.GetCredentialStatusFunc(ctx, host)
}

// GetCredentialStatusCalls gets all the calls that were made to GetCredentialStatus.
// Check the length with:
//
//	len(mockedquerier.GetCredentialStatusCalls())
func (mock *querierMock) GetCredentialStatusCalls() []struct {
	Ctx  context.Context
	Host string
} {
	var calls []struct {
		Ctx  context.Context
		Host string
	}
	mock.lockGetCredentialStatus.RLock()
	calls = mock.calls.GetCredentialStatus
	mock.lockGetCredentialStatus.RUnlock()
	return calls
}

// ListCredentialStatuses calls ListCredentialStatusesFunc.
func (mock *querierMock) ListCredentialStatuses(ctx context.Context) ([]gen.ListCredentialStatusesRow, error) {
	if mock.ListCredentialStatusesFunc == nil {
		panic("querierMock.ListCredentialStatusesFunc: method is nil but querier.ListCredentialStatuses was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListCredentialStatuses.Lock()
	mock.calls.ListCredentialStatuses = append(mock.calls.ListCredentialStatuses, callInfo)
	mock.lockListCredentialStatuses.Unlock()
	return mock.ListCredentialStatusesFunc(ctx)
}

// ListCredentialStatusesCalls gets all the calls that were made to ListCredentialStatuses.
// Check the length with:
//
//	len(mockedquerier.ListCredentialStatusesCalls())
func (mock *querierMock) ListCredentialStatusesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListCredentialStatuses.RLock()
	calls = mock.calls.ListCredentialStatuses
	mock.lockListCredentialStatuses.RUnlock()
	return calls
}

// SetCredentialValidated calls SetCredentialValidatedFunc.
func (mock *querierMock) SetCredentialValidated(ctx context.Context, arg gen.SetCredentialValidatedParams) (gen.SetCredentialValidatedRow, error) {
	if mock.SetCredentialValidatedFunc == nil {
		panic("querierMock.SetCredentialValidatedFunc: method is nil but querier.SetCredentialValidated was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg gen.SetCredentialValidatedParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockSetCredentialValidated.Lock()
	mock.calls.SetCredentialValidated = append(mock.calls.SetCredentialValidated, callInfo)
	mock.lockSetCredentialValidated.Unlock()
	return mock.SetCredentialValidatedFunc(ctx, arg)
}

// SetCredentialValidatedCalls gets all the calls that were made to SetCredentialValidated.
// Check the length with:
//
//	len(mockedquerier.SetCredentialValidatedCalls())
func (mock *querierMock) SetCredentialValidatedCalls() []struct {
	Ctx context.Context
	Arg gen.SetCredentialValidatedParams
} {
	var calls []struct {
		Ctx context.Context
		Arg gen.SetCredentialValidatedParams
	}
	mock.lockSetCredentialValidated.RLock()
	calls = mock.calls.SetCredentialValidated
	mock.lockSetCredentialValidated.RUnlock()
	return calls
}

// UpsertCredentialToken calls UpsertCredentialTokenFunc.
func (mock *querierMock) UpsertCredentialToken(ctx context.Context, arg gen.UpsertCredentialTokenParams) (gen.Credential, error) {
	if mock.UpsertCredentialTokenFunc == nil {
		panic("querierMock.UpsertCredentialTokenFunc: method is nil but querier.UpsertCredentialToken was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg gen.UpsertCredentialTokenParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockUpsertCredentialToken.Lock()
	mock.calls.UpsertCredentialToken = append(mock.calls.UpsertCredentialToken, callInfo)
	mock.lockUpsertCredentialToken.Unlock()
	return mock.UpsertCredentialTokenFunc(ctx, arg)
}

// UpsertCredentialTokenCalls gets all the calls that were made to UpsertCredentialToken.
// Check the length with:
//
//	len(mockedquerier.UpsertCredentialTokenCalls())
func (mock *querierMock) UpsertCredentialTokenCalls() []struct {
	Ctx context.Context
	Arg gen.UpsertCredentialTokenParams
} {
	var calls []struct {
		Ctx context.Context
		Arg gen.UpsertCredentialTokenParams
	}
	mock.lockUpsertCredentialToken.RLock()
	calls = mock.calls.UpsertCredentialToken
	mock.lockUpsertCredentialToken.RUnlock()
	return calls
}

// Ensure, that encryptorMock does implement encryptor.
// If this is not the case, regenerate this file with moq.
var _ encryptor = &encryptorMock{}

// encryptorMock is a mock implementation of encryptor.
//
//	func TestSomethingThatUsesencryptor(t *testing.T) {
//
//		// make and configure a mocked encryptor
//		mockedencryptor := &encryptorMock{
//			DecryptFunc: func(ciphertext []byte) ([]byte, error) {
//				panic("mock out the Decrypt method")
//			},
//			EncryptFunc: func(plaintext []byte) ([]byte, error) {
//				panic("mock out the Encrypt method")
//			},
//		}
//
//		// use mockedencryptor in code that requires encryptor
//		// and then make assertions.
//
//	}
type encryptorMock struct {
	// DecryptFunc mocks the Decrypt method.
	DecryptFunc func(ciphertext []byte) ([]byte, error)

	// EncryptFunc mocks the Encrypt method.
	EncryptFunc func(plaintext []byte) ([]byte, error)

	// calls tracks calls to the methods.
	calls struct {
		// Decrypt holds details about calls to the Decrypt method.
		Decrypt []struct {
			// Ciphertext is the ciphertext argument value.
			Ciphertext []byte
		}
		// Encrypt holds details about calls to the Encrypt method.
		Encrypt []struct {
			// Plaintext is the plaintext argument value.
			Plaintext []byte
		}
	}
	lockDecrypt sync.RWMutex
	lockEncrypt sync.RWMutex
}

// Decrypt calls DecryptFunc.
func (mock *encryptorMock) Decrypt(ciphertext []byte) ([]byte, error) {
	if mock.DecryptFunc == nil {
		panic("encryptorMock.DecryptFunc: method is nil but encryptor.Decrypt was just called")
	}
	callInfo := struct {
		Ciphertext []byte
	}{
		Ciphertext: ciphertext,
	}
	mock.lockDecrypt.Lock()
	mock.calls.Decrypt = append(mock.calls.Decrypt, callInfo)
	mock.lockDecrypt.Unlock()
	return mock.DecryptFunc(ciphertext)
}

// DecryptCalls gets all the calls that were made to Decrypt.
// Check the length with:
//
//	len(mockedencryptor.DecryptCalls())
func (mock *encryptorMock) DecryptCalls() []struct {
	Ciphertext []byte
} {
	var calls []struct {
		Ciphertext []byte
	}
	mock.lockDecrypt.RLock()
	calls = mock.calls.Decrypt
	mock.lockDecrypt.RUnlock()
	return calls
}

// Encrypt calls EncryptFunc.
func (mock *encryptorMock) Encrypt(plaintext []byte) ([]byte, error) {
	if mock.EncryptFunc == nil {
		panic("encryptorMock.EncryptFunc: method is nil but encryptor.Encrypt was just called")
	}
	callInfo := struct {
		Plaintext []byte
	}{
		Plaintext: plaintext,
	}
	mock.lockEncrypt.Lock()
	mock.calls.Encrypt = append(mock.calls.Encrypt, callInfo)
	mock.lockEncrypt.Unlock()
	return mock.EncryptFunc(plaintext)
}

// EncryptCalls gets all the calls that were made to Encrypt.
// Check the length with:
//
//	len(mockedencryptor.EncryptCalls())
func (mock *encryptorMock) EncryptCalls() []struct {
	Plaintext []byte
} {
	var calls []struct {
		Plaintext []byte
	}
	mock.lockEncrypt.RLock()
	calls = mock.calls.Encrypt
	mock.lockEncrypt.RUnlock()
	return calls
}
