// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mirrorsync

import (
	"context"
	"github.com/bobcob7/loam/internal/ingest"
	"github.com/bobcob7/loam/internal/reposstore"
	"github.com/bobcob7/loam/internal/workbranchstore"
	"github.com/google/uuid"
	"sync"
)

// Ensure, that RepoListerMock does implement RepoLister.
// If this is not the case, regenerate this file with moq.
var _ RepoLister = &RepoListerMock{}

// RepoListerMock is a mock implementation of RepoLister.
//
//	func TestSomethingThatUsesRepoLister(t *testing.T) {
//
//		// make and configure a mocked RepoLister
//		mockedRepoLister := &RepoListerMock{
//			ListReposFunc: func(ctx context.Context) ([]RepoID, error) {
//				panic("mock out the ListRepos method")
//			},
//		}
//
//		// use mockedRepoLister in code that requires RepoLister
//		// and then make assertions.
//
//	}
type RepoListerMock struct {
	// ListReposFunc mocks the ListRepos method.
	ListReposFunc func(ctx context.Context) ([]RepoID, error)

	// calls tracks calls to the methods.
	calls struct {
		// ListRepos holds details about calls to the ListRepos method.
		ListRepos []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockListRepos sync.RWMutex
}

// ListRepos calls ListReposFunc.
func (mock *RepoListerMock) ListRepos(ctx context.Context) ([]RepoID, error) {
	if mock.ListReposFunc == nil {
		panic("RepoListerMock.ListReposFunc: method is nil but RepoLister.ListRepos was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListRepos.Lock()
	mock.calls.ListRepos = append(mock.calls.ListRepos, callInfo)
	mock.lockListRepos.Unlock()
	return mock.ListReposFunc(ctx)
}

// ListReposCalls gets all the calls that were made to ListRepos.
// Check the length with:
//
//	len(mockedRepoLister.ListReposCalls())
func (mock *RepoListerMock) ListReposCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListRepos.RLock()
	calls = mock.calls.ListRepos
	mock.lockListRepos.RUnlock()
	return calls
}

// Ensure, that FetcherMock does implement Fetcher.
// If this is not the case, regenerate this file with moq.
var _ Fetcher = &FetcherMock{}

// FetcherMock is a mock implementation of Fetcher.
//
//	func TestSomethingThatUsesFetcher(t *testing.T) {
//
//		// make and configure a mocked Fetcher
//		mockedFetcher := &FetcherMock{
//			FetchFunc: func(ctx context.Context, repo RepoID) (FetchResult, error) {
//				panic("mock out the Fetch method")
//			},
//		}
//
//		// use mockedFetcher in code that requires Fetcher
//		// and then make assertions.
//
//	}
type FetcherMock struct {
	// FetchFunc mocks the Fetch method.
	FetchFunc func(ctx context.Context, repo RepoID) (FetchResult, error)

	// calls tracks calls to the methods.
	calls struct {
		// Fetch holds details about calls to the Fetch method.
		Fetch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Repo is the repo argument value.
			Repo RepoID
		}
	}
	lockFetch sync.RWMutex
}

// Fetch calls FetchFunc.
func (mock *FetcherMock) Fetch(ctx context.Context, repo RepoID) (FetchResult, error) {
	if mock.FetchFunc == nil {
		panic("FetcherMock.FetchFunc: method is nil but Fetcher.Fetch was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Repo RepoID
	}{
		Ctx:  ctx,
		Repo: repo,
	}
	mock.lockFetch.Lock()
	mock.calls.Fetch = append(mock.calls.Fetch, callInfo)
	mock.lockFetch.Unlock()
	return mock.FetchFunc(ctx, repo)
}

// FetchCalls gets all the calls that were made to Fetch.
// Check the length with:
//
//	len(mockedFetcher.FetchCalls())
func (mock *FetcherMock) FetchCalls() []struct {
	Ctx  context.Context
	Repo RepoID
} {
	var calls []struct {
		Ctx  context.Context
		Repo RepoID
	}
	mock.lockFetch.RLock()
	calls = mock.calls.Fetch
	mock.lockFetch.RUnlock()
	return calls
}

// Ensure, that AdvanceDetectorMock does implement AdvanceDetector.
// If this is not the case, regenerate this file with moq.
var _ AdvanceDetector = &AdvanceDetectorMock{}

// AdvanceDetectorMock is a mock implementation of AdvanceDetector.
//
//	func TestSomethingThatUsesAdvanceDetector(t *testing.T) {
//
//		// make and configure a mocked AdvanceDetector
//		mockedAdvanceDetector := &AdvanceDetectorMock{
//			DetectAdvancesFunc: func(ctx context.Context, repo RepoID, fetched FetchResult) ([]Advance, error) {
//				panic("mock out the DetectAdvances method")
//			},
//		}
//
//		// use mockedAdvanceDetector in code that requires AdvanceDetector
//		// and then make assertions.
//
//	}
type AdvanceDetectorMock struct {
	// DetectAdvancesFunc mocks the DetectAdvances method.
	DetectAdvancesFunc func(ctx context.Context, repo RepoID, fetched FetchResult) ([]Advance, error)

	// calls tracks calls to the methods.
	calls struct {
		// DetectAdvances holds details about calls to the DetectAdvances method.
		DetectAdvances []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Repo is the repo argument value.
			Repo RepoID
			// Fetched is the fetched argument value.
			Fetched FetchResult
		}
	}
	lockDetectAdvances sync.RWMutex
}

// DetectAdvances calls DetectAdvancesFunc.
func (mock *AdvanceDetectorMock) DetectAdvances(ctx context.Context, repo RepoID, fetched FetchResult) ([]Advance, error) {
	if mock.DetectAdvancesFunc == nil {
		panic("AdvanceDetectorMock.DetectAdvancesFunc: method is nil but AdvanceDetector.DetectAdvances was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Repo    RepoID
		Fetched FetchResult
	}{
		Ctx:     ctx,
		Repo:    repo,
		Fetched: fetched,
	}
	mock.lockDetectAdvances.Lock()
	mock.calls.DetectAdvances = append(mock.calls.DetectAdvances, callInfo)
	mock.lockDetectAdvances.Unlock()
	return mock.DetectAdvancesFunc(ctx, repo, fetched)
}

// DetectAdvancesCalls gets all the calls that were made to DetectAdvances.
// Check the length with:
//
//	len(mockedAdvanceDetector.DetectAdvancesCalls())
func (mock *AdvanceDetectorMock) DetectAdvancesCalls() []struct {
	Ctx     context.Context
	Repo    RepoID
	Fetched FetchResult
} {
	var calls []struct {
		Ctx     context.Context
		Repo    RepoID
		Fetched FetchResult
	}
	mock.lockDetectAdvances.RLock()
	calls = mock.calls.DetectAdvances
	mock.lockDetectAdvances.RUnlock()
	return calls
}

// Ensure, that MergeabilityCheckerMock does implement MergeabilityChecker.
// If this is not the case, regenerate this file with moq.
var _ MergeabilityChecker = &MergeabilityCheckerMock{}

// MergeabilityCheckerMock is a mock implementation of MergeabilityChecker.
//
//	func TestSomethingThatUsesMergeabilityChecker(t *testing.T) {
//
//		// make and configure a mocked MergeabilityChecker
//		mockedMergeabilityChecker := &MergeabilityCheckerMock{
//			CheckMergeabilityFunc: func(ctx context.Context, repo RepoID, advanced []Advance) error {
//				panic("mock out the CheckMergeability method")
//			},
//		}
//
//		// use mockedMergeabilityChecker in code that requires MergeabilityChecker
//		// and then make assertions.
//
//	}
type MergeabilityCheckerMock struct {
	// CheckMergeabilityFunc mocks the CheckMergeability method.
	CheckMergeabilityFunc func(ctx context.Context, repo RepoID, advanced []Advance) error

	// calls tracks calls to the methods.
	calls struct {
		// CheckMergeability holds details about calls to the CheckMergeability method.
		CheckMergeability []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Repo is the repo argument value.
			Repo RepoID
			// Advanced is the advanced argument value.
			Advanced []Advance
		}
	}
	lockCheckMergeability sync.RWMutex
}

// CheckMergeability calls CheckMergeabilityFunc.
func (mock *MergeabilityCheckerMock) CheckMergeability(ctx context.Context, repo RepoID, advanced []Advance) error {
	if mock.CheckMergeabilityFunc == nil {
		panic("MergeabilityCheckerMock.CheckMergeabilityFunc: method is nil but MergeabilityChecker.CheckMergeability was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Repo     RepoID
		Advanced []Advance
	}{
		Ctx:      ctx,
		Repo:     repo,
		Advanced: advanced,
	}
	mock.lockCheckMergeability.Lock()
	mock.calls.CheckMergeability = append(mock.calls.CheckMergeability, callInfo)
	mock.lockCheckMergeability.Unlock()
	return mock.CheckMergeabilityFunc(ctx, repo, advanced)
}

// CheckMergeabilityCalls gets all the calls that were made to CheckMergeability.
// Check the length with:
//
//	len(mockedMergeabilityChecker.CheckMergeabilityCalls())
func (mock *MergeabilityCheckerMock) CheckMergeabilityCalls() []struct {
	Ctx      context.Context
	Repo     RepoID
	Advanced []Advance
} {
	var calls []struct {
		Ctx      context.Context
		Repo     RepoID
		Advanced []Advance
	}
	mock.lockCheckMergeability.RLock()
	calls = mock.calls.CheckMergeability
	mock.lockCheckMergeability.RUnlock()
	return calls
}

// Ensure, that IngestEnqueuerMock does implement IngestEnqueuer.
// If this is not the case, regenerate this file with moq.
var _ IngestEnqueuer = &IngestEnqueuerMock{}

// IngestEnqueuerMock is a mock implementation of IngestEnqueuer.
//
//	func TestSomethingThatUsesIngestEnqueuer(t *testing.T) {
//
//		// make and configure a mocked IngestEnqueuer
//		mockedIngestEnqueuer := &IngestEnqueuerMock{
//			EnqueueIngestFunc: func(ctx context.Context, repo RepoID, advanced []Advance) (bool, error) {
//				panic("mock out the EnqueueIngest method")
//			},
//		}
//
//		// use mockedIngestEnqueuer in code that requires IngestEnqueuer
//		// and then make assertions.
//
//	}
type IngestEnqueuerMock struct {
	// EnqueueIngestFunc mocks the EnqueueIngest method.
	EnqueueIngestFunc func(ctx context.Context, repo RepoID, advanced []Advance) (bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// EnqueueIngest holds details about calls to the EnqueueIngest method.
		EnqueueIngest []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Repo is the repo argument value.
			Repo RepoID
			// Advanced is the advanced argument value.
			Advanced []Advance
		}
	}
	lockEnqueueIngest sync.RWMutex
}

// EnqueueIngest calls EnqueueIngestFunc.
func (mock *IngestEnqueuerMock) EnqueueIngest(ctx context.Context, repo RepoID, advanced []Advance) (bool, error) {
	if mock.EnqueueIngestFunc == nil {
		panic("IngestEnqueuerMock.EnqueueIngestFunc: method is nil but IngestEnqueuer.EnqueueIngest was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Repo     RepoID
		Advanced []Advance
	}{
		Ctx:      ctx,
		Repo:     repo,
		Advanced: advanced,
	}
	mock.lockEnqueueIngest.Lock()
	mock.calls.EnqueueIngest = append(mock.calls.EnqueueIngest, callInfo)
	mock.lockEnqueueIngest.Unlock()
	return mock.EnqueueIngestFunc(ctx, repo, advanced)
}

// EnqueueIngestCalls gets all the calls that were made to EnqueueIngest.
// Check the length with:
//
//	len(mockedIngestEnqueuer.EnqueueIngestCalls())
func (mock *IngestEnqueuerMock) EnqueueIngestCalls() []struct {
	Ctx      context.Context
	Repo     RepoID
	Advanced []Advance
} {
	var calls []struct {
		Ctx      context.Context
		Repo     RepoID
		Advanced []Advance
	}
	mock.lockEnqueueIngest.RLock()
	calls = mock.calls.EnqueueIngest
	mock.lockEnqueueIngest.RUnlock()
	return calls
}

// Ensure, that PRPollerMock does implement PRPoller.
// If this is not the case, regenerate this file with moq.
var _ PRPoller = &PRPollerMock{}

// PRPollerMock is a mock implementation of PRPoller.
//
//	func TestSomethingThatUsesPRPoller(t *testing.T) {
//
//		// make and configure a mocked PRPoller
//		mockedPRPoller := &PRPollerMock{
//			PollPRsFunc: func(ctx context.Context, repo RepoID) error {
//				panic("mock out the PollPRs method")
//			},
//		}
//
//		// use mockedPRPoller in code that requires PRPoller
//		// and then make assertions.
//
//	}
type PRPollerMock struct {
	// PollPRsFunc mocks the PollPRs method.
	PollPRsFunc func(ctx context.Context, repo RepoID) error

	// calls tracks calls to the methods.
	calls struct {
		// PollPRs holds details about calls to the PollPRs method.
		PollPRs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Repo is the repo argument value.
			Repo RepoID
		}
	}
	lockPollPRs sync.RWMutex
}

// PollPRs calls PollPRsFunc.
func (mock *PRPollerMock) PollPRs(ctx context.Context, repo RepoID) error {
	if mock.PollPRsFunc == nil {
		panic("PRPollerMock.PollPRsFunc: method is nil but PRPoller.PollPRs was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Repo RepoID
	}{
		Ctx:  ctx,
		Repo: repo,
	}
	mock.lockPollPRs.Lock()
	mock.calls.PollPRs = append(mock.calls.PollPRs, callInfo)
	mock.lockPollPRs.Unlock()
	return mock.PollPRsFunc(ctx, repo)
}

// PollPRsCalls gets all the calls that were made to PollPRs.
// Check the length with:
//
//	len(mockedPRPoller.PollPRsCalls())
func (mock *PRPollerMock) PollPRsCalls() []struct {
	Ctx  context.Context
	Repo RepoID
} {
	var calls []struct {
		Ctx  context.Context
		Repo RepoID
	}
	mock.lockPollPRs.RLock()
	calls = mock.calls.PollPRs
	mock.lockPollPRs.RUnlock()
	return calls
}

// Ensure, that SyncStateReporterMock does implement SyncStateReporter.
// If this is not the case, regenerate this file with moq.
var _ SyncStateReporter = &SyncStateReporterMock{}

// SyncStateReporterMock is a mock implementation of SyncStateReporter.
//
//	func TestSomethingThatUsesSyncStateReporter(t *testing.T) {
//
//		// make and configure a mocked SyncStateReporter
//		mockedSyncStateReporter := &SyncStateReporterMock{
//			ReportErrorFunc: func(ctx context.Context, repo RepoID, err error, enqueuedIngest bool) error {
//				panic("mock out the ReportError method")
//			},
//			ReportIdleFunc: func(ctx context.Context, repo RepoID, enqueuedIngest bool) error {
//				panic("mock out the ReportIdle method")
//			},
//			ReportSyncingFunc: func(ctx context.Context, repo RepoID) error {
//				panic("mock out the ReportSyncing method")
//			},
//		}
//
//		// use mockedSyncStateReporter in code that requires SyncStateReporter
//		// and then make assertions.
//
//	}
type SyncStateReporterMock struct {
	// ReportErrorFunc mocks the ReportError method.
	ReportErrorFunc func(ctx context.Context, repo RepoID, err error, enqueuedIngest bool) error

	// ReportIdleFunc mocks the ReportIdle method.
	ReportIdleFunc func(ctx context.Context, repo RepoID, enqueuedIngest bool) error

	// ReportSyncingFunc mocks the ReportSyncing method.
	ReportSyncingFunc func(ctx context.Context, repo RepoID) error

	// calls tracks calls to the methods.
	calls struct {
		// ReportError holds details about calls to the ReportError method.
		ReportError []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Repo is the repo argument value.
			Repo RepoID
			// Err is the err argument value.
			Err error
			// EnqueuedIngest is the enqueuedIngest argument value.
			EnqueuedIngest bool
		}
		// ReportIdle holds details about calls to the ReportIdle method.
		ReportIdle []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Repo is the repo argument value.
			Repo RepoID
			// EnqueuedIngest is the enqueuedIngest argument value.
			EnqueuedIngest bool
		}
		// ReportSyncing holds details about calls to the ReportSyncing method.
		ReportSyncing []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Repo is the repo argument value.
			Repo RepoID
		}
	}
	lockReportError   sync.RWMutex
	lockReportIdle    sync.RWMutex
	lockReportSyncing sync.RWMutex
}

// ReportError calls ReportErrorFunc.
func (mock *SyncStateReporterMock) ReportError(ctx context.Context, repo RepoID, err error, enqueuedIngest bool) error {
	if mock.ReportErrorFunc == nil {
		panic("SyncStateReporterMock.ReportErrorFunc: method is nil but SyncStateReporter.ReportError was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		Repo           RepoID
		Err            error
		EnqueuedIngest bool
	}{
		Ctx:            ctx,
		Repo:           repo,
		Err:            err,
		EnqueuedIngest: enqueuedIngest,
	}
	mock.lockReportError.Lock()
	mock.calls.ReportError = append(mock.calls.ReportError, callInfo)
	mock.lockReportError.Unlock()
	return mock.ReportErrorFunc(ctx, repo, err, enqueuedIngest)
}

// ReportErrorCalls gets all the calls that were made to ReportError.
// Check the length with:
//
//	len(mockedSyncStateReporter.ReportErrorCalls())
func (mock *SyncStateReporterMock) ReportErrorCalls() []struct {
	Ctx            context.Context
	Repo           RepoID
	Err            error
	EnqueuedIngest bool
} {
	var calls []struct {
		Ctx            context.Context
		Repo           RepoID
		Err            error
		EnqueuedIngest bool
	}
	mock.lockReportError.RLock()
	calls = mock.calls.ReportError
	mock.lockReportError.RUnlock()
	return calls
}

// ReportIdle calls ReportIdleFunc.
func (mock *SyncStateReporterMock) ReportIdle(ctx context.Context, repo RepoID, enqueuedIngest bool) error {
	if mock.ReportIdleFunc == nil {
		panic("SyncStateReporterMock.ReportIdleFunc: method is nil but SyncStateReporter.ReportIdle was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		Repo           RepoID
		EnqueuedIngest bool
	}{
		Ctx:            ctx,
		Repo:           repo,
		EnqueuedIngest: enqueuedIngest,
	}
	mock.lockReportIdle.Lock()
	mock.calls.ReportIdle = append(mock.calls.ReportIdle, callInfo)
	mock.lockReportIdle.Unlock()
	return mock.ReportIdleFunc(ctx, repo, enqueuedIngest)
}

// ReportIdleCalls gets all the calls that were made to ReportIdle.
// Check the length with:
//
//	len(mockedSyncStateReporter.ReportIdleCalls())
func (mock *SyncStateReporterMock) ReportIdleCalls() []struct {
	Ctx            context.Context
	Repo           RepoID
	EnqueuedIngest bool
} {
	var calls []struct {
		Ctx            context.Context
		Repo           RepoID
		EnqueuedIngest bool
	}
	mock.lockReportIdle.RLock()
	calls = mock.calls.ReportIdle
	mock.lockReportIdle.RUnlock()
	return calls
}

// ReportSyncing calls ReportSyncingFunc.
func (mock *SyncStateReporterMock) ReportSyncing(ctx context.Context, repo RepoID) error {
	if mock.ReportSyncingFunc == nil {
		panic("SyncStateReporterMock.ReportSyncingFunc: method is nil but SyncStateReporter.ReportSyncing was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Repo RepoID
	}{
		Ctx:  ctx,
		Repo: repo,
	}
	mock.lockReportSyncing.Lock()
	mock.calls.ReportSyncing = append(mock.calls.ReportSyncing, callInfo)
	mock.lockReportSyncing.Unlock()
	return mock.ReportSyncingFunc(ctx, repo)
}

// ReportSyncingCalls gets all the calls that were made to ReportSyncing.
// Check the length with:
//
//	len(mockedSyncStateReporter.ReportSyncingCalls())
func (mock *SyncStateReporterMock) ReportSyncingCalls() []struct {
	Ctx  context.Context
	Repo RepoID
} {
	var calls []struct {
		Ctx  context.Context
		Repo RepoID
	}
	mock.lockReportSyncing.RLock()
	calls = mock.calls.ReportSyncing
	mock.lockReportSyncing.RUnlock()
	return calls
}

// Ensure, that repoNameListerMock does implement repoNameLister.
// If this is not the case, regenerate this file with moq.
var _ repoNameLister = &repoNameListerMock{}

// repoNameListerMock is a mock implementation of repoNameLister.
//
//	func TestSomethingThatUsesrepoNameLister(t *testing.T) {
//
//		// make and configure a mocked repoNameLister
//		mockedrepoNameLister := &repoNameListerMock{
//			ListAllRepoNamesFunc: func(ctx context.Context) ([]string, error) {
//				panic("mock out the ListAllRepoNames method")
//			},
//		}
//
//		// use mockedrepoNameLister in code that requires repoNameLister
//		// and then make assertions.
//
//	}
type repoNameListerMock struct {
	// ListAllRepoNamesFunc mocks the ListAllRepoNames method.
	ListAllRepoNamesFunc func(ctx context.Context) ([]string, error)

	// calls tracks calls to the methods.
	calls struct {
		// ListAllRepoNames holds details about calls to the ListAllRepoNames method.
		ListAllRepoNames []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockListAllRepoNames sync.RWMutex
}

// ListAllRepoNames calls ListAllRepoNamesFunc.
func (mock *repoNameListerMock) ListAllRepoNames(ctx context.Context) ([]string, error) {
	if mock.ListAllRepoNamesFunc == nil {
		panic("repoNameListerMock.ListAllRepoNamesFunc: method is nil but repoNameLister.ListAllRepoNames was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListAllRepoNames.Lock()
	mock.calls.ListAllRepoNames = append(mock.calls.ListAllRepoNames, callInfo)
	mock.lockListAllRepoNames.Unlock()
	return mock.ListAllRepoNamesFunc(ctx)
}

// ListAllRepoNamesCalls gets all the calls that were made to ListAllRepoNames.
// Check the length with:
//
//	len(mockedrepoNameLister.ListAllRepoNamesCalls())
func (mock *repoNameListerMock) ListAllRepoNamesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListAllRepoNames.RLock()
	calls = mock.calls.ListAllRepoNames
	mock.lockListAllRepoNames.RUnlock()
	return calls
}

// Ensure, that upstreamRefFetcherMock does implement upstreamRefFetcher.
// If this is not the case, regenerate this file with moq.
var _ upstreamRefFetcher = &upstreamRefFetcherMock{}

// upstreamRefFetcherMock is a mock implementation of upstreamRefFetcher.
//
//	func TestSomethingThatUsesupstreamRefFetcher(t *testing.T) {
//
//		// make and configure a mocked upstreamRefFetcher
//		mockedupstreamRefFetcher := &upstreamRefFetcherMock{
//			FetchFunc: func(ctx context.Context, host string, mirrorDir string, upstreamURL string, refspecs []string) ([]byte, error) {
//				panic("mock out the Fetch method")
//			},
//		}
//
//		// use mockedupstreamRefFetcher in code that requires upstreamRefFetcher
//		// and then make assertions.
//
//	}
type upstreamRefFetcherMock struct {
	// FetchFunc mocks the Fetch method.
	FetchFunc func(ctx context.Context, host string, mirrorDir string, upstreamURL string, refspecs []string) ([]byte, error)

	// calls tracks calls to the methods.
	calls struct {
		// Fetch holds details about calls to the Fetch method.
		Fetch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Host is the host argument value.
			Host string
			// MirrorDir is the mirrorDir argument value.
			MirrorDir string
			// UpstreamURL is the upstreamURL argument value.
			UpstreamURL string
			// Refspecs is the refspecs argument value.
			Refspecs []string
		}
	}
	lockFetch sync.RWMutex
}

// Fetch calls FetchFunc.
func (mock *upstreamRefFetcherMock) Fetch(ctx context.Context, host string, mirrorDir string, upstreamURL string, refspecs []string) ([]byte, error) {
	if mock.FetchFunc == nil {
		panic("upstreamRefFetcherMock.FetchFunc: method is nil but upstreamRefFetcher.Fetch was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Host        string
		MirrorDir   string
		UpstreamURL string
		Refspecs    []string
	}{
		Ctx:         ctx,
		Host:        host,
		MirrorDir:   mirrorDir,
		UpstreamURL: upstreamURL,
		Refspecs:    refspecs,
	}
	mock.lockFetch.Lock()
	mock.calls.Fetch = append(mock.calls.Fetch, callInfo)
	mock.lockFetch.Unlock()
	return mock.FetchFunc(ctx, host, mirrorDir, upstreamURL, refspecs)
}

// FetchCalls gets all the calls that were made to Fetch.
// Check the length with:
//
//	len(mockedupstreamRefFetcher.FetchCalls())
func (mock *upstreamRefFetcherMock) FetchCalls() []struct {
	Ctx         context.Context
	Host        string
	MirrorDir   string
	UpstreamURL string
	Refspecs    []string
} {
	var calls []struct {
		Ctx         context.Context
		Host        string
		MirrorDir   string
		UpstreamURL string
		Refspecs    []string
	}
	mock.lockFetch.RLock()
	calls = mock.calls.Fetch
	mock.lockFetch.RUnlock()
	return calls
}

// Ensure, that repoResolverMock does implement repoResolver.
// If this is not the case, regenerate this file with moq.
var _ repoResolver = &repoResolverMock{}

// repoResolverMock is a mock implementation of repoResolver.
//
//	func TestSomethingThatUsesrepoResolver(t *testing.T) {
//
//		// make and configure a mocked repoResolver
//		mockedrepoResolver := &repoResolverMock{
//			ResolveRepoFunc: func(ctx context.Context, repo RepoID) (string, string, []string, error) {
//				panic("mock out the ResolveRepo method")
//			},
//		}
//
//		// use mockedrepoResolver in code that requires repoResolver
//		// and then make assertions.
//
//	}
type repoResolverMock struct {
	// ResolveRepoFunc mocks the ResolveRepo method.
	ResolveRepoFunc func(ctx context.Context, repo RepoID) (string, string, []string, error)

	// calls tracks calls to the methods.
	calls struct {
		// ResolveRepo holds details about calls to the ResolveRepo method.
		ResolveRepo []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Repo is the repo argument value.
			Repo RepoID
		}
	}
	lockResolveRepo sync.RWMutex
}

// ResolveRepo calls ResolveRepoFunc.
func (mock *repoResolverMock) ResolveRepo(ctx context.Context, repo RepoID) (string, string, []string, error) {
	if mock.ResolveRepoFunc == nil {
		panic("repoResolverMock.ResolveRepoFunc: method is nil but repoResolver.ResolveRepo was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Repo RepoID
	}{
		Ctx:  ctx,
		Repo: repo,
	}
	mock.lockResolveRepo.Lock()
	mock.calls.ResolveRepo = append(mock.calls.ResolveRepo, callInfo)
	mock.lockResolveRepo.Unlock()
	return mock.ResolveRepoFunc(ctx, repo)
}

// ResolveRepoCalls gets all the calls that were made to ResolveRepo.
// Check the length with:
//
//	len(mockedrepoResolver.ResolveRepoCalls())
func (mock *repoResolverMock) ResolveRepoCalls() []struct {
	Ctx  context.Context
	Repo RepoID
} {
	var calls []struct {
		Ctx  context.Context
		Repo RepoID
	}
	mock.lockResolveRepo.RLock()
	calls = mock.calls.ResolveRepo
	mock.lockResolveRepo.RUnlock()
	return calls
}

// Ensure, that repoByNameLookupMock does implement repoByNameLookup.
// If this is not the case, regenerate this file with moq.
var _ repoByNameLookup = &repoByNameLookupMock{}

// repoByNameLookupMock is a mock implementation of repoByNameLookup.
//
//	func TestSomethingThatUsesrepoByNameLookup(t *testing.T) {
//
//		// make and configure a mocked repoByNameLookup
//		mockedrepoByNameLookup := &repoByNameLookupMock{
//			GetRepoByNameFunc: func(ctx context.Context, name string) (reposstore.Repo, error) {
//				panic("mock out the GetRepoByName method")
//			},
//		}
//
//		// use mockedrepoByNameLookup in code that requires repoByNameLookup
//		// and then make assertions.
//
//	}
type repoByNameLookupMock struct {
	// GetRepoByNameFunc mocks the GetRepoByName method.
	GetRepoByNameFunc func(ctx context.Context, name string) (reposstore.Repo, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetRepoByName holds details about calls to the GetRepoByName method.
		GetRepoByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
	}
	lockGetRepoByName sync.RWMutex
}

// GetRepoByName calls GetRepoByNameFunc.
func (mock *repoByNameLookupMock) GetRepoByName(ctx context.Context, name string) (reposstore.Repo, error) {
	if mock.GetRepoByNameFunc == nil {
		panic("repoByNameLookupMock.GetRepoByNameFunc: method is nil but repoByNameLookup.GetRepoByName was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockGetRepoByName.Lock()
	mock.calls.GetRepoByName = append(mock.calls.GetRepoByName, callInfo)
	mock.lockGetRepoByName.Unlock()
	return mock.GetRepoByNameFunc(ctx, name)
}

// GetRepoByNameCalls gets all the calls that were made to GetRepoByName.
// Check the length with:
//
//	len(mockedrepoByNameLookup.GetRepoByNameCalls())
func (mock *repoByNameLookupMock) GetRepoByNameCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockGetRepoByName.RLock()
	calls = mock.calls.GetRepoByName
	mock.lockGetRepoByName.RUnlock()
	return calls
}

// Ensure, that workBranchNameListerMock does implement workBranchNameLister.
// If this is not the case, regenerate this file with moq.
var _ workBranchNameLister = &workBranchNameListerMock{}

// workBranchNameListerMock is a mock implementation of workBranchNameLister.
//
//	func TestSomethingThatUsesworkBranchNameLister(t *testing.T) {
//
//		// make and configure a mocked workBranchNameLister
//		mockedworkBranchNameLister := &workBranchNameListerMock{
//			ListFunc: func(ctx context.Context, filter workbranchstore.ListFilter, limit int32, offset int32) ([]workbranchstore.WorkBranch, int64, error) {
//				panic("mock out the List method")
//			},
//		}
//
//		// use mockedworkBranchNameLister in code that requires workBranchNameLister
//		// and then make assertions.
//
//	}
type workBranchNameListerMock struct {
	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, filter workbranchstore.ListFilter, limit int32, offset int32) ([]workbranchstore.WorkBranch, int64, error)

	// calls tracks calls to the methods.
	calls struct {
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Filter is the filter argument value.
			Filter workbranchstore.ListFilter
			// Limit is the limit argument value.
			Limit int32
			// Offset is the offset argument value.
			Offset int32
		}
	}
	lockList sync.RWMutex
}

// List calls ListFunc.
func (mock *workBranchNameListerMock) List(ctx context.Context, filter workbranchstore.ListFilter, limit int32, offset int32) ([]workbranchstore.WorkBranch, int64, error) {
	if mock.ListFunc == nil {
		panic("workBranchNameListerMock.ListFunc: method is nil but workBranchNameLister.List was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Filter workbranchstore.ListFilter
		Limit  int32
		Offset int32
	}{
		Ctx:    ctx,
		Filter: filter,
		Limit:  limit,
		Offset: offset,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, filter, limit, offset)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedworkBranchNameLister.ListCalls())
func (mock *workBranchNameListerMock) ListCalls() []struct {
	Ctx    context.Context
	Filter workbranchstore.ListFilter
	Limit  int32
	Offset int32
} {
	var calls []struct {
		Ctx    context.Context
		Filter workbranchstore.ListFilter
		Limit  int32
		Offset int32
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Ensure, that targetBranchListerMock does implement targetBranchLister.
// If this is not the case, regenerate this file with moq.
var _ targetBranchLister = &targetBranchListerMock{}

// targetBranchListerMock is a mock implementation of targetBranchLister.
//
//	func TestSomethingThatUsestargetBranchLister(t *testing.T) {
//
//		// make and configure a mocked targetBranchLister
//		mockedtargetBranchLister := &targetBranchListerMock{
//			ListTargetBranchesFunc: func(ctx context.Context, repoID uuid.UUID) ([]reposstore.TargetBranch, error) {
//				panic("mock out the ListTargetBranches method")
//			},
//		}
//
//		// use mockedtargetBranchLister in code that requires targetBranchLister
//		// and then make assertions.
//
//	}
type targetBranchListerMock struct {
	// ListTargetBranchesFunc mocks the ListTargetBranches method.
	ListTargetBranchesFunc func(ctx context.Context, repoID uuid.UUID) ([]reposstore.TargetBranch, error)

	// calls tracks calls to the methods.
	calls struct {
		// ListTargetBranches holds details about calls to the ListTargetBranches method.
		ListTargetBranches []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RepoID is the repoID argument value.
			RepoID uuid.UUID
		}
	}
	lockListTargetBranches sync.RWMutex
}

// ListTargetBranches calls ListTargetBranchesFunc.
func (mock *targetBranchListerMock) ListTargetBranches(ctx context.Context, repoID uuid.UUID) ([]reposstore.TargetBranch, error) {
	if mock.ListTargetBranchesFunc == nil {
		panic("targetBranchListerMock.ListTargetBranchesFunc: method is nil but targetBranchLister.ListTargetBranches was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		RepoID uuid.UUID
	}{
		Ctx:    ctx,
		RepoID: repoID,
	}
	mock.lockListTargetBranches.Lock()
	mock.calls.ListTargetBranches = append(mock.calls.ListTargetBranches, callInfo)
	mock.lockListTargetBranches.Unlock()
	return mock.ListTargetBranchesFunc(ctx, repoID)
}

// ListTargetBranchesCalls gets all the calls that were made to ListTargetBranches.
// Check the length with:
//
//	len(mockedtargetBranchLister.ListTargetBranchesCalls())
func (mock *targetBranchListerMock) ListTargetBranchesCalls() []struct {
	Ctx    context.Context
	RepoID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		RepoID uuid.UUID
	}
	mock.lockListTargetBranches.RLock()
	calls = mock.calls.ListTargetBranches
	mock.lockListTargetBranches.RUnlock()
	return calls
}

// Ensure, that ingestedRefLookupMock does implement ingestedRefLookup.
// If this is not the case, regenerate this file with moq.
var _ ingestedRefLookup = &ingestedRefLookupMock{}

// ingestedRefLookupMock is a mock implementation of ingestedRefLookup.
//
//	func TestSomethingThatUsesingestedRefLookup(t *testing.T) {
//
//		// make and configure a mocked ingestedRefLookup
//		mockedingestedRefLookup := &ingestedRefLookupMock{
//			IngestedRefFunc: func(ctx context.Context, repoID uuid.UUID, branch string) (reposstore.IngestedRef, error) {
//				panic("mock out the IngestedRef method")
//			},
//		}
//
//		// use mockedingestedRefLookup in code that requires ingestedRefLookup
//		// and then make assertions.
//
//	}
type ingestedRefLookupMock struct {
	// IngestedRefFunc mocks the IngestedRef method.
	IngestedRefFunc func(ctx context.Context, repoID uuid.UUID, branch string) (reposstore.IngestedRef, error)

	// calls tracks calls to the methods.
	calls struct {
		// IngestedRef holds details about calls to the IngestedRef method.
		IngestedRef []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RepoID is the repoID argument value.
			RepoID uuid.UUID
			// Branch is the branch argument value.
			Branch string
		}
	}
	lockIngestedRef sync.RWMutex
}

// IngestedRef calls IngestedRefFunc.
func (mock *ingestedRefLookupMock) IngestedRef(ctx context.Context, repoID uuid.UUID, branch string) (reposstore.IngestedRef, error) {
	if mock.IngestedRefFunc == nil {
		panic("ingestedRefLookupMock.IngestedRefFunc: method is nil but ingestedRefLookup.IngestedRef was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		RepoID uuid.UUID
		Branch string
	}{
		Ctx:    ctx,
		RepoID: repoID,
		Branch: branch,
	}
	mock.lockIngestedRef.Lock()
	mock.calls.IngestedRef = append(mock.calls.IngestedRef, callInfo)
	mock.lockIngestedRef.Unlock()
	return mock.IngestedRefFunc(ctx, repoID, branch)
}

// IngestedRefCalls gets all the calls that were made to IngestedRef.
// Check the length with:
//
//	len(mockedingestedRefLookup.IngestedRefCalls())
func (mock *ingestedRefLookupMock) IngestedRefCalls() []struct {
	Ctx    context.Context
	RepoID uuid.UUID
	Branch string
} {
	var calls []struct {
		Ctx    context.Context
		RepoID uuid.UUID
		Branch string
	}
	mock.lockIngestedRef.RLock()
	calls = mock.calls.IngestedRef
	mock.lockIngestedRef.RUnlock()
	return calls
}

// Ensure, that ingestJobEnqueuerMock does implement ingestJobEnqueuer.
// If this is not the case, regenerate this file with moq.
var _ ingestJobEnqueuer = &ingestJobEnqueuerMock{}

// ingestJobEnqueuerMock is a mock implementation of ingestJobEnqueuer.
//
//	func TestSomethingThatUsesingestJobEnqueuer(t *testing.T) {
//
//		// make and configure a mocked ingestJobEnqueuer
//		mockedingestJobEnqueuer := &ingestJobEnqueuerMock{
//			EnqueueFunc: func(ctx context.Context, repoID uuid.UUID, targetBranch string, kind ingest.Kind) error {
//				panic("mock out the Enqueue method")
//			},
//		}
//
//		// use mockedingestJobEnqueuer in code that requires ingestJobEnqueuer
//		// and then make assertions.
//
//	}
type ingestJobEnqueuerMock struct {
	// EnqueueFunc mocks the Enqueue method.
	EnqueueFunc func(ctx context.Context, repoID uuid.UUID, targetBranch string, kind ingest.Kind) error

	// calls tracks calls to the methods.
	calls struct {
		// Enqueue holds details about calls to the Enqueue method.
		Enqueue []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RepoID is the repoID argument value.
			RepoID uuid.UUID
			// TargetBranch is the targetBranch argument value.
			TargetBranch string
			// Kind is the kind argument value.
			Kind ingest.Kind
		}
	}
	lockEnqueue sync.RWMutex
}

// Enqueue calls EnqueueFunc.
func (mock *ingestJobEnqueuerMock) Enqueue(ctx context.Context, repoID uuid.UUID, targetBranch string, kind ingest.Kind) error {
	if mock.EnqueueFunc == nil {
		panic("ingestJobEnqueuerMock.EnqueueFunc: method is nil but ingestJobEnqueuer.Enqueue was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		RepoID       uuid.UUID
		TargetBranch string
		Kind         ingest.Kind
	}{
		Ctx:          ctx,
		RepoID:       repoID,
		TargetBranch: targetBranch,
		Kind:         kind,
	}
	mock.lockEnqueue.Lock()
	mock.calls.Enqueue = append(mock.calls.Enqueue, callInfo)
	mock.lockEnqueue.Unlock()
	return mock.EnqueueFunc(ctx, repoID, targetBranch, kind)
}

// EnqueueCalls gets all the calls that were made to Enqueue.
// Check the length with:
//
//	len(mockedingestJobEnqueuer.EnqueueCalls())
func (mock *ingestJobEnqueuerMock) EnqueueCalls() []struct {
	Ctx          context.Context
	RepoID       uuid.UUID
	TargetBranch string
	Kind         ingest.Kind
} {
	var calls []struct {
		Ctx          context.Context
		RepoID       uuid.UUID
		TargetBranch string
		Kind         ingest.Kind
	}
	mock.lockEnqueue.RLock()
	calls = mock.calls.Enqueue
	mock.lockEnqueue.RUnlock()
	return calls
}

// Ensure, that mergeTreeRunnerMock does implement mergeTreeRunner.
// If this is not the case, regenerate this file with moq.
var _ mergeTreeRunner = &mergeTreeRunnerMock{}

// mergeTreeRunnerMock is a mock implementation of mergeTreeRunner.
//
//	func TestSomethingThatUsesmergeTreeRunner(t *testing.T) {
//
//		// make and configure a mocked mergeTreeRunner
//		mockedmergeTreeRunner := &mergeTreeRunnerMock{
//			MergeTreeFunc: func(ctx context.Context, mirrorDir string, ours string, theirs string) (bool, error) {
//				panic("mock out the MergeTree method")
//			},
//		}
//
//		// use mockedmergeTreeRunner in code that requires mergeTreeRunner
//		// and then make assertions.
//
//	}
type mergeTreeRunnerMock struct {
	// MergeTreeFunc mocks the MergeTree method.
	MergeTreeFunc func(ctx context.Context, mirrorDir string, ours string, theirs string) (bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// MergeTree holds details about calls to the MergeTree method.
		MergeTree []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// MirrorDir is the mirrorDir argument value.
			MirrorDir string
			// Ours is the ours argument value.
			Ours string
			// Theirs is the theirs argument value.
			Theirs string
		}
	}
	lockMergeTree sync.RWMutex
}

// MergeTree calls MergeTreeFunc.
func (mock *mergeTreeRunnerMock) MergeTree(ctx context.Context, mirrorDir string, ours string, theirs string) (bool, error) {
	if mock.MergeTreeFunc == nil {
		panic("mergeTreeRunnerMock.MergeTreeFunc: method is nil but mergeTreeRunner.MergeTree was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		MirrorDir string
		Ours      string
		Theirs    string
	}{
		Ctx:       ctx,
		MirrorDir: mirrorDir,
		Ours:      ours,
		Theirs:    theirs,
	}
	mock.lockMergeTree.Lock()
	mock.calls.MergeTree = append(mock.calls.MergeTree, callInfo)
	mock.lockMergeTree.Unlock()
	return mock.MergeTreeFunc(ctx, mirrorDir, ours, theirs)
}

// MergeTreeCalls gets all the calls that were made to MergeTree.
// Check the length with:
//
//	len(mockedmergeTreeRunner.MergeTreeCalls())
func (mock *mergeTreeRunnerMock) MergeTreeCalls() []struct {
	Ctx       context.Context
	MirrorDir string
	Ours      string
	Theirs    string
} {
	var calls []struct {
		Ctx       context.Context
		MirrorDir string
		Ours      string
		Theirs    string
	}
	mock.lockMergeTree.RLock()
	calls = mock.calls.MergeTree
	mock.lockMergeTree.RUnlock()
	return calls
}

// Ensure, that workBranchConflictMarkerMock does implement workBranchConflictMarker.
// If this is not the case, regenerate this file with moq.
var _ workBranchConflictMarker = &workBranchConflictMarkerMock{}

// workBranchConflictMarkerMock is a mock implementation of workBranchConflictMarker.
//
//	func TestSomethingThatUsesworkBranchConflictMarker(t *testing.T) {
//
//		// make and configure a mocked workBranchConflictMarker
//		mockedworkBranchConflictMarker := &workBranchConflictMarkerMock{
//			MarkConflictedFunc: func(ctx context.Context, id uuid.UUID) (workbranchstore.WorkBranch, error) {
//				panic("mock out the MarkConflicted method")
//			},
//		}
//
//		// use mockedworkBranchConflictMarker in code that requires workBranchConflictMarker
//		// and then make assertions.
//
//	}
type workBranchConflictMarkerMock struct {
	// MarkConflictedFunc mocks the MarkConflicted method.
	MarkConflictedFunc func(ctx context.Context, id uuid.UUID) (workbranchstore.WorkBranch, error)

	// calls tracks calls to the methods.
	calls struct {
		// MarkConflicted holds details about calls to the MarkConflicted method.
		MarkConflicted []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
	}
	lockMarkConflicted sync.RWMutex
}

// MarkConflicted calls MarkConflictedFunc.
func (mock *workBranchConflictMarkerMock) MarkConflicted(ctx context.Context, id uuid.UUID) (workbranchstore.WorkBranch, error) {
	if mock.MarkConflictedFunc == nil {
		panic("workBranchConflictMarkerMock.MarkConflictedFunc: method is nil but workBranchConflictMarker.MarkConflicted was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockMarkConflicted.Lock()
	mock.calls.MarkConflicted = append(mock.calls.MarkConflicted, callInfo)
	mock.lockMarkConflicted.Unlock()
	return mock.MarkConflictedFunc(ctx, id)
}

// MarkConflictedCalls gets all the calls that were made to MarkConflicted.
// Check the length with:
//
//	len(mockedworkBranchConflictMarker.MarkConflictedCalls())
func (mock *workBranchConflictMarkerMock) MarkConflictedCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockMarkConflicted.RLock()
	calls = mock.calls.MarkConflicted
	mock.lockMarkConflicted.RUnlock()
	return calls
}

// Ensure, that workBranchTerminatorMock does implement workBranchTerminator.
// If this is not the case, regenerate this file with moq.
var _ workBranchTerminator = &workBranchTerminatorMock{}

// workBranchTerminatorMock is a mock implementation of workBranchTerminator.
//
//	func TestSomethingThatUsesworkBranchTerminator(t *testing.T) {
//
//		// make and configure a mocked workBranchTerminator
//		mockedworkBranchTerminator := &workBranchTerminatorMock{
//			CloseFunc: func(ctx context.Context, id uuid.UUID, reason string) (workbranchstore.WorkBranch, error) {
//				panic("mock out the Close method")
//			},
//			CompleteFunc: func(ctx context.Context, id uuid.UUID) (workbranchstore.WorkBranch, error) {
//				panic("mock out the Complete method")
//			},
//		}
//
//		// use mockedworkBranchTerminator in code that requires workBranchTerminator
//		// and then make assertions.
//
//	}
type workBranchTerminatorMock struct {
	// CloseFunc mocks the Close method.
	CloseFunc func(ctx context.Context, id uuid.UUID, reason string) (workbranchstore.WorkBranch, error)

	// CompleteFunc mocks the Complete method.
	CompleteFunc func(ctx context.Context, id uuid.UUID) (workbranchstore.WorkBranch, error)

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
			// Reason is the reason argument value.
			Reason string
		}
		// Complete holds details about calls to the Complete method.
		Complete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
	}
	lockClose    sync.RWMutex
	lockComplete sync.RWMutex
}

// Close calls CloseFunc.
func (mock *workBranchTerminatorMock) Close(ctx context.Context, id uuid.UUID, reason string) (workbranchstore.WorkBranch, error) {
	if mock.CloseFunc == nil {
		panic("workBranchTerminatorMock.CloseFunc: method is nil but workBranchTerminator.Close was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		ID     uuid.UUID
		Reason string
	}{
		Ctx:    ctx,
		ID:     id,
		Reason: reason,
	}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc(ctx, id, reason)
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedworkBranchTerminator.CloseCalls())
func (mock *workBranchTerminatorMock) CloseCalls() []struct {
	Ctx    context.Context
	ID     uuid.UUID
	Reason string
} {
	var calls []struct {
		Ctx    context.Context
		ID     uuid.UUID
		Reason string
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// Complete calls CompleteFunc.
func (mock *workBranchTerminatorMock) Complete(ctx context.Context, id uuid.UUID) (workbranchstore.WorkBranch, error) {
	if mock.CompleteFunc == nil {
		panic("workBranchTerminatorMock.CompleteFunc: method is nil but workBranchTerminator.Complete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockComplete.Lock()
	mock.calls.Complete = append(mock.calls.Complete, callInfo)
	mock.lockComplete.Unlock()
	return mock.CompleteFunc(ctx, id)
}

// CompleteCalls gets all the calls that were made to Complete.
// Check the length with:
//
//	len(mockedworkBranchTerminator.CompleteCalls())
func (mock *workBranchTerminatorMock) CompleteCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockComplete.RLock()
	calls = mock.calls.Complete
	mock.lockComplete.RUnlock()
	return calls
}

// Ensure, that pullRequestTrackerMock does implement pullRequestTracker.
// If this is not the case, regenerate this file with moq.
var _ pullRequestTracker = &pullRequestTrackerMock{}

// pullRequestTrackerMock is a mock implementation of pullRequestTracker.
//
//	func TestSomethingThatUsespullRequestTracker(t *testing.T) {
//
//		// make and configure a mocked pullRequestTracker
//		mockedpullRequestTracker := &pullRequestTrackerMock{
//			ClosePRFunc: func(ctx context.Context, repo string, prNumber int) error {
//				panic("mock out the ClosePR method")
//			},
//			GetPRStateFunc: func(ctx context.Context, repo string, prNumber int) (string, error) {
//				panic("mock out the GetPRState method")
//			},
//		}
//
//		// use mockedpullRequestTracker in code that requires pullRequestTracker
//		// and then make assertions.
//
//	}
type pullRequestTrackerMock struct {
	// ClosePRFunc mocks the ClosePR method.
	ClosePRFunc func(ctx context.Context, repo string, prNumber int) error

	// GetPRStateFunc mocks the GetPRState method.
	GetPRStateFunc func(ctx context.Context, repo string, prNumber int) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// ClosePR holds details about calls to the ClosePR method.
		ClosePR []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Repo is the repo argument value.
			Repo string
			// PrNumber is the prNumber argument value.
			PrNumber int
		}
		// GetPRState holds details about calls to the GetPRState method.
		GetPRState []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Repo is the repo argument value.
			Repo string
			// PrNumber is the prNumber argument value.
			PrNumber int
		}
	}
	lockClosePR    sync.RWMutex
	lockGetPRState sync.RWMutex
}

// ClosePR calls ClosePRFunc.
func (mock *pullRequestTrackerMock) ClosePR(ctx context.Context, repo string, prNumber int) error {
	if mock.ClosePRFunc == nil {
		panic("pullRequestTrackerMock.ClosePRFunc: method is nil but pullRequestTracker.ClosePR was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Repo     string
		PrNumber int
	}{
		Ctx:      ctx,
		Repo:     repo,
		PrNumber: prNumber,
	}
	mock.lockClosePR.Lock()
	mock.calls.ClosePR = append(mock.calls.ClosePR, callInfo)
	mock.lockClosePR.Unlock()
	return mock.ClosePRFunc(ctx, repo, prNumber)
}

// ClosePRCalls gets all the calls that were made to ClosePR.
// Check the length with:
//
//	len(mockedpullRequestTracker.ClosePRCalls())
func (mock *pullRequestTrackerMock) ClosePRCalls() []struct {
	Ctx      context.Context
	Repo     string
	PrNumber int
} {
	var calls []struct {
		Ctx      context.Context
		Repo     string
		PrNumber int
	}
	mock.lockClosePR.RLock()
	calls = mock.calls.ClosePR
	mock.lockClosePR.RUnlock()
	return calls
}

// GetPRState calls GetPRStateFunc.
func (mock *pullRequestTrackerMock) GetPRState(ctx context.Context, repo string, prNumber int) (string, error) {
	if mock.GetPRStateFunc == nil {
		panic("pullRequestTrackerMock.GetPRStateFunc: method is nil but pullRequestTracker.GetPRState was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Repo     string
		PrNumber int
	}{
		Ctx:      ctx,
		Repo:     repo,
		PrNumber: prNumber,
	}
	mock.lockGetPRState.Lock()
	mock.calls.GetPRState = append(mock.calls.GetPRState, callInfo)
	mock.lockGetPRState.Unlock()
	return mock.GetPRStateFunc(ctx, repo, prNumber)
}

// GetPRStateCalls gets all the calls that were made to GetPRState.
// Check the length with:
//
//	len(mockedpullRequestTracker.GetPRStateCalls())
func (mock *pullRequestTrackerMock) GetPRStateCalls() []struct {
	Ctx      context.Context
	Repo     string
	PrNumber int
} {
	var calls []struct {
		Ctx      context.Context
		Repo     string
		PrNumber int
	}
	mock.lockGetPRState.RLock()
	calls = mock.calls.GetPRState
	mock.lockGetPRState.RUnlock()
	return calls
}

// Ensure, that upstreamRefDeleterMock does implement upstreamRefDeleter.
// If this is not the case, regenerate this file with moq.
var _ upstreamRefDeleter = &upstreamRefDeleterMock{}

// upstreamRefDeleterMock is a mock implementation of upstreamRefDeleter.
//
//	func TestSomethingThatUsesupstreamRefDeleter(t *testing.T) {
//
//		// make and configure a mocked upstreamRefDeleter
//		mockedupstreamRefDeleter := &upstreamRefDeleterMock{
//			DeleteRemoteRefFunc: func(ctx context.Context, host string, mirrorDir string, upstreamURL string, ref string) ([]byte, error) {
//				panic("mock out the DeleteRemoteRef method")
//			},
//		}
//
//		// use mockedupstreamRefDeleter in code that requires upstreamRefDeleter
//		// and then make assertions.
//
//	}
type upstreamRefDeleterMock struct {
	// DeleteRemoteRefFunc mocks the DeleteRemoteRef method.
	DeleteRemoteRefFunc func(ctx context.Context, host string, mirrorDir string, upstreamURL string, ref string) ([]byte, error)

	// calls tracks calls to the methods.
	calls struct {
		// DeleteRemoteRef holds details about calls to the DeleteRemoteRef method.
		DeleteRemoteRef []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Host is the host argument value.
			Host string
			// MirrorDir is the mirrorDir argument value.
			MirrorDir string
			// UpstreamURL is the upstreamURL argument value.
			UpstreamURL string
			// Ref is the ref argument value.
			Ref string
		}
	}
	lockDeleteRemoteRef sync.RWMutex
}

// DeleteRemoteRef calls DeleteRemoteRefFunc.
func (mock *upstreamRefDeleterMock) DeleteRemoteRef(ctx context.Context, host string, mirrorDir string, upstreamURL string, ref string) ([]byte, error) {
	if mock.DeleteRemoteRefFunc == nil {
		panic("upstreamRefDeleterMock.DeleteRemoteRefFunc: method is nil but upstreamRefDeleter.DeleteRemoteRef was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Host        string
		MirrorDir   string
		UpstreamURL string
		Ref         string
	}{
		Ctx:         ctx,
		Host:        host,
		MirrorDir:   mirrorDir,
		UpstreamURL: upstreamURL,
		Ref:         ref,
	}
	mock.lockDeleteRemoteRef.Lock()
	mock.calls.DeleteRemoteRef = append(mock.calls.DeleteRemoteRef, callInfo)
	mock.lockDeleteRemoteRef.Unlock()
	return mock.DeleteRemoteRefFunc(ctx, host, mirrorDir, upstreamURL, ref)
}

// DeleteRemoteRefCalls gets all the calls that were made to DeleteRemoteRef.
// Check the length with:
//
//	len(mockedupstreamRefDeleter.DeleteRemoteRefCalls())
func (mock *upstreamRefDeleterMock) DeleteRemoteRefCalls() []struct {
	Ctx         context.Context
	Host        string
	MirrorDir   string
	UpstreamURL string
	Ref         string
} {
	var calls []struct {
		Ctx         context.Context
		Host        string
		MirrorDir   string
		UpstreamURL string
		Ref         string
	}
	mock.lockDeleteRemoteRef.RLock()
	calls = mock.calls.DeleteRemoteRef
	mock.lockDeleteRemoteRef.RUnlock()
	return calls
}

// Ensure, that upstreamRefPusherMock does implement upstreamRefPusher.
// If this is not the case, regenerate this file with moq.
var _ upstreamRefPusher = &upstreamRefPusherMock{}

// upstreamRefPusherMock is a mock implementation of upstreamRefPusher.
//
//	func TestSomethingThatUsesupstreamRefPusher(t *testing.T) {
//
//		// make and configure a mocked upstreamRefPusher
//		mockedupstreamRefPusher := &upstreamRefPusherMock{
//			PushFunc: func(ctx context.Context, host string, mirrorDir string, upstreamURL string, refspec string) ([]byte, error) {
//				panic("mock out the Push method")
//			},
//		}
//
//		// use mockedupstreamRefPusher in code that requires upstreamRefPusher
//		// and then make assertions.
//
//	}
type upstreamRefPusherMock struct {
	// PushFunc mocks the Push method.
	PushFunc func(ctx context.Context, host string, mirrorDir string, upstreamURL string, refspec string) ([]byte, error)

	// calls tracks calls to the methods.
	calls struct {
		// Push holds details about calls to the Push method.
		Push []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Host is the host argument value.
			Host string
			// MirrorDir is the mirrorDir argument value.
			MirrorDir string
			// UpstreamURL is the upstreamURL argument value.
			UpstreamURL string
			// Refspec is the refspec argument value.
			Refspec string
		}
	}
	lockPush sync.RWMutex
}

// Push calls PushFunc.
func (mock *upstreamRefPusherMock) Push(ctx context.Context, host string, mirrorDir string, upstreamURL string, refspec string) ([]byte, error) {
	if mock.PushFunc == nil {
		panic("upstreamRefPusherMock.PushFunc: method is nil but upstreamRefPusher.Push was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Host        string
		MirrorDir   string
		UpstreamURL string
		Refspec     string
	}{
		Ctx:         ctx,
		Host:        host,
		MirrorDir:   mirrorDir,
		UpstreamURL: upstreamURL,
		Refspec:     refspec,
	}
	mock.lockPush.Lock()
	mock.calls.Push = append(mock.calls.Push, callInfo)
	mock.lockPush.Unlock()
	return mock.PushFunc(ctx, host, mirrorDir, upstreamURL, refspec)
}

// PushCalls gets all the calls that were made to Push.
// Check the length with:
//
//	len(mockedupstreamRefPusher.PushCalls())
func (mock *upstreamRefPusherMock) PushCalls() []struct {
	Ctx         context.Context
	Host        string
	MirrorDir   string
	UpstreamURL string
	Refspec     string
} {
	var calls []struct {
		Ctx         context.Context
		Host        string
		MirrorDir   string
		UpstreamURL string
		Refspec     string
	}
	mock.lockPush.RLock()
	calls = mock.calls.Push
	mock.lockPush.RUnlock()
	return calls
}

// Ensure, that workBranchByNameLookupMock does implement workBranchByNameLookup.
// If this is not the case, regenerate this file with moq.
var _ workBranchByNameLookup = &workBranchByNameLookupMock{}

// workBranchByNameLookupMock is a mock implementation of workBranchByNameLookup.
//
//	func TestSomethingThatUsesworkBranchByNameLookup(t *testing.T) {
//
//		// make and configure a mocked workBranchByNameLookup
//		mockedworkBranchByNameLookup := &workBranchByNameLookupMock{
//			GetByNameFunc: func(ctx context.Context, repoID uuid.UUID, name string) (workbranchstore.WorkBranch, error) {
//				panic("mock out the GetByName method")
//			},
//		}
//
//		// use mockedworkBranchByNameLookup in code that requires workBranchByNameLookup
//		// and then make assertions.
//
//	}
type workBranchByNameLookupMock struct {
	// GetByNameFunc mocks the GetByName method.
	GetByNameFunc func(ctx context.Context, repoID uuid.UUID, name string) (workbranchstore.WorkBranch, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetByName holds details about calls to the GetByName method.
		GetByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RepoID is the repoID argument value.
			RepoID uuid.UUID
			// Name is the name argument value.
			Name string
		}
	}
	lockGetByName sync.RWMutex
}

// GetByName calls GetByNameFunc.
func (mock *workBranchByNameLookupMock) GetByName(ctx context.Context, repoID uuid.UUID, name string) (workbranchstore.WorkBranch, error) {
	if mock.GetByNameFunc == nil {
		panic("workBranchByNameLookupMock.GetByNameFunc: method is nil but workBranchByNameLookup.GetByName was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		RepoID uuid.UUID
		Name   string
	}{
		Ctx:    ctx,
		RepoID: repoID,
		Name:   name,
	}
	mock.lockGetByName.Lock()
	mock.calls.GetByName = append(mock.calls.GetByName, callInfo)
	mock.lockGetByName.Unlock()
	return mock.GetByNameFunc(ctx, repoID, name)
}

// GetByNameCalls gets all the calls that were made to GetByName.
// Check the length with:
//
//	len(mockedworkBranchByNameLookup.GetByNameCalls())
func (mock *workBranchByNameLookupMock) GetByNameCalls() []struct {
	Ctx    context.Context
	RepoID uuid.UUID
	Name   string
} {
	var calls []struct {
		Ctx    context.Context
		RepoID uuid.UUID
		Name   string
	}
	mock.lockGetByName.RLock()
	calls = mock.calls.GetByName
	mock.lockGetByName.RUnlock()
	return calls
}

// Ensure, that workBranchPRRecorderMock does implement workBranchPRRecorder.
// If this is not the case, regenerate this file with moq.
var _ workBranchPRRecorder = &workBranchPRRecorderMock{}

// workBranchPRRecorderMock is a mock implementation of workBranchPRRecorder.
//
//	func TestSomethingThatUsesworkBranchPRRecorder(t *testing.T) {
//
//		// make and configure a mocked workBranchPRRecorder
//		mockedworkBranchPRRecorder := &workBranchPRRecorderMock{
//			RecordUpstreamPRFunc: func(ctx context.Context, id uuid.UUID, prURL string, prNumber int32) (workbranchstore.WorkBranch, error) {
//				panic("mock out the RecordUpstreamPR method")
//			},
//		}
//
//		// use mockedworkBranchPRRecorder in code that requires workBranchPRRecorder
//		// and then make assertions.
//
//	}
type workBranchPRRecorderMock struct {
	// RecordUpstreamPRFunc mocks the RecordUpstreamPR method.
	RecordUpstreamPRFunc func(ctx context.Context, id uuid.UUID, prURL string, prNumber int32) (workbranchstore.WorkBranch, error)

	// calls tracks calls to the methods.
	calls struct {
		// RecordUpstreamPR holds details about calls to the RecordUpstreamPR method.
		RecordUpstreamPR []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
			// PrURL is the prURL argument value.
			PrURL string
			// PrNumber is the prNumber argument value.
			PrNumber int32
		}
	}
	lockRecordUpstreamPR sync.RWMutex
}

// RecordUpstreamPR calls RecordUpstreamPRFunc.
func (mock *workBranchPRRecorderMock) RecordUpstreamPR(ctx context.Context, id uuid.UUID, prURL string, prNumber int32) (workbranchstore.WorkBranch, error) {
	if mock.RecordUpstreamPRFunc == nil {
		panic("workBranchPRRecorderMock.RecordUpstreamPRFunc: method is nil but workBranchPRRecorder.RecordUpstreamPR was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		ID       uuid.UUID
		PrURL    string
		PrNumber int32
	}{
		Ctx:      ctx,
		ID:       id,
		PrURL:    prURL,
		PrNumber: prNumber,
	}
	mock.lockRecordUpstreamPR.Lock()
	mock.calls.RecordUpstreamPR = append(mock.calls.RecordUpstreamPR, callInfo)
	mock.lockRecordUpstreamPR.Unlock()
	return mock.RecordUpstreamPRFunc(ctx, id, prURL, prNumber)
}

// RecordUpstreamPRCalls gets all the calls that were made to RecordUpstreamPR.
// Check the length with:
//
//	len(mockedworkBranchPRRecorder.RecordUpstreamPRCalls())
func (mock *workBranchPRRecorderMock) RecordUpstreamPRCalls() []struct {
	Ctx      context.Context
	ID       uuid.UUID
	PrURL    string
	PrNumber int32
} {
	var calls []struct {
		Ctx      context.Context
		ID       uuid.UUID
		PrURL    string
		PrNumber int32
	}
	mock.lockRecordUpstreamPR.RLock()
	calls = mock.calls.RecordUpstreamPR
	mock.lockRecordUpstreamPR.RUnlock()
	return calls
}

// Ensure, that pullRequestOpenerMock does implement pullRequestOpener.
// If this is not the case, regenerate this file with moq.
var _ pullRequestOpener = &pullRequestOpenerMock{}

// pullRequestOpenerMock is a mock implementation of pullRequestOpener.
//
//	func TestSomethingThatUsespullRequestOpener(t *testing.T) {
//
//		// make and configure a mocked pullRequestOpener
//		mockedpullRequestOpener := &pullRequestOpenerMock{
//			CreatePRFunc: func(ctx context.Context, repo string, headBranch string, targetBranch string, title string, description string) (string, int, error) {
//				panic("mock out the CreatePR method")
//			},
//			FindOpenPRFunc: func(ctx context.Context, repo string, headBranch string, targetBranch string) (string, int, bool, error) {
//				panic("mock out the FindOpenPR method")
//			},
//		}
//
//		// use mockedpullRequestOpener in code that requires pullRequestOpener
//		// and then make assertions.
//
//	}
type pullRequestOpenerMock struct {
	// CreatePRFunc mocks the CreatePR method.
	CreatePRFunc func(ctx context.Context, repo string, headBranch string, targetBranch string, title string, description string) (string, int, error)

	// FindOpenPRFunc mocks the FindOpenPR method.
	FindOpenPRFunc func(ctx context.Context, repo string, headBranch string, targetBranch string) (string, int, bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreatePR holds details about calls to the CreatePR method.
		CreatePR []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Repo is the repo argument value.
			Repo string
			// HeadBranch is the headBranch argument value.
			HeadBranch string
			// TargetBranch is the targetBranch argument value.
			TargetBranch string
			// Title is the title argument value.
			Title string
			// Description is the description argument value.
			Description string
		}
		// FindOpenPR holds details about calls to the FindOpenPR method.
		FindOpenPR []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Repo is the repo argument value.
			Repo string
			// HeadBranch is the headBranch argument value.
			HeadBranch string
			// TargetBranch is the targetBranch argument value.
			TargetBranch string
		}
	}
	lockCreatePR   sync.RWMutex
	lockFindOpenPR sync.RWMutex
}

// CreatePR calls CreatePRFunc.
func (mock *pullRequestOpenerMock) CreatePR(ctx context.Context, repo string, headBranch string, targetBranch string, title string, description string) (string, int, error) {
	if mock.CreatePRFunc == nil {
		panic("pullRequestOpenerMock.CreatePRFunc: method is nil but pullRequestOpener.CreatePR was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		Repo         string
		HeadBranch   string
		TargetBranch string
		Title        string
		Description  string
	}{
		Ctx:          ctx,
		Repo:         repo,
		HeadBranch:   headBranch,
		TargetBranch: targetBranch,
		Title:        title,
		Description:  description,
	}
	mock.lockCreatePR.Lock()
	mock.calls.CreatePR = append(mock.calls.CreatePR, callInfo)
	mock.lockCreatePR.Unlock()
	return mock.CreatePRFunc(ctx, repo, headBranch, targetBranch, title, description)
}

// CreatePRCalls gets all the calls that were made to CreatePR.
// Check the length with:
//
//	len(mockedpullRequestOpener.CreatePRCalls())
func (mock *pullRequestOpenerMock) CreatePRCalls() []struct {
	Ctx          context.Context
	Repo         string
	HeadBranch   string
	TargetBranch string
	Title        string
	Description  string
} {
	var calls []struct {
		Ctx          context.Context
		Repo         string
		HeadBranch   string
		TargetBranch string
		Title        string
		Description  string
	}
	mock.lockCreatePR.RLock()
	calls = mock.calls.CreatePR
	mock.lockCreatePR.RUnlock()
	return calls
}

// FindOpenPR calls FindOpenPRFunc.
func (mock *pullRequestOpenerMock) FindOpenPR(ctx context.Context, repo string, headBranch string, targetBranch string) (string, int, bool, error) {
	if mock.FindOpenPRFunc == nil {
		panic("pullRequestOpenerMock.FindOpenPRFunc: method is nil but pullRequestOpener.FindOpenPR was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		Repo         string
		HeadBranch   string
		TargetBranch string
	}{
		Ctx:          ctx,
		Repo:         repo,
		HeadBranch:   headBranch,
		TargetBranch: targetBranch,
	}
	mock.lockFindOpenPR.Lock()
	mock.calls.FindOpenPR = append(mock.calls.FindOpenPR, callInfo)
	mock.lockFindOpenPR.Unlock()
	return mock.FindOpenPRFunc(ctx, repo, headBranch, targetBranch)
}

// FindOpenPRCalls gets all the calls that were made to FindOpenPR.
// Check the length with:
//
//	len(mockedpullRequestOpener.FindOpenPRCalls())
func (mock *pullRequestOpenerMock) FindOpenPRCalls() []struct {
	Ctx          context.Context
	Repo         string
	HeadBranch   string
	TargetBranch string
} {
	var calls []struct {
		Ctx          context.Context
		Repo         string
		HeadBranch   string
		TargetBranch string
	}
	mock.lockFindOpenPR.RLock()
	calls = mock.calls.FindOpenPR
	mock.lockFindOpenPR.RUnlock()
	return calls
}
