-- Reverses 0010_chunk_rejections.up.sql.
--
-- THIS DOWN WAS FIRST WRITTEN AS A DELIBERATE NO-OP, following 0006 and
-- 0009, and that was WRONG. It is recorded here because the reasoning is
-- easy to repeat: those two protect operator-written text that a
-- destructive down would silently discard, and this ledger is likewise not
-- re-derivable (see below), so the same shape looked right.
--
-- It is not, and the reason is structural rather than a matter of taste.
-- chunk_rejections carries `repo_id uuid REFERENCES repos (id)`, and
-- golang-migrate applies downs in REVERSE order, so this file runs before
-- 0001_init.down.sql -- which drops `repos` with a plain DROP TABLE and no
-- CASCADE. Leaving this table in place therefore makes a full rollback
-- fail outright:
--
--   ERROR: cannot drop table repos because other objects depend on it
--   (SQLSTATE 2BP01), constraint chunk_rejections_repo_id_fkey ...
--
-- Not hypothetical, and not caught by reading: this file was a no-op on
-- the first push and internal/db/migrations'
-- TestMigrateAgainstRealPostgres and TestCodeIntelMigrationAgainstReal
-- Postgres both went red on exactly that error. Any future migration that
-- adds a foreign key into 0001's tables inherits the same rule -- its down
-- MUST drop its own table.
--
-- WHAT ROLLING BACK PAST 0010 ACTUALLY COSTS, which is the part the
-- original no-op was trying (in the wrong way) to protect. Unlike every
-- other derived table in this schema, this ledger is NOT re-derivable by
-- re-running an ingest. Every other one has the git mirror as its source
-- of truth; this one records that a path was rejected WHILE THE INGESTED
-- REF ADVANCED PAST IT, and the only way to rediscover that is to re-chunk
-- and re-embed the file -- which is precisely what the row exists to make
-- happen. So dropping these rows is genuinely lossy: the affected paths
-- fall back out of every future incremental plan, because they are not in
-- `git diff ingested_ref..tip` (they did not change), which is the defect
-- loam-qj21 exists to fix.
--
-- THE REMEDY, for an operator who rolls back and later rolls forward
-- again: force a FULL rebuild of every enrolled repo afterwards. A
-- KindFull ingest re-reads and re-chunks every file in the tree, so it
-- reconstructs the ledger from scratch, and it is the only operation that
-- can. A grammar or pipeline version bump does this to every repo at once
-- (internal/ingest/orchestrator's GrammarVersion / PipelineVersion); a
-- manual reindex does it one repo at a time. Doing nothing is also
-- survivable -- the index is merely incomplete for those paths, exactly as
-- it was before this bead -- but nothing will report it.
DROP TABLE IF EXISTS chunk_rejections;
