// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package ingest

import (
	"context"
	"github.com/google/uuid"
	"sync"
)

// Ensure, that EnqueuerMock does implement Enqueuer.
// If this is not the case, regenerate this file with moq.
var _ Enqueuer = &EnqueuerMock{}

// EnqueuerMock is a mock implementation of Enqueuer.
//
//	func TestSomethingThatUsesEnqueuer(t *testing.T) {
//
//		// make and configure a mocked Enqueuer
//		mockedEnqueuer := &EnqueuerMock{
//			EnqueueFunc: func(ctx context.Context, repoID uuid.UUID, targetBranch string, kind Kind) error {
//				panic("mock out the Enqueue method")
//			},
//		}
//
//		// use mockedEnqueuer in code that requires Enqueuer
//		// and then make assertions.
//
//	}
type EnqueuerMock struct {
	// EnqueueFunc mocks the Enqueue method.
	EnqueueFunc func(ctx context.Context, repoID uuid.UUID, targetBranch string, kind Kind) error

	// calls tracks calls to the methods.
	calls struct {
		// Enqueue holds details about calls to the Enqueue method.
		Enqueue []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RepoID is the repoID argument value.
			RepoID uuid.UUID
			// TargetBranch is the targetBranch argument value.
			TargetBranch string
			// Kind is the kind argument value.
			Kind Kind
		}
	}
	lockEnqueue sync.RWMutex
}

// Enqueue calls EnqueueFunc.
func (mock *EnqueuerMock) Enqueue(ctx context.Context, repoID uuid.UUID, targetBranch string, kind Kind) error {
	if mock.EnqueueFunc == nil {
		panic("EnqueuerMock.EnqueueFunc: method is nil but Enqueuer.Enqueue was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		RepoID       uuid.UUID
		TargetBranch string
		Kind         Kind
	}{
		Ctx:          ctx,
		RepoID:       repoID,
		TargetBranch: targetBranch,
		Kind:         kind,
	}
	mock.lockEnqueue.Lock()
	mock.calls.Enqueue = append(mock.calls.Enqueue, callInfo)
	mock.lockEnqueue.Unlock()
	return mock.EnqueueFunc(ctx, repoID, targetBranch, kind)
}

// EnqueueCalls gets all the calls that were made to Enqueue.
// Check the length with:
//
//	len(mockedEnqueuer.EnqueueCalls())
func (mock *EnqueuerMock) EnqueueCalls() []struct {
	Ctx          context.Context
	RepoID       uuid.UUID
	TargetBranch string
	Kind         Kind
} {
	var calls []struct {
		Ctx          context.Context
		RepoID       uuid.UUID
		TargetBranch string
		Kind         Kind
	}
	mock.lockEnqueue.RLock()
	calls = mock.calls.Enqueue
	mock.lockEnqueue.RUnlock()
	return calls
}

// Ensure, that OrchestratorMock does implement Orchestrator.
// If this is not the case, regenerate this file with moq.
var _ Orchestrator = &OrchestratorMock{}

// OrchestratorMock is a mock implementation of Orchestrator.
//
//	func TestSomethingThatUsesOrchestrator(t *testing.T) {
//
//		// make and configure a mocked Orchestrator
//		mockedOrchestrator := &OrchestratorMock{
//			RunFunc: func(ctx context.Context, job Job) (Stats, error) {
//				panic("mock out the Run method")
//			},
//		}
//
//		// use mockedOrchestrator in code that requires Orchestrator
//		// and then make assertions.
//
//	}
type OrchestratorMock struct {
	// RunFunc mocks the Run method.
	RunFunc func(ctx context.Context, job Job) (Stats, error)

	// calls tracks calls to the methods.
	calls struct {
		// Run holds details about calls to the Run method.
		Run []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Job is the job argument value.
			Job Job
		}
	}
	lockRun sync.RWMutex
}

// Run calls RunFunc.
func (mock *OrchestratorMock) Run(ctx context.Context, job Job) (Stats, error) {
	if mock.RunFunc == nil {
		panic("OrchestratorMock.RunFunc: method is nil but Orchestrator.Run was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Job Job
	}{
		Ctx: ctx,
		Job: job,
	}
	mock.lockRun.Lock()
	mock.calls.Run = append(mock.calls.Run, callInfo)
	mock.lockRun.Unlock()
	return mock.RunFunc(ctx, job)
}

// RunCalls gets all the calls that were made to Run.
// Check the length with:
//
//	len(mockedOrchestrator.RunCalls())
func (mock *OrchestratorMock) RunCalls() []struct {
	Ctx context.Context
	Job Job
} {
	var calls []struct {
		Ctx context.Context
		Job Job
	}
	mock.lockRun.RLock()
	calls = mock.calls.Run
	mock.lockRun.RUnlock()
	return calls
}
