// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package reviewpublish

import (
	"context"
	"github.com/bobcob7/loam/internal/workbranchstore"
	"sync"
)

// Ensure, that AnchorCheckerMock does implement AnchorChecker.
// If this is not the case, regenerate this file with moq.
var _ AnchorChecker = &AnchorCheckerMock{}

// AnchorCheckerMock is a mock implementation of AnchorChecker.
//
//	func TestSomethingThatUsesAnchorChecker(t *testing.T) {
//
//		// make and configure a mocked AnchorChecker
//		mockedAnchorChecker := &AnchorCheckerMock{
//			FileLineCountFunc: func(ctx context.Context, wb workbranchstore.WorkBranch, file string) (int, error) {
//				panic("mock out the FileLineCount method")
//			},
//		}
//
//		// use mockedAnchorChecker in code that requires AnchorChecker
//		// and then make assertions.
//
//	}
type AnchorCheckerMock struct {
	// FileLineCountFunc mocks the FileLineCount method.
	FileLineCountFunc func(ctx context.Context, wb workbranchstore.WorkBranch, file string) (int, error)

	// calls tracks calls to the methods.
	calls struct {
		// FileLineCount holds details about calls to the FileLineCount method.
		FileLineCount []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Wb is the wb argument value.
			Wb workbranchstore.WorkBranch
			// File is the file argument value.
			File string
		}
	}
	lockFileLineCount sync.RWMutex
}

// FileLineCount calls FileLineCountFunc.
func (mock *AnchorCheckerMock) FileLineCount(ctx context.Context, wb workbranchstore.WorkBranch, file string) (int, error) {
	if mock.FileLineCountFunc == nil {
		panic("AnchorCheckerMock.FileLineCountFunc: method is nil but AnchorChecker.FileLineCount was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Wb   workbranchstore.WorkBranch
		File string
	}{
		Ctx:  ctx,
		Wb:   wb,
		File: file,
	}
	mock.lockFileLineCount.Lock()
	mock.calls.FileLineCount = append(mock.calls.FileLineCount, callInfo)
	mock.lockFileLineCount.Unlock()
	return mock.FileLineCountFunc(ctx, wb, file)
}

// FileLineCountCalls gets all the calls that were made to FileLineCount.
// Check the length with:
//
//	len(mockedAnchorChecker.FileLineCountCalls())
func (mock *AnchorCheckerMock) FileLineCountCalls() []struct {
	Ctx  context.Context
	Wb   workbranchstore.WorkBranch
	File string
} {
	var calls []struct {
		Ctx  context.Context
		Wb   workbranchstore.WorkBranch
		File string
	}
	mock.lockFileLineCount.RLock()
	calls = mock.calls.FileLineCount
	mock.lockFileLineCount.RUnlock()
	return calls
}
