// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package workbranchstore

import (
	"context"
	"github.com/bobcob7/loam/internal/db/gen"
	"github.com/jackc/pgx/v5/pgtype"
	"sync"
)

// Ensure, that querierMock does implement querier.
// If this is not the case, regenerate this file with moq.
var _ querier = &querierMock{}

// querierMock is a mock implementation of querier.
//
//	func TestSomethingThatUsesquerier(t *testing.T) {
//
//		// make and configure a mocked querier
//		mockedquerier := &querierMock{
//			ClearWorkBranchConflictFunc: func(ctx context.Context, id pgtype.UUID) (gen.WorkBranch, error) {
//				panic("mock out the ClearWorkBranchConflict method")
//			},
//			CloseWorkBranchFunc: func(ctx context.Context, arg gen.CloseWorkBranchParams) (gen.WorkBranch, error) {
//				panic("mock out the CloseWorkBranch method")
//			},
//			CompleteWorkBranchFunc: func(ctx context.Context, id pgtype.UUID) (gen.WorkBranch, error) {
//				panic("mock out the CompleteWorkBranch method")
//			},
//			CountWorkBranchesFunc: func(ctx context.Context, arg gen.CountWorkBranchesParams) (int64, error) {
//				panic("mock out the CountWorkBranches method")
//			},
//			CreateWorkBranchFunc: func(ctx context.Context, arg gen.CreateWorkBranchParams) (gen.WorkBranch, error) {
//				panic("mock out the CreateWorkBranch method")
//			},
//			GetWorkBranchByIDFunc: func(ctx context.Context, id pgtype.UUID) (gen.WorkBranch, error) {
//				panic("mock out the GetWorkBranchByID method")
//			},
//			GetWorkBranchByNameFunc: func(ctx context.Context, arg gen.GetWorkBranchByNameParams) (gen.WorkBranch, error) {
//				panic("mock out the GetWorkBranchByName method")
//			},
//			ListWorkBranchesFunc: func(ctx context.Context, arg gen.ListWorkBranchesParams) ([]gen.WorkBranch, error) {
//				panic("mock out the ListWorkBranches method")
//			},
//			MarkWorkBranchConflictedFunc: func(ctx context.Context, id pgtype.UUID) (gen.WorkBranch, error) {
//				panic("mock out the MarkWorkBranchConflicted method")
//			},
//			RecordWorkBranchAcceptedTipFunc: func(ctx context.Context, arg gen.RecordWorkBranchAcceptedTipParams) (gen.WorkBranch, error) {
//				panic("mock out the RecordWorkBranchAcceptedTip method")
//			},
//			RecordWorkBranchUpstreamPRFunc: func(ctx context.Context, arg gen.RecordWorkBranchUpstreamPRParams) (gen.WorkBranch, error) {
//				panic("mock out the RecordWorkBranchUpstreamPR method")
//			},
//			SetWorkBranchTitleDescriptionFunc: func(ctx context.Context, arg gen.SetWorkBranchTitleDescriptionParams) (gen.WorkBranch, error) {
//				panic("mock out the SetWorkBranchTitleDescription method")
//			},
//			UpdateWorkBranchStateFunc: func(ctx context.Context, arg gen.UpdateWorkBranchStateParams) (gen.WorkBranch, error) {
//				panic("mock out the UpdateWorkBranchState method")
//			},
//		}
//
//		// use mockedquerier in code that requires querier
//		// and then make assertions.
//
//	}
type querierMock struct {
	// ClearWorkBranchConflictFunc mocks the ClearWorkBranchConflict method.
	ClearWorkBranchConflictFunc func(ctx context.Context, id pgtype.UUID) (gen.WorkBranch, error)

	// CloseWorkBranchFunc mocks the CloseWorkBranch method.
	CloseWorkBranchFunc func(ctx context.Context, arg gen.CloseWorkBranchParams) (gen.WorkBranch, error)

	// CompleteWorkBranchFunc mocks the CompleteWorkBranch method.
	CompleteWorkBranchFunc func(ctx context.Context, id pgtype.UUID) (gen.WorkBranch, error)

	// CountWorkBranchesFunc mocks the CountWorkBranches method.
	CountWorkBranchesFunc func(ctx context.Context, arg gen.CountWorkBranchesParams) (int64, error)

	// CreateWorkBranchFunc mocks the CreateWorkBranch method.
	CreateWorkBranchFunc func(ctx context.Context, arg gen.CreateWorkBranchParams) (gen.WorkBranch, error)

	// GetWorkBranchByIDFunc mocks the GetWorkBranchByID method.
	GetWorkBranchByIDFunc func(ctx context.Context, id pgtype.UUID) (gen.WorkBranch, error)

	// GetWorkBranchByNameFunc mocks the GetWorkBranchByName method.
	GetWorkBranchByNameFunc func(ctx context.Context, arg gen.GetWorkBranchByNameParams) (gen.WorkBranch, error)

	// ListWorkBranchesFunc mocks the ListWorkBranches method.
	ListWorkBranchesFunc func(ctx context.Context, arg gen.ListWorkBranchesParams) ([]gen.WorkBranch, error)

	// MarkWorkBranchConflictedFunc mocks the MarkWorkBranchConflicted method.
	MarkWorkBranchConflictedFunc func(ctx context.Context, id pgtype.UUID) (gen.WorkBranch, error)

	// RecordWorkBranchAcceptedTipFunc mocks the RecordWorkBranchAcceptedTip method.
	RecordWorkBranchAcceptedTipFunc func(ctx context.Context, arg gen.RecordWorkBranchAcceptedTipParams) (gen.WorkBranch, error)

	// RecordWorkBranchUpstreamPRFunc mocks the RecordWorkBranchUpstreamPR method.
	RecordWorkBranchUpstreamPRFunc func(ctx context.Context, arg gen.RecordWorkBranchUpstreamPRParams) (gen.WorkBranch, error)

	// SetWorkBranchTitleDescriptionFunc mocks the SetWorkBranchTitleDescription method.
	SetWorkBranchTitleDescriptionFunc func(ctx context.Context, arg gen.SetWorkBranchTitleDescriptionParams) (gen.WorkBranch, error)

	// UpdateWorkBranchStateFunc mocks the UpdateWorkBranchState method.
	UpdateWorkBranchStateFunc func(ctx context.Context, arg gen.UpdateWorkBranchStateParams) (gen.WorkBranch, error)

	// calls tracks calls to the methods.
	calls struct {
		// ClearWorkBranchConflict holds details about calls to the ClearWorkBranchConflict method.
		ClearWorkBranchConflict []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID pgtype.UUID
		}
		// CloseWorkBranch holds details about calls to the CloseWorkBranch method.
		CloseWorkBranch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg gen.CloseWorkBranchParams
		}
		// CompleteWorkBranch holds details about calls to the CompleteWorkBranch method.
		CompleteWorkBranch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID pgtype.UUID
		}
		// CountWorkBranches holds details about calls to the CountWorkBranches method.
		CountWorkBranches []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg gen.CountWorkBranchesParams
		}
		// CreateWorkBranch holds details about calls to the CreateWorkBranch method.
		CreateWorkBranch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg gen.CreateWorkBranchParams
		}
		// GetWorkBranchByID holds details about calls to the GetWorkBranchByID method.
		GetWorkBranchByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID pgtype.UUID
		}
		// GetWorkBranchByName holds details about calls to the GetWorkBranchByName method.
		GetWorkBranchByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg gen.GetWorkBranchByNameParams
		}
		// ListWorkBranches holds details about calls to the ListWorkBranches method.
		ListWorkBranches []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg gen.ListWorkBranchesParams
		}
		// MarkWorkBranchConflicted holds details about calls to the MarkWorkBranchConflicted method.
		MarkWorkBranchConflicted []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID pgtype.UUID
		}
		// RecordWorkBranchAcceptedTip holds details about calls to the RecordWorkBranchAcceptedTip method.
		RecordWorkBranchAcceptedTip []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg gen.RecordWorkBranchAcceptedTipParams
		}
		// RecordWorkBranchUpstreamPR holds details about calls to the RecordWorkBranchUpstreamPR method.
		RecordWorkBranchUpstreamPR []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg gen.RecordWorkBranchUpstreamPRParams
		}
		// SetWorkBranchTitleDescription holds details about calls to the SetWorkBranchTitleDescription method.
		SetWorkBranchTitleDescription []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg gen.SetWorkBranchTitleDescriptionParams
		}
		// UpdateWorkBranchState holds details about calls to the UpdateWorkBranchState method.
		UpdateWorkBranchState []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg gen.UpdateWorkBranchStateParams
		}
	}
	lockClearWorkBranchConflict       sync.RWMutex
	lockCloseWorkBranch               sync.RWMutex
	lockCompleteWorkBranch            sync.RWMutex
	lockCountWorkBranches             sync.RWMutex
	lockCreateWorkBranch              sync.RWMutex
	lockGetWorkBranchByID             sync.RWMutex
	lockGetWorkBranchByName           sync.RWMutex
	lockListWorkBranches              sync.RWMutex
	lockMarkWorkBranchConflicted      sync.RWMutex
	lockRecordWorkBranchAcceptedTip   sync.RWMutex
	lockRecordWorkBranchUpstreamPR    sync.RWMutex
	lockSetWorkBranchTitleDescription sync.RWMutex
	lockUpdateWorkBranchState         sync.RWMutex
}

// ClearWorkBranchConflict calls ClearWorkBranchConflictFunc.
func (mock *querierMock) ClearWorkBranchConflict(ctx context.Context, id pgtype.UUID) (gen.WorkBranch, error) {
	if mock.ClearWorkBranchConflictFunc == nil {
		panic("querierMock.ClearWorkBranchConflictFunc: method is nil but querier.ClearWorkBranchConflict was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  pgtype.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockClearWorkBranchConflict.Lock()
	mock.calls.ClearWorkBranchConflict = append(mock.calls.ClearWorkBranchConflict, callInfo)
	mock.lockClearWorkBranchConflict.Unlock()
	return mock.ClearWorkBranchConflictFunc(ctx, id)
}

// ClearWorkBranchConflictCalls gets all the calls that were made to ClearWorkBranchConflict.
// Check the length with:
//
//	len(mockedquerier.ClearWorkBranchConflictCalls())
func (mock *querierMock) ClearWorkBranchConflictCalls() []struct {
	Ctx context.Context
	ID  pgtype.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  pgtype.UUID
	}
	mock.lockClearWorkBranchConflict.RLock()
	calls = mock.calls.ClearWorkBranchConflict
	mock.lockClearWorkBranchConflict.RUnlock()
	return calls
}

// CloseWorkBranch calls CloseWorkBranchFunc.
func (mock *querierMock) CloseWorkBranch(ctx context.Context, arg gen.CloseWorkBranchParams) (gen.WorkBranch, error) {
	if mock.CloseWorkBranchFunc == nil {
		panic("querierMock.CloseWorkBranchFunc: method is nil but querier.CloseWorkBranch was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg gen.CloseWorkBranchParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockCloseWorkBranch.Lock()
	mock.calls.CloseWorkBranch = append(mock.calls.CloseWorkBranch, callInfo)
	mock.lockCloseWorkBranch.Unlock()
	return mock.CloseWorkBranchFunc(ctx, arg)
}

// CloseWorkBranchCalls gets all the calls that were made to CloseWorkBranch.
// Check the length with:
//
//	len(mockedquerier.CloseWorkBranchCalls())
func (mock *querierMock) CloseWorkBranchCalls() []struct {
	Ctx context.Context
	Arg gen.CloseWorkBranchParams
} {
	var calls []struct {
		Ctx context.Context
		Arg gen.CloseWorkBranchParams
	}
	mock.lockCloseWorkBranch.RLock()
	calls = mock.calls.CloseWorkBranch
	mock.lockCloseWorkBranch.RUnlock()
	return calls
}

// CompleteWorkBranch calls CompleteWorkBranchFunc.
func (mock *querierMock) CompleteWorkBranch(ctx context.Context, id pgtype.UUID) (gen.WorkBranch, error) {
	if mock.CompleteWorkBranchFunc == nil {
		panic("querierMock.CompleteWorkBranchFunc: method is nil but querier.CompleteWorkBranch was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  pgtype.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockCompleteWorkBranch.Lock()
	mock.calls.CompleteWorkBranch = append(mock.calls.CompleteWorkBranch, callInfo)
	mock.lockCompleteWorkBranch.Unlock()
	return mock.CompleteWorkBranchFunc(ctx, id)
}

// CompleteWorkBranchCalls gets all the calls that were made to CompleteWorkBranch.
// Check the length with:
//
//	len(mockedquerier.CompleteWorkBranchCalls())
func (mock *querierMock) CompleteWorkBranchCalls() []struct {
	Ctx context.Context
	ID  pgtype.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  pgtype.UUID
	}
	mock.lockCompleteWorkBranch.RLock()
	calls = mock.calls.CompleteWorkBranch
	mock.lockCompleteWorkBranch.RUnlock()
	return calls
}

// CountWorkBranches calls CountWorkBranchesFunc.
func (mock *querierMock) CountWorkBranches(ctx context.Context, arg gen.CountWorkBranchesParams) (int64, error) {
	if mock.CountWorkBranchesFunc == nil {
		panic("querierMock.CountWorkBranchesFunc: method is nil but querier.CountWorkBranches was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg gen.CountWorkBranchesParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockCountWorkBranches.Lock()
	mock.calls.CountWorkBranches = append(mock.calls.CountWorkBranches, callInfo)
	mock.lockCountWorkBranches.Unlock()
	return mock.CountWorkBranchesFunc(ctx, arg)
}

// CountWorkBranchesCalls gets all the calls that were made to CountWorkBranches.
// Check the length with:
//
//	len(mockedquerier.CountWorkBranchesCalls())
func (mock *querierMock) CountWorkBranchesCalls() []struct {
	Ctx context.Context
	Arg gen.CountWorkBranchesParams
} {
	var calls []struct {
		Ctx context.Context
		Arg gen.CountWorkBranchesParams
	}
	mock.lockCountWorkBranches.RLock()
	calls = mock.calls.CountWorkBranches
	mock.lockCountWorkBranches.RUnlock()
	return calls
}

// CreateWorkBranch calls CreateWorkBranchFunc.
func (mock *querierMock) CreateWorkBranch(ctx context.Context, arg gen.CreateWorkBranchParams) (gen.WorkBranch, error) {
	if mock.CreateWorkBranchFunc == nil {
		panic("querierMock.CreateWorkBranchFunc: method is nil but querier.CreateWorkBranch was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg gen.CreateWorkBranchParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockCreateWorkBranch.Lock()
	mock.calls.CreateWorkBranch = append(mock.calls.CreateWorkBranch, callInfo)
	mock.lockCreateWorkBranch.Unlock()
	return mock.CreateWorkBranchFunc(ctx, arg)
}

// CreateWorkBranchCalls gets all the calls that were made to CreateWorkBranch.
// Check the length with:
//
//	len(mockedquerier.CreateWorkBranchCalls())
func (mock *querierMock) CreateWorkBranchCalls() []struct {
	Ctx context.Context
	Arg gen.CreateWorkBranchParams
} {
	var calls []struct {
		Ctx context.Context
		Arg gen.CreateWorkBranchParams
	}
	mock.lockCreateWorkBranch.RLock()
	calls = mock.calls.CreateWorkBranch
	mock.lockCreateWorkBranch.RUnlock()
	return calls
}

// GetWorkBranchByID calls GetWorkBranchByIDFunc.
func (mock *querierMock) GetWorkBranchByID(ctx context.Context, id pgtype.UUID) (gen.WorkBranch, error) {
	if mock.GetWorkBranchByIDFunc == nil {
		panic("querierMock.GetWorkBranchByIDFunc: method is nil but querier.GetWorkBranchByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  pgtype.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetWorkBranchByID.Lock()
	mock.calls.GetWorkBranchByID = append(mock.calls.GetWorkBranchByID, callInfo)
	mock.lockGetWorkBranchByID.Unlock()
	return mock.GetWorkBranchByIDFunc(ctx, id)
}

// GetWorkBranchByIDCalls gets all the calls that were made to GetWorkBranchByID.
// Check the length with:
//
//	len(mockedquerier.GetWorkBranchByIDCalls())
func (mock *querierMock) GetWorkBranchByIDCalls() []struct {
	Ctx context.Context
	ID  pgtype.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  pgtype.UUID
	}
	mock.lockGetWorkBranchByID.RLock()
	calls = mock.calls.GetWorkBranchByID
	mock.lockGetWorkBranchByID.RUnlock()
	return calls
}

// GetWorkBranchByName calls GetWorkBranchByNameFunc.
func (mock *querierMock) GetWorkBranchByName(ctx context.Context, arg gen.GetWorkBranchByNameParams) (gen.WorkBranch, error) {
	if mock.GetWorkBranchByNameFunc == nil {
		panic("querierMock.GetWorkBranchByNameFunc: method is nil but querier.GetWorkBranchByName was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg gen.GetWorkBranchByNameParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockGetWorkBranchByName.Lock()
	mock.calls.GetWorkBranchByName = append(mock.calls.GetWorkBranchByName, callInfo)
	mock.lockGetWorkBranchByName.Unlock()
	return mock.GetWorkBranchByNameFunc(ctx, arg)
}

// GetWorkBranchByNameCalls gets all the calls that were made to GetWorkBranchByName.
// Check the length with:
//
//	len(mockedquerier.GetWorkBranchByNameCalls())
func (mock *querierMock) GetWorkBranchByNameCalls() []struct {
	Ctx context.Context
	Arg gen.GetWorkBranchByNameParams
} {
	var calls []struct {
		Ctx context.Context
		Arg gen.GetWorkBranchByNameParams
	}
	mock.lockGetWorkBranchByName.RLock()
	calls = mock.calls.GetWorkBranchByName
	mock.lockGetWorkBranchByName.RUnlock()
	return calls
}

// ListWorkBranches calls ListWorkBranchesFunc.
func (mock *querierMock) ListWorkBranches(ctx context.Context, arg gen.ListWorkBranchesParams) ([]gen.WorkBranch, error) {
	if mock.ListWorkBranchesFunc == nil {
		panic("querierMock.ListWorkBranchesFunc: method is nil but querier.ListWorkBranches was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg gen.ListWorkBranchesParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockListWorkBranches.Lock()
	mock.calls.ListWorkBranches = append(mock.calls.ListWorkBranches, callInfo)
	mock.lockListWorkBranches.Unlock()
	return mock.ListWorkBranchesFunc(ctx, arg)
}

// ListWorkBranchesCalls gets all the calls that were made to ListWorkBranches.
// Check the length with:
//
//	len(mockedquerier.ListWorkBranchesCalls())
func (mock *querierMock) ListWorkBranchesCalls() []struct {
	Ctx context.Context
	Arg gen.ListWorkBranchesParams
} {
	var calls []struct {
		Ctx context.Context
		Arg gen.ListWorkBranchesParams
	}
	mock.lockListWorkBranches.RLock()
	calls = mock.calls.ListWorkBranches
	mock.lockListWorkBranches.RUnlock()
	return calls
}

// MarkWorkBranchConflicted calls MarkWorkBranchConflictedFunc.
func (mock *querierMock) MarkWorkBranchConflicted(ctx context.Context, id pgtype.UUID) (gen.WorkBranch, error) {
	if mock.MarkWorkBranchConflictedFunc == nil {
		panic("querierMock.MarkWorkBranchConflictedFunc: method is nil but querier.MarkWorkBranchConflicted was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  pgtype.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockMarkWorkBranchConflicted.Lock()
	mock.calls.MarkWorkBranchConflicted = append(mock.calls.MarkWorkBranchConflicted, callInfo)
	mock.lockMarkWorkBranchConflicted.Unlock()
	return mock.MarkWorkBranchConflictedFunc(ctx, id)
}

// MarkWorkBranchConflictedCalls gets all the calls that were made to MarkWorkBranchConflicted.
// Check the length with:
//
//	len(mockedquerier.MarkWorkBranchConflictedCalls())
func (mock *querierMock) MarkWorkBranchConflictedCalls() []struct {
	Ctx context.Context
	ID  pgtype.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  pgtype.UUID
	}
	mock.lockMarkWorkBranchConflicted.RLock()
	calls = mock.calls.MarkWorkBranchConflicted
	mock.lockMarkWorkBranchConflicted.RUnlock()
	return calls
}

// RecordWorkBranchAcceptedTip calls RecordWorkBranchAcceptedTipFunc.
func (mock *querierMock) RecordWorkBranchAcceptedTip(ctx context.Context, arg gen.RecordWorkBranchAcceptedTipParams) (gen.WorkBranch, error) {
	if mock.RecordWorkBranchAcceptedTipFunc == nil {
		panic("querierMock.RecordWorkBranchAcceptedTipFunc: method is nil but querier.RecordWorkBranchAcceptedTip was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg gen.RecordWorkBranchAcceptedTipParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockRecordWorkBranchAcceptedTip.Lock()
	mock.calls.RecordWorkBranchAcceptedTip = append(mock.calls.RecordWorkBranchAcceptedTip, callInfo)
	mock.lockRecordWorkBranchAcceptedTip.Unlock()
	return mock.RecordWorkBranchAcceptedTipFunc(ctx, arg)
}

// RecordWorkBranchAcceptedTipCalls gets all the calls that were made to RecordWorkBranchAcceptedTip.
// Check the length with:
//
//	len(mockedquerier.RecordWorkBranchAcceptedTipCalls())
func (mock *querierMock) RecordWorkBranchAcceptedTipCalls() []struct {
	Ctx context.Context
	Arg gen.RecordWorkBranchAcceptedTipParams
} {
	var calls []struct {
		Ctx context.Context
		Arg gen.RecordWorkBranchAcceptedTipParams
	}
	mock.lockRecordWorkBranchAcceptedTip.RLock()
	calls = mock.calls.RecordWorkBranchAcceptedTip
	mock.lockRecordWorkBranchAcceptedTip.RUnlock()
	return calls
}

// RecordWorkBranchUpstreamPR calls RecordWorkBranchUpstreamPRFunc.
func (mock *querierMock) RecordWorkBranchUpstreamPR(ctx context.Context, arg gen.RecordWorkBranchUpstreamPRParams) (gen.WorkBranch, error) {
	if mock.RecordWorkBranchUpstreamPRFunc == nil {
		panic("querierMock.RecordWorkBranchUpstreamPRFunc: method is nil but querier.RecordWorkBranchUpstreamPR was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg gen.RecordWorkBranchUpstreamPRParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockRecordWorkBranchUpstreamPR.Lock()
	mock.calls.RecordWorkBranchUpstreamPR = append(mock.calls.RecordWorkBranchUpstreamPR, callInfo)
	mock.lockRecordWorkBranchUpstreamPR.Unlock()
	return mock.RecordWorkBranchUpstreamPRFunc(ctx, arg)
}

// RecordWorkBranchUpstreamPRCalls gets all the calls that were made to RecordWorkBranchUpstreamPR.
// Check the length with:
//
//	len(mockedquerier.RecordWorkBranchUpstreamPRCalls())
func (mock *querierMock) RecordWorkBranchUpstreamPRCalls() []struct {
	Ctx context.Context
	Arg gen.RecordWorkBranchUpstreamPRParams
} {
	var calls []struct {
		Ctx context.Context
		Arg gen.RecordWorkBranchUpstreamPRParams
	}
	mock.lockRecordWorkBranchUpstreamPR.RLock()
	calls = mock.calls.RecordWorkBranchUpstreamPR
	mock.lockRecordWorkBranchUpstreamPR.RUnlock()
	return calls
}

// SetWorkBranchTitleDescription calls SetWorkBranchTitleDescriptionFunc.
func (mock *querierMock) SetWorkBranchTitleDescription(ctx context.Context, arg gen.SetWorkBranchTitleDescriptionParams) (gen.WorkBranch, error) {
	if mock.SetWorkBranchTitleDescriptionFunc == nil {
		panic("querierMock.SetWorkBranchTitleDescriptionFunc: method is nil but querier.SetWorkBranchTitleDescription was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg gen.SetWorkBranchTitleDescriptionParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockSetWorkBranchTitleDescription.Lock()
	mock.calls.SetWorkBranchTitleDescription = append(mock.calls.SetWorkBranchTitleDescription, callInfo)
	mock.lockSetWorkBranchTitleDescription.Unlock()
	return mock.SetWorkBranchTitleDescriptionFunc(ctx, arg)
}

// SetWorkBranchTitleDescriptionCalls gets all the calls that were made to SetWorkBranchTitleDescription.
// Check the length with:
//
//	len(mockedquerier.SetWorkBranchTitleDescriptionCalls())
func (mock *querierMock) SetWorkBranchTitleDescriptionCalls() []struct {
	Ctx context.Context
	Arg gen.SetWorkBranchTitleDescriptionParams
} {
	var calls []struct {
		Ctx context.Context
		Arg gen.SetWorkBranchTitleDescriptionParams
	}
	mock.lockSetWorkBranchTitleDescription.RLock()
	calls = mock.calls.SetWorkBranchTitleDescription
	mock.lockSetWorkBranchTitleDescription.RUnlock()
	return calls
}

// UpdateWorkBranchState calls UpdateWorkBranchStateFunc.
func (mock *querierMock) UpdateWorkBranchState(ctx context.Context, arg gen.UpdateWorkBranchStateParams) (gen.WorkBranch, error) {
	if mock.UpdateWorkBranchStateFunc == nil {
		panic("querierMock.UpdateWorkBranchStateFunc: method is nil but querier.UpdateWorkBranchState was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg gen.UpdateWorkBranchStateParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockUpdateWorkBranchState.Lock()
	mock.calls.UpdateWorkBranchState = append(mock.calls.UpdateWorkBranchState, callInfo)
	mock.lockUpdateWorkBranchState.Unlock()
	return mock.UpdateWorkBranchStateFunc(ctx, arg)
}

// UpdateWorkBranchStateCalls gets all the calls that were made to UpdateWorkBranchState.
// Check the length with:
//
//	len(mockedquerier.UpdateWorkBranchStateCalls())
func (mock *querierMock) UpdateWorkBranchStateCalls() []struct {
	Ctx context.Context
	Arg gen.UpdateWorkBranchStateParams
} {
	var calls []struct {
		Ctx context.Context
		Arg gen.UpdateWorkBranchStateParams
	}
	mock.lockUpdateWorkBranchState.RLock()
	calls = mock.calls.UpdateWorkBranchState
	mock.lockUpdateWorkBranchState.RUnlock()
	return calls
}
