package workbranchstore

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"

	"github.com/bobcob7/loam/internal/db/gen"
)

// State is a work_branches.state value, matching the column's CHECK
// constraint (docs/persistence-spec.md "work_branches").
type State string

// The five states work_branches.state's CHECK constraint allows
// (docs/cli-spec.md "Its lifecycle"). Complete and closed are terminal:
// no method in this package transitions a branch out of either.
const (
	StateDraft      State = "draft"
	StateReviewable State = "reviewable"
	StateReviewed   State = "reviewed"
	StateComplete   State = "complete"
	StateClosed     State = "closed"
)

// Conflict is a work_branches.conflict value, matching the column's CHECK
// constraint (docs/persistence-spec.md "work_branches";
// docs/git-spec.md "Target Advances & Catch-Up").
type Conflict string

// The three conflict values work_branches.conflict's CHECK constraint
// allows.
const (
	ConflictNone    Conflict = "none"
	ConflictFlagged Conflict = "flagged"
	ConflictReset   Conflict = "reset"
)

// WorkBranch is one work_branches row. The diff itself is never here --
// it is computed from git (target...name); this struct only carries the
// pointer at the ref (docs/persistence-spec.md "work_branches").
type WorkBranch struct {
	ID               uuid.UUID
	RepoID           uuid.UUID
	Name             string
	Target           string
	Title            *string
	Description      *string
	State            State
	Author           string
	UpstreamPRURL    *string
	UpstreamPRNumber *int32
	Conflict         Conflict
	CloseReason      *string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

// ListFilter narrows List/Count: every field is optional. RepoID nil,
// and every empty string field (Target, Author, State,
// AwaitingVerdictReviewer), means "no filter on this column" -- none of
// the underlying columns is ever legitimately empty, so the empty value
// is a safe "unset" sentinel (docs/cli-spec.md "list").
type ListFilter struct {
	RepoID                  *uuid.UUID
	Target                  string
	Author                  string
	State                   State
	AwaitingVerdictReviewer string
}

// Store implements the work_branches aggregate. Construct with New over a
// querier (typically gen.New(pool) or gen.New(tx)), or NewInTx as a named
// shorthand for the latter.
type Store struct {
	q      querier
	logger *slog.Logger
}

// New builds a Store backed by q, typically a *gen.Queries constructed
// over either a *pgxpool.Pool (standalone reads/writes) or a pgx.Tx
// (atomic with other stores' writes in the same transaction) -- see
// NewInTx for the latter as a named entry point matching this codebase's
// other store packages (internal/codegraph, internal/chunkstore).
func New(q querier, logger *slog.Logger) *Store {
	return &Store{q: q, logger: logger}
}

// NewInTx builds a Store bound to tx, an already-open transaction the
// caller owns and will commit or roll back itself: it is exactly
// New(gen.New(tx), logger), given a name so callers composing several
// stores' writes into one commit -- the atomic swap loam-c94.12
// orchestrates -- have one consistent constructor to reach for across
// every store package. Store never calls tx.Begin/Commit/Rollback itself,
// so there is no nested-transaction path to guard against here.
func NewInTx(tx pgx.Tx, logger *slog.Logger) *Store {
	return New(gen.New(tx), logger)
}

// Create inserts a new work_branches row in the default draft state with
// no conflict, identified by (repoID, name) -- name is generated by the
// caller (docs/cli-spec.md "start": "The name is randomly generated"),
// never by this store.
func (s *Store) Create(ctx context.Context, repoID uuid.UUID, name, target, author string) (WorkBranch, error) {
	id, err := uuid.NewV7()
	if err != nil {
		return WorkBranch{}, fmt.Errorf("generating work branch id: %w", err)
	}
	row, err := s.q.CreateWorkBranch(ctx, gen.CreateWorkBranchParams{
		ID:     pgUUID(id),
		RepoID: pgUUID(repoID),
		Name:   name,
		Target: target,
		Author: author,
	})
	if err != nil {
		if isUniqueViolation(err, "work_branches_repo_id_name_key") {
			return WorkBranch{}, fmt.Errorf("creating work branch %s/%s: %w", repoID, name, errDuplicateName)
		}
		return WorkBranch{}, fmt.Errorf("creating work branch %s/%s: %w", repoID, name, err)
	}
	s.logger.InfoContext(ctx, "created work branch", "work_branch_id", id, "repo_id", repoID, "name", name, "target", target, "author", author)
	return fromGenWorkBranch(row), nil
}

// Get returns the work branch identified by id.
func (s *Store) Get(ctx context.Context, id uuid.UUID) (WorkBranch, error) {
	row, err := s.q.GetWorkBranchByID(ctx, pgUUID(id))
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return WorkBranch{}, fmt.Errorf("getting work branch %s: %w", id, errNotFound)
		}
		return WorkBranch{}, fmt.Errorf("getting work branch %s: %w", id, err)
	}
	return fromGenWorkBranch(row), nil
}

// GetByName resolves the (repoID, name) identity -- UNIQUE(repo_id, name)
// -- to a row.
func (s *Store) GetByName(ctx context.Context, repoID uuid.UUID, name string) (WorkBranch, error) {
	row, err := s.q.GetWorkBranchByName(ctx, gen.GetWorkBranchByNameParams{RepoID: pgUUID(repoID), Name: name})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return WorkBranch{}, fmt.Errorf("getting work branch %s/%s: %w", repoID, name, errNotFound)
		}
		return WorkBranch{}, fmt.Errorf("getting work branch %s/%s: %w", repoID, name, err)
	}
	return fromGenWorkBranch(row), nil
}

// List returns filter's matching work branches ordered newest-created
// first, with LIMIT/OFFSET pagination, plus the total count matching the
// same filter, unpaginated -- for PageInfo.total
// (docs/persistence-spec.md "Conventions"). A non-positive limit reaches
// Postgres as-is; callers are expected to supply a sane page size (see
// docs/cli-spec.md "list": "--limit <n> ... defaults to 100").
func (s *Store) List(ctx context.Context, filter ListFilter, limit, offset int32) ([]WorkBranch, int64, error) {
	repoID, target, author, state, reviewer := filterColumns(filter)
	rows, err := s.q.ListWorkBranches(ctx, gen.ListWorkBranchesParams{
		Column1: repoID,
		Column2: target,
		Column3: author,
		Column4: state,
		Column5: reviewer,
		Limit:   limit,
		Offset:  offset,
	})
	if err != nil {
		return nil, 0, fmt.Errorf("listing work branches: %w", err)
	}
	total, err := s.q.CountWorkBranches(ctx, gen.CountWorkBranchesParams{
		Column1: repoID,
		Column2: target,
		Column3: author,
		Column4: state,
		Column5: reviewer,
	})
	if err != nil {
		return nil, 0, fmt.Errorf("counting work branches: %w", err)
	}
	result := make([]WorkBranch, 0, len(rows))
	for _, row := range rows {
		result = append(result, fromGenWorkBranch(row))
	}
	return result, total, nil
}

// SetTitleDescription replaces id's title and description with the given
// values -- a full replace, not a partial patch: this package leaves
// "leave one field unchanged" (docs/cli-spec.md "set": omitting --title or
// stdin leaves that field as-is) to the caller, which can read the
// current value via Get and pass it straight through. Rejected (zero rows,
// mapped to errIllegalTransition) once the branch is complete or closed
// (docs/cli-spec.md "State gates": `set` allowed in draft/reviewable/
// reviewed only).
func (s *Store) SetTitleDescription(ctx context.Context, id uuid.UUID, title, description string) (WorkBranch, error) {
	row, err := s.q.SetWorkBranchTitleDescription(ctx, gen.SetWorkBranchTitleDescriptionParams{
		ID:          pgUUID(id),
		Title:       pgText(title),
		Description: pgText(description),
	})
	if err != nil {
		return WorkBranch{}, s.transitionErr(ctx, id, err, "setting title/description on")
	}
	s.logger.InfoContext(ctx, "set work branch title/description", "work_branch_id", id)
	return fromGenWorkBranch(row), nil
}

// UpdateState performs one of the ordinary, agent-facing lifecycle
// transitions (docs/cli-spec.md "Its lifecycle"): draft -> reviewable
// (request-review), reviewable -> reviewed (first verdict), reviewed ->
// reviewable (re-review). Both transitions into reviewable also require a
// title and description to already be set (docs/cli-spec.md
// "request-review"). Any other (from, to) pair -- including
// reviewable/reviewed -> draft, -> complete, or -> closed -- is rejected
// (errIllegalTransition): those are reached only through
// MarkConflicted, Complete, and Close respectively, each of which
// carries bookkeeping (conflict, or close_reason) this generic method
// does not.
func (s *Store) UpdateState(ctx context.Context, id uuid.UUID, to State) (WorkBranch, error) {
	row, err := s.q.UpdateWorkBranchState(ctx, gen.UpdateWorkBranchStateParams{ID: pgUUID(id), State: string(to)})
	if err != nil {
		return WorkBranch{}, s.transitionErr(ctx, id, err, fmt.Sprintf("transitioning to %s", to))
	}
	s.logger.InfoContext(ctx, "updated work branch state", "work_branch_id", id, "to", to)
	return fromGenWorkBranch(row), nil
}

// Close is the admin-only terminal transition (docs/cli-spec.md: "closed
// (admin-only, or when the upstream PR is closed)"): any non-terminal
// state may close, recording reason as close_reason in the same
// statement.
func (s *Store) Close(ctx context.Context, id uuid.UUID, reason string) (WorkBranch, error) {
	row, err := s.q.CloseWorkBranch(ctx, gen.CloseWorkBranchParams{ID: pgUUID(id), CloseReason: pgText(reason)})
	if err != nil {
		return WorkBranch{}, s.transitionErr(ctx, id, err, "closing")
	}
	s.logger.InfoContext(ctx, "closed work branch", "work_branch_id", id, "reason", reason)
	return fromGenWorkBranch(row), nil
}

// Complete is the server-only terminal transition set when the upstream
// PR merges (docs/cli-spec.md: "There is no agent complete command");
// only a reviewable/reviewed branch (an accepted proposal) can complete.
func (s *Store) Complete(ctx context.Context, id uuid.UUID) (WorkBranch, error) {
	row, err := s.q.CompleteWorkBranch(ctx, pgUUID(id))
	if err != nil {
		return WorkBranch{}, s.transitionErr(ctx, id, err, "completing")
	}
	s.logger.InfoContext(ctx, "completed work branch", "work_branch_id", id)
	return fromGenWorkBranch(row), nil
}

// MarkConflicted records that a target-branch advance no longer merges
// cleanly into id (docs/git-spec.md "Target Advances & Catch-Up"): a
// draft branch just gains the flag (conflict -> flagged, state
// untouched); a reviewable or reviewed branch is reset to draft AND
// flagged in the same statement (conflict -> reset, state -> draft).
//
// This method is IDEMPOTENT and level-triggered, matching how the
// mergeability checker actually calls it: it re-evaluates every open
// (non-terminal) work branch on every target-branch advance, so the same
// branch can be found still-conflicting on several advances in a row
// before anyone catches it up. Calling MarkConflicted again on an
// already-conflicted branch is a benign no-op (it never returns
// errIllegalTransition for that reason alone), and it never downgrades an
// existing 'reset' back to 'flagged' -- doing so would silently strand a
// demoted branch merely-flagged, with no restore-to-reviewable path left
// for ClearConflict. Only legal from a non-terminal state (draft,
// reviewable, or reviewed); complete/closed reject.
func (s *Store) MarkConflicted(ctx context.Context, id uuid.UUID) (WorkBranch, error) {
	row, err := s.q.MarkWorkBranchConflicted(ctx, pgUUID(id))
	if err != nil {
		return WorkBranch{}, s.transitionErr(ctx, id, err, "marking conflicted")
	}
	s.logger.InfoContext(ctx, "marked work branch conflicted", "work_branch_id", id, "state", row.State, "conflict", row.Conflict)
	return fromGenWorkBranch(row), nil
}

// ClearConflict records a catch-up push that brings the branch up to date
// (docs/git-spec.md "Target Advances & Catch-Up"): conflict always
// returns to none; state only moves if the branch had been demoted
// (conflict was reset) -- it "flips directly back to reviewable", no
// request-review needed. A merely flagged branch (never demoted, stayed
// draft throughout) just loses the flag; its state is untouched. Only
// legal from (conflict IN (flagged, reset)) -- clearing an already-none
// conflict is rejected rather than silently succeeding.
func (s *Store) ClearConflict(ctx context.Context, id uuid.UUID) (WorkBranch, error) {
	row, err := s.q.ClearWorkBranchConflict(ctx, pgUUID(id))
	if err != nil {
		return WorkBranch{}, s.transitionErr(ctx, id, err, "clearing conflict on")
	}
	s.logger.InfoContext(ctx, "cleared work branch conflict", "work_branch_id", id)
	return fromGenWorkBranch(row), nil
}

// transitionErr maps a transition query's error to a distinguishable
// sentinel: errNotFound if id names no row at all, errIllegalTransition if
// the row exists but its current state/conflict disqualified the guarded
// UPDATE (zero rows matched, not a transport failure), or the raw error
// wrapped with context for anything else. verb names the attempted action
// for the error message.
//
// The classification Get below can itself fail for a reason that is
// neither "found" nor "not found" -- a dropped connection, a cancelled
// context -- and errors.Is(getErr, pgx.ErrNoRows) is false in that case
// too, same as it would be for a genuine row. That failure must NOT fall
// through to errIllegalTransition (which would misreport a transport
// problem as a precondition failure a caller could just accept and move
// on from); it is reported as its own wrapped error instead.
func (s *Store) transitionErr(ctx context.Context, id uuid.UUID, err error, verb string) error {
	if !errors.Is(err, pgx.ErrNoRows) {
		return fmt.Errorf("%s work branch %s: %w", verb, id, err)
	}
	_, getErr := s.q.GetWorkBranchByID(ctx, pgUUID(id))
	if getErr == nil {
		return fmt.Errorf("%s work branch %s: %w", verb, id, errIllegalTransition)
	}
	if errors.Is(getErr, pgx.ErrNoRows) {
		return fmt.Errorf("%s work branch %s: %w", verb, id, errNotFound)
	}
	return fmt.Errorf("%s work branch %s: classifying failed transition: %w", verb, id, getErr)
}

// filterColumns converts a ListFilter to the five positional filter
// columns ListWorkBranches/CountWorkBranches share: repoID is left
// Valid: false (SQL NULL, "no filter") when filter.RepoID is nil, and
// every string column is passed through as-is (empty means "no filter" at
// the SQL layer -- internal/db/queries/work_branches.sql).
func filterColumns(filter ListFilter) (repoID pgtype.UUID, target, author, state, reviewer string) {
	if filter.RepoID != nil {
		repoID = pgUUID(*filter.RepoID)
	}
	return repoID, filter.Target, filter.Author, string(filter.State), filter.AwaitingVerdictReviewer
}

// fromGenWorkBranch converts a sqlc-generated row into the store's own
// WorkBranch type, keeping pgtype/gen details out of this package's public
// surface.
func fromGenWorkBranch(row gen.WorkBranch) WorkBranch {
	return WorkBranch{
		ID:               uuidFromPg(row.ID),
		RepoID:           uuidFromPg(row.RepoID),
		Name:             row.Name,
		Target:           row.Target,
		Title:            textFromPg(row.Title),
		Description:      textFromPg(row.Description),
		State:            State(row.State),
		Author:           row.Author,
		UpstreamPRURL:    textFromPg(row.UpstreamPrUrl),
		UpstreamPRNumber: int4FromPg(row.UpstreamPrNumber),
		Conflict:         Conflict(row.Conflict),
		CloseReason:      textFromPg(row.CloseReason),
		CreatedAt:        row.CreatedAt.Time,
		UpdatedAt:        row.UpdatedAt.Time,
	}
}
