// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package state

import (
	"context"
	"github.com/jackc/pgx/v5/pgconn"
	"sync"
)

// Ensure, that execerMock does implement execer.
// If this is not the case, regenerate this file with moq.
var _ execer = &execerMock{}

// execerMock is a mock implementation of execer.
//
//	func TestSomethingThatUsesexecer(t *testing.T) {
//
//		// make and configure a mocked execer
//		mockedexecer := &execerMock{
//			ExecFunc: func(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error) {
//				panic("mock out the Exec method")
//			},
//		}
//
//		// use mockedexecer in code that requires execer
//		// and then make assertions.
//
//	}
type execerMock struct {
	// ExecFunc mocks the Exec method.
	ExecFunc func(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error)

	// calls tracks calls to the methods.
	calls struct {
		// Exec holds details about calls to the Exec method.
		Exec []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SQL is the sql argument value.
			SQL string
			// Args is the args argument value.
			Args []any
		}
	}
	lockExec sync.RWMutex
}

// Exec calls ExecFunc.
func (mock *execerMock) Exec(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error) {
	if mock.ExecFunc == nil {
		panic("execerMock.ExecFunc: method is nil but execer.Exec was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		SQL  string
		Args []any
	}{
		Ctx:  ctx,
		SQL:  sql,
		Args: args,
	}
	mock.lockExec.Lock()
	mock.calls.Exec = append(mock.calls.Exec, callInfo)
	mock.lockExec.Unlock()
	return mock.ExecFunc(ctx, sql, args...)
}

// ExecCalls gets all the calls that were made to Exec.
// Check the length with:
//
//	len(mockedexecer.ExecCalls())
func (mock *execerMock) ExecCalls() []struct {
	Ctx  context.Context
	SQL  string
	Args []any
} {
	var calls []struct {
		Ctx  context.Context
		SQL  string
		Args []any
	}
	mock.lockExec.RLock()
	calls = mock.calls.Exec
	mock.lockExec.RUnlock()
	return calls
}
