// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package main

import (
	"context"
	"github.com/bobcob7/loam/internal/credentialstore"
	"github.com/bobcob7/loam/internal/reposstore"
	"sync"
)

// Ensure, that runnerMock does implement runner.
// If this is not the case, regenerate this file with moq.
var _ runner = &runnerMock{}

// runnerMock is a mock implementation of runner.
//
//	func TestSomethingThatUsesrunner(t *testing.T) {
//
//		// make and configure a mocked runner
//		mockedrunner := &runnerMock{
//			RunFunc: func(ctx context.Context)  {
//				panic("mock out the Run method")
//			},
//		}
//
//		// use mockedrunner in code that requires runner
//		// and then make assertions.
//
//	}
type runnerMock struct {
	// RunFunc mocks the Run method.
	RunFunc func(ctx context.Context)

	// calls tracks calls to the methods.
	calls struct {
		// Run holds details about calls to the Run method.
		Run []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockRun sync.RWMutex
}

// Run calls RunFunc.
func (mock *runnerMock) Run(ctx context.Context) {
	if mock.RunFunc == nil {
		panic("runnerMock.RunFunc: method is nil but runner.Run was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockRun.Lock()
	mock.calls.Run = append(mock.calls.Run, callInfo)
	mock.lockRun.Unlock()
	mock.RunFunc(ctx)
}

// RunCalls gets all the calls that were made to Run.
// Check the length with:
//
//	len(mockedrunner.RunCalls())
func (mock *runnerMock) RunCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockRun.RLock()
	calls = mock.calls.Run
	mock.lockRun.RUnlock()
	return calls
}

// Ensure, that closerMock does implement closer.
// If this is not the case, regenerate this file with moq.
var _ closer = &closerMock{}

// closerMock is a mock implementation of closer.
//
//	func TestSomethingThatUsescloser(t *testing.T) {
//
//		// make and configure a mocked closer
//		mockedcloser := &closerMock{
//			CloseFunc: func()  {
//				panic("mock out the Close method")
//			},
//		}
//
//		// use mockedcloser in code that requires closer
//		// and then make assertions.
//
//	}
type closerMock struct {
	// CloseFunc mocks the Close method.
	CloseFunc func()

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
	}
	lockClose sync.RWMutex
}

// Close calls CloseFunc.
func (mock *closerMock) Close() {
	if mock.CloseFunc == nil {
		panic("closerMock.CloseFunc: method is nil but closer.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedcloser.CloseCalls())
func (mock *closerMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// Ensure, that repoNameListerMock does implement repoNameLister.
// If this is not the case, regenerate this file with moq.
var _ repoNameLister = &repoNameListerMock{}

// repoNameListerMock is a mock implementation of repoNameLister.
//
//	func TestSomethingThatUsesrepoNameLister(t *testing.T) {
//
//		// make and configure a mocked repoNameLister
//		mockedrepoNameLister := &repoNameListerMock{
//			ListAllRepoNamesFunc: func(ctx context.Context) ([]string, error) {
//				panic("mock out the ListAllRepoNames method")
//			},
//		}
//
//		// use mockedrepoNameLister in code that requires repoNameLister
//		// and then make assertions.
//
//	}
type repoNameListerMock struct {
	// ListAllRepoNamesFunc mocks the ListAllRepoNames method.
	ListAllRepoNamesFunc func(ctx context.Context) ([]string, error)

	// calls tracks calls to the methods.
	calls struct {
		// ListAllRepoNames holds details about calls to the ListAllRepoNames method.
		ListAllRepoNames []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockListAllRepoNames sync.RWMutex
}

// ListAllRepoNames calls ListAllRepoNamesFunc.
func (mock *repoNameListerMock) ListAllRepoNames(ctx context.Context) ([]string, error) {
	if mock.ListAllRepoNamesFunc == nil {
		panic("repoNameListerMock.ListAllRepoNamesFunc: method is nil but repoNameLister.ListAllRepoNames was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListAllRepoNames.Lock()
	mock.calls.ListAllRepoNames = append(mock.calls.ListAllRepoNames, callInfo)
	mock.lockListAllRepoNames.Unlock()
	return mock.ListAllRepoNamesFunc(ctx)
}

// ListAllRepoNamesCalls gets all the calls that were made to ListAllRepoNames.
// Check the length with:
//
//	len(mockedrepoNameLister.ListAllRepoNamesCalls())
func (mock *repoNameListerMock) ListAllRepoNamesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListAllRepoNames.RLock()
	calls = mock.calls.ListAllRepoNames
	mock.lockListAllRepoNames.RUnlock()
	return calls
}

// Ensure, that repoForgeLookupMock does implement repoForgeLookup.
// If this is not the case, regenerate this file with moq.
var _ repoForgeLookup = &repoForgeLookupMock{}

// repoForgeLookupMock is a mock implementation of repoForgeLookup.
//
//	func TestSomethingThatUsesrepoForgeLookup(t *testing.T) {
//
//		// make and configure a mocked repoForgeLookup
//		mockedrepoForgeLookup := &repoForgeLookupMock{
//			GetRepoByNameFunc: func(ctx context.Context, name string) (reposstore.Repo, error) {
//				panic("mock out the GetRepoByName method")
//			},
//		}
//
//		// use mockedrepoForgeLookup in code that requires repoForgeLookup
//		// and then make assertions.
//
//	}
type repoForgeLookupMock struct {
	// GetRepoByNameFunc mocks the GetRepoByName method.
	GetRepoByNameFunc func(ctx context.Context, name string) (reposstore.Repo, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetRepoByName holds details about calls to the GetRepoByName method.
		GetRepoByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
	}
	lockGetRepoByName sync.RWMutex
}

// GetRepoByName calls GetRepoByNameFunc.
func (mock *repoForgeLookupMock) GetRepoByName(ctx context.Context, name string) (reposstore.Repo, error) {
	if mock.GetRepoByNameFunc == nil {
		panic("repoForgeLookupMock.GetRepoByNameFunc: method is nil but repoForgeLookup.GetRepoByName was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockGetRepoByName.Lock()
	mock.calls.GetRepoByName = append(mock.calls.GetRepoByName, callInfo)
	mock.lockGetRepoByName.Unlock()
	return mock.GetRepoByNameFunc(ctx, name)
}

// GetRepoByNameCalls gets all the calls that were made to GetRepoByName.
// Check the length with:
//
//	len(mockedrepoForgeLookup.GetRepoByNameCalls())
func (mock *repoForgeLookupMock) GetRepoByNameCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockGetRepoByName.RLock()
	calls = mock.calls.GetRepoByName
	mock.lockGetRepoByName.RUnlock()
	return calls
}

// Ensure, that forgeCredentialLookupMock does implement forgeCredentialLookup.
// If this is not the case, regenerate this file with moq.
var _ forgeCredentialLookup = &forgeCredentialLookupMock{}

// forgeCredentialLookupMock is a mock implementation of forgeCredentialLookup.
//
//	func TestSomethingThatUsesforgeCredentialLookup(t *testing.T) {
//
//		// make and configure a mocked forgeCredentialLookup
//		mockedforgeCredentialLookup := &forgeCredentialLookupMock{
//			GetByHostFunc: func(ctx context.Context, host string) (credentialstore.Credential, error) {
//				panic("mock out the GetByHost method")
//			},
//		}
//
//		// use mockedforgeCredentialLookup in code that requires forgeCredentialLookup
//		// and then make assertions.
//
//	}
type forgeCredentialLookupMock struct {
	// GetByHostFunc mocks the GetByHost method.
	GetByHostFunc func(ctx context.Context, host string) (credentialstore.Credential, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetByHost holds details about calls to the GetByHost method.
		GetByHost []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Host is the host argument value.
			Host string
		}
	}
	lockGetByHost sync.RWMutex
}

// GetByHost calls GetByHostFunc.
func (mock *forgeCredentialLookupMock) GetByHost(ctx context.Context, host string) (credentialstore.Credential, error) {
	if mock.GetByHostFunc == nil {
		panic("forgeCredentialLookupMock.GetByHostFunc: method is nil but forgeCredentialLookup.GetByHost was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Host string
	}{
		Ctx:  ctx,
		Host: host,
	}
	mock.lockGetByHost.Lock()
	mock.calls.GetByHost = append(mock.calls.GetByHost, callInfo)
	mock.lockGetByHost.Unlock()
	return mock.GetByHostFunc(ctx, host)
}

// GetByHostCalls gets all the calls that were made to GetByHost.
// Check the length with:
//
//	len(mockedforgeCredentialLookup.GetByHostCalls())
func (mock *forgeCredentialLookupMock) GetByHostCalls() []struct {
	Ctx  context.Context
	Host string
} {
	var calls []struct {
		Ctx  context.Context
		Host string
	}
	mock.lockGetByHost.RLock()
	calls = mock.calls.GetByHost
	mock.lockGetByHost.RUnlock()
	return calls
}
