// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package chunks

import (
	"context"
	"github.com/bobcob7/loam/internal/db/gen"
	"sync"
)

// Ensure, that queriesMock does implement queries.
// If this is not the case, regenerate this file with moq.
var _ queries = &queriesMock{}

// queriesMock is a mock implementation of queries.
//
//	func TestSomethingThatUsesqueries(t *testing.T) {
//
//		// make and configure a mocked queries
//		mockedqueries := &queriesMock{
//			DeleteChunksByFileFunc: func(ctx context.Context, arg gen.DeleteChunksByFileParams) error {
//				panic("mock out the DeleteChunksByFile method")
//			},
//			InsertChunkFunc: func(ctx context.Context, arg gen.InsertChunkParams) (gen.Chunk, error) {
//				panic("mock out the InsertChunk method")
//			},
//			SearchChunksByEmbeddingScopedFunc: func(ctx context.Context, arg gen.SearchChunksByEmbeddingScopedParams) ([]gen.Chunk, error) {
//				panic("mock out the SearchChunksByEmbeddingScoped method")
//			},
//		}
//
//		// use mockedqueries in code that requires queries
//		// and then make assertions.
//
//	}
type queriesMock struct {
	// DeleteChunksByFileFunc mocks the DeleteChunksByFile method.
	DeleteChunksByFileFunc func(ctx context.Context, arg gen.DeleteChunksByFileParams) error

	// InsertChunkFunc mocks the InsertChunk method.
	InsertChunkFunc func(ctx context.Context, arg gen.InsertChunkParams) (gen.Chunk, error)

	// SearchChunksByEmbeddingScopedFunc mocks the SearchChunksByEmbeddingScoped method.
	SearchChunksByEmbeddingScopedFunc func(ctx context.Context, arg gen.SearchChunksByEmbeddingScopedParams) ([]gen.Chunk, error)

	// calls tracks calls to the methods.
	calls struct {
		// DeleteChunksByFile holds details about calls to the DeleteChunksByFile method.
		DeleteChunksByFile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg gen.DeleteChunksByFileParams
		}
		// InsertChunk holds details about calls to the InsertChunk method.
		InsertChunk []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg gen.InsertChunkParams
		}
		// SearchChunksByEmbeddingScoped holds details about calls to the SearchChunksByEmbeddingScoped method.
		SearchChunksByEmbeddingScoped []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg gen.SearchChunksByEmbeddingScopedParams
		}
	}
	lockDeleteChunksByFile            sync.RWMutex
	lockInsertChunk                   sync.RWMutex
	lockSearchChunksByEmbeddingScoped sync.RWMutex
}

// DeleteChunksByFile calls DeleteChunksByFileFunc.
func (mock *queriesMock) DeleteChunksByFile(ctx context.Context, arg gen.DeleteChunksByFileParams) error {
	if mock.DeleteChunksByFileFunc == nil {
		panic("queriesMock.DeleteChunksByFileFunc: method is nil but queries.DeleteChunksByFile was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg gen.DeleteChunksByFileParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockDeleteChunksByFile.Lock()
	mock.calls.DeleteChunksByFile = append(mock.calls.DeleteChunksByFile, callInfo)
	mock.lockDeleteChunksByFile.Unlock()
	return mock.DeleteChunksByFileFunc(ctx, arg)
}

// DeleteChunksByFileCalls gets all the calls that were made to DeleteChunksByFile.
// Check the length with:
//
//	len(mockedqueries.DeleteChunksByFileCalls())
func (mock *queriesMock) DeleteChunksByFileCalls() []struct {
	Ctx context.Context
	Arg gen.DeleteChunksByFileParams
} {
	var calls []struct {
		Ctx context.Context
		Arg gen.DeleteChunksByFileParams
	}
	mock.lockDeleteChunksByFile.RLock()
	calls = mock.calls.DeleteChunksByFile
	mock.lockDeleteChunksByFile.RUnlock()
	return calls
}

// InsertChunk calls InsertChunkFunc.
func (mock *queriesMock) InsertChunk(ctx context.Context, arg gen.InsertChunkParams) (gen.Chunk, error) {
	if mock.InsertChunkFunc == nil {
		panic("queriesMock.InsertChunkFunc: method is nil but queries.InsertChunk was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg gen.InsertChunkParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockInsertChunk.Lock()
	mock.calls.InsertChunk = append(mock.calls.InsertChunk, callInfo)
	mock.lockInsertChunk.Unlock()
	return mock.InsertChunkFunc(ctx, arg)
}

// InsertChunkCalls gets all the calls that were made to InsertChunk.
// Check the length with:
//
//	len(mockedqueries.InsertChunkCalls())
func (mock *queriesMock) InsertChunkCalls() []struct {
	Ctx context.Context
	Arg gen.InsertChunkParams
} {
	var calls []struct {
		Ctx context.Context
		Arg gen.InsertChunkParams
	}
	mock.lockInsertChunk.RLock()
	calls = mock.calls.InsertChunk
	mock.lockInsertChunk.RUnlock()
	return calls
}

// SearchChunksByEmbeddingScoped calls SearchChunksByEmbeddingScopedFunc.
func (mock *queriesMock) SearchChunksByEmbeddingScoped(ctx context.Context, arg gen.SearchChunksByEmbeddingScopedParams) ([]gen.Chunk, error) {
	if mock.SearchChunksByEmbeddingScopedFunc == nil {
		panic("queriesMock.SearchChunksByEmbeddingScopedFunc: method is nil but queries.SearchChunksByEmbeddingScoped was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg gen.SearchChunksByEmbeddingScopedParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockSearchChunksByEmbeddingScoped.Lock()
	mock.calls.SearchChunksByEmbeddingScoped = append(mock.calls.SearchChunksByEmbeddingScoped, callInfo)
	mock.lockSearchChunksByEmbeddingScoped.Unlock()
	return mock.SearchChunksByEmbeddingScopedFunc(ctx, arg)
}

// SearchChunksByEmbeddingScopedCalls gets all the calls that were made to SearchChunksByEmbeddingScoped.
// Check the length with:
//
//	len(mockedqueries.SearchChunksByEmbeddingScopedCalls())
func (mock *queriesMock) SearchChunksByEmbeddingScopedCalls() []struct {
	Ctx context.Context
	Arg gen.SearchChunksByEmbeddingScopedParams
} {
	var calls []struct {
		Ctx context.Context
		Arg gen.SearchChunksByEmbeddingScopedParams
	}
	mock.lockSearchChunksByEmbeddingScoped.RLock()
	calls = mock.calls.SearchChunksByEmbeddingScoped
	mock.lockSearchChunksByEmbeddingScoped.RUnlock()
	return calls
}

// Ensure, that transactorMock does implement transactor.
// If this is not the case, regenerate this file with moq.
var _ transactor = &transactorMock{}

// transactorMock is a mock implementation of transactor.
//
//	func TestSomethingThatUsestransactor(t *testing.T) {
//
//		// make and configure a mocked transactor
//		mockedtransactor := &transactorMock{
//			withinTxFunc: func(ctx context.Context, fn func(q queries) error) error {
//				panic("mock out the withinTx method")
//			},
//		}
//
//		// use mockedtransactor in code that requires transactor
//		// and then make assertions.
//
//	}
type transactorMock struct {
	// withinTxFunc mocks the withinTx method.
	withinTxFunc func(ctx context.Context, fn func(q queries) error) error

	// calls tracks calls to the methods.
	calls struct {
		// withinTx holds details about calls to the withinTx method.
		withinTx []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Fn is the fn argument value.
			Fn func(q queries) error
		}
	}
	lockwithinTx sync.RWMutex
}

// withinTx calls withinTxFunc.
func (mock *transactorMock) withinTx(ctx context.Context, fn func(q queries) error) error {
	if mock.withinTxFunc == nil {
		panic("transactorMock.withinTxFunc: method is nil but transactor.withinTx was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Fn  func(q queries) error
	}{
		Ctx: ctx,
		Fn:  fn,
	}
	mock.lockwithinTx.Lock()
	mock.calls.withinTx = append(mock.calls.withinTx, callInfo)
	mock.lockwithinTx.Unlock()
	return mock.withinTxFunc(ctx, fn)
}

// withinTxCalls gets all the calls that were made to withinTx.
// Check the length with:
//
//	len(mockedtransactor.withinTxCalls())
func (mock *transactorMock) withinTxCalls() []struct {
	Ctx context.Context
	Fn  func(q queries) error
} {
	var calls []struct {
		Ctx context.Context
		Fn  func(q queries) error
	}
	mock.lockwithinTx.RLock()
	calls = mock.calls.withinTx
	mock.lockwithinTx.RUnlock()
	return calls
}
