// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package repoadmin

import (
	"context"
	"github.com/bobcob7/loam/internal/credentialstore"
	"github.com/bobcob7/loam/internal/ingest"
	"github.com/bobcob7/loam/internal/reposstore"
	"github.com/bobcob7/loam/internal/workbranchstore"
	"github.com/google/uuid"
	"sync"
	"time"
)

// Ensure, that repoStoreMock does implement repoStore.
// If this is not the case, regenerate this file with moq.
var _ repoStore = &repoStoreMock{}

// repoStoreMock is a mock implementation of repoStore.
//
//	func TestSomethingThatUsesrepoStore(t *testing.T) {
//
//		// make and configure a mocked repoStore
//		mockedrepoStore := &repoStoreMock{
//			AddTargetBranchFunc: func(ctx context.Context, repoID uuid.UUID, branch string) (reposstore.TargetBranch, error) {
//				panic("mock out the AddTargetBranch method")
//			},
//			CreateRepoFunc: func(ctx context.Context, params reposstore.CreateRepoParams) (reposstore.Repo, error) {
//				panic("mock out the CreateRepo method")
//			},
//			GetRepoByNameFunc: func(ctx context.Context, name string) (reposstore.Repo, error) {
//				panic("mock out the GetRepoByName method")
//			},
//			ListReposFunc: func(ctx context.Context, page reposstore.Page) (reposstore.ListReposResult, error) {
//				panic("mock out the ListRepos method")
//			},
//			ListTargetBranchesFunc: func(ctx context.Context, repoID uuid.UUID) ([]reposstore.TargetBranch, error) {
//				panic("mock out the ListTargetBranches method")
//			},
//			RemoveTargetBranchFunc: func(ctx context.Context, repoID uuid.UUID, branch string) error {
//				panic("mock out the RemoveTargetBranch method")
//			},
//			UpdateRepoFunc: func(ctx context.Context, id uuid.UUID, params reposstore.UpdateRepoParams) (reposstore.Repo, error) {
//				panic("mock out the UpdateRepo method")
//			},
//			UpdateSyncStateFunc: func(ctx context.Context, id uuid.UUID, state reposstore.SyncState, lastSyncedAt *time.Time, syncErr *string) (reposstore.Repo, error) {
//				panic("mock out the UpdateSyncState method")
//			},
//		}
//
//		// use mockedrepoStore in code that requires repoStore
//		// and then make assertions.
//
//	}
type repoStoreMock struct {
	// AddTargetBranchFunc mocks the AddTargetBranch method.
	AddTargetBranchFunc func(ctx context.Context, repoID uuid.UUID, branch string) (reposstore.TargetBranch, error)

	// CreateRepoFunc mocks the CreateRepo method.
	CreateRepoFunc func(ctx context.Context, params reposstore.CreateRepoParams) (reposstore.Repo, error)

	// GetRepoByNameFunc mocks the GetRepoByName method.
	GetRepoByNameFunc func(ctx context.Context, name string) (reposstore.Repo, error)

	// ListReposFunc mocks the ListRepos method.
	ListReposFunc func(ctx context.Context, page reposstore.Page) (reposstore.ListReposResult, error)

	// ListTargetBranchesFunc mocks the ListTargetBranches method.
	ListTargetBranchesFunc func(ctx context.Context, repoID uuid.UUID) ([]reposstore.TargetBranch, error)

	// RemoveTargetBranchFunc mocks the RemoveTargetBranch method.
	RemoveTargetBranchFunc func(ctx context.Context, repoID uuid.UUID, branch string) error

	// UpdateRepoFunc mocks the UpdateRepo method.
	UpdateRepoFunc func(ctx context.Context, id uuid.UUID, params reposstore.UpdateRepoParams) (reposstore.Repo, error)

	// UpdateSyncStateFunc mocks the UpdateSyncState method.
	UpdateSyncStateFunc func(ctx context.Context, id uuid.UUID, state reposstore.SyncState, lastSyncedAt *time.Time, syncErr *string) (reposstore.Repo, error)

	// calls tracks calls to the methods.
	calls struct {
		// AddTargetBranch holds details about calls to the AddTargetBranch method.
		AddTargetBranch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RepoID is the repoID argument value.
			RepoID uuid.UUID
			// Branch is the branch argument value.
			Branch string
		}
		// CreateRepo holds details about calls to the CreateRepo method.
		CreateRepo []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params reposstore.CreateRepoParams
		}
		// GetRepoByName holds details about calls to the GetRepoByName method.
		GetRepoByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
		// ListRepos holds details about calls to the ListRepos method.
		ListRepos []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Page is the page argument value.
			Page reposstore.Page
		}
		// ListTargetBranches holds details about calls to the ListTargetBranches method.
		ListTargetBranches []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RepoID is the repoID argument value.
			RepoID uuid.UUID
		}
		// RemoveTargetBranch holds details about calls to the RemoveTargetBranch method.
		RemoveTargetBranch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RepoID is the repoID argument value.
			RepoID uuid.UUID
			// Branch is the branch argument value.
			Branch string
		}
		// UpdateRepo holds details about calls to the UpdateRepo method.
		UpdateRepo []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
			// Params is the params argument value.
			Params reposstore.UpdateRepoParams
		}
		// UpdateSyncState holds details about calls to the UpdateSyncState method.
		UpdateSyncState []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
			// State is the state argument value.
			State reposstore.SyncState
			// LastSyncedAt is the lastSyncedAt argument value.
			LastSyncedAt *time.Time
			// SyncErr is the syncErr argument value.
			SyncErr *string
		}
	}
	lockAddTargetBranch    sync.RWMutex
	lockCreateRepo         sync.RWMutex
	lockGetRepoByName      sync.RWMutex
	lockListRepos          sync.RWMutex
	lockListTargetBranches sync.RWMutex
	lockRemoveTargetBranch sync.RWMutex
	lockUpdateRepo         sync.RWMutex
	lockUpdateSyncState    sync.RWMutex
}

// AddTargetBranch calls AddTargetBranchFunc.
func (mock *repoStoreMock) AddTargetBranch(ctx context.Context, repoID uuid.UUID, branch string) (reposstore.TargetBranch, error) {
	if mock.AddTargetBranchFunc == nil {
		panic("repoStoreMock.AddTargetBranchFunc: method is nil but repoStore.AddTargetBranch was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		RepoID uuid.UUID
		Branch string
	}{
		Ctx:    ctx,
		RepoID: repoID,
		Branch: branch,
	}
	mock.lockAddTargetBranch.Lock()
	mock.calls.AddTargetBranch = append(mock.calls.AddTargetBranch, callInfo)
	mock.lockAddTargetBranch.Unlock()
	return mock.AddTargetBranchFunc(ctx, repoID, branch)
}

// AddTargetBranchCalls gets all the calls that were made to AddTargetBranch.
// Check the length with:
//
//	len(mockedrepoStore.AddTargetBranchCalls())
func (mock *repoStoreMock) AddTargetBranchCalls() []struct {
	Ctx    context.Context
	RepoID uuid.UUID
	Branch string
} {
	var calls []struct {
		Ctx    context.Context
		RepoID uuid.UUID
		Branch string
	}
	mock.lockAddTargetBranch.RLock()
	calls = mock.calls.AddTargetBranch
	mock.lockAddTargetBranch.RUnlock()
	return calls
}

// CreateRepo calls CreateRepoFunc.
func (mock *repoStoreMock) CreateRepo(ctx context.Context, params reposstore.CreateRepoParams) (reposstore.Repo, error) {
	if mock.CreateRepoFunc == nil {
		panic("repoStoreMock.CreateRepoFunc: method is nil but repoStore.CreateRepo was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params reposstore.CreateRepoParams
	}{
		Ctx:    ctx,
		Params: params,
	}
	mock.lockCreateRepo.Lock()
	mock.calls.CreateRepo = append(mock.calls.CreateRepo, callInfo)
	mock.lockCreateRepo.Unlock()
	return mock.CreateRepoFunc(ctx, params)
}

// CreateRepoCalls gets all the calls that were made to CreateRepo.
// Check the length with:
//
//	len(mockedrepoStore.CreateRepoCalls())
func (mock *repoStoreMock) CreateRepoCalls() []struct {
	Ctx    context.Context
	Params reposstore.CreateRepoParams
} {
	var calls []struct {
		Ctx    context.Context
		Params reposstore.CreateRepoParams
	}
	mock.lockCreateRepo.RLock()
	calls = mock.calls.CreateRepo
	mock.lockCreateRepo.RUnlock()
	return calls
}

// GetRepoByName calls GetRepoByNameFunc.
func (mock *repoStoreMock) GetRepoByName(ctx context.Context, name string) (reposstore.Repo, error) {
	if mock.GetRepoByNameFunc == nil {
		panic("repoStoreMock.GetRepoByNameFunc: method is nil but repoStore.GetRepoByName was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockGetRepoByName.Lock()
	mock.calls.GetRepoByName = append(mock.calls.GetRepoByName, callInfo)
	mock.lockGetRepoByName.Unlock()
	return mock.GetRepoByNameFunc(ctx, name)
}

// GetRepoByNameCalls gets all the calls that were made to GetRepoByName.
// Check the length with:
//
//	len(mockedrepoStore.GetRepoByNameCalls())
func (mock *repoStoreMock) GetRepoByNameCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockGetRepoByName.RLock()
	calls = mock.calls.GetRepoByName
	mock.lockGetRepoByName.RUnlock()
	return calls
}

// ListRepos calls ListReposFunc.
func (mock *repoStoreMock) ListRepos(ctx context.Context, page reposstore.Page) (reposstore.ListReposResult, error) {
	if mock.ListReposFunc == nil {
		panic("repoStoreMock.ListReposFunc: method is nil but repoStore.ListRepos was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Page reposstore.Page
	}{
		Ctx:  ctx,
		Page: page,
	}
	mock.lockListRepos.Lock()
	mock.calls.ListRepos = append(mock.calls.ListRepos, callInfo)
	mock.lockListRepos.Unlock()
	return mock.ListReposFunc(ctx, page)
}

// ListReposCalls gets all the calls that were made to ListRepos.
// Check the length with:
//
//	len(mockedrepoStore.ListReposCalls())
func (mock *repoStoreMock) ListReposCalls() []struct {
	Ctx  context.Context
	Page reposstore.Page
} {
	var calls []struct {
		Ctx  context.Context
		Page reposstore.Page
	}
	mock.lockListRepos.RLock()
	calls = mock.calls.ListRepos
	mock.lockListRepos.RUnlock()
	return calls
}

// ListTargetBranches calls ListTargetBranchesFunc.
func (mock *repoStoreMock) ListTargetBranches(ctx context.Context, repoID uuid.UUID) ([]reposstore.TargetBranch, error) {
	if mock.ListTargetBranchesFunc == nil {
		panic("repoStoreMock.ListTargetBranchesFunc: method is nil but repoStore.ListTargetBranches was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		RepoID uuid.UUID
	}{
		Ctx:    ctx,
		RepoID: repoID,
	}
	mock.lockListTargetBranches.Lock()
	mock.calls.ListTargetBranches = append(mock.calls.ListTargetBranches, callInfo)
	mock.lockListTargetBranches.Unlock()
	return mock.ListTargetBranchesFunc(ctx, repoID)
}

// ListTargetBranchesCalls gets all the calls that were made to ListTargetBranches.
// Check the length with:
//
//	len(mockedrepoStore.ListTargetBranchesCalls())
func (mock *repoStoreMock) ListTargetBranchesCalls() []struct {
	Ctx    context.Context
	RepoID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		RepoID uuid.UUID
	}
	mock.lockListTargetBranches.RLock()
	calls = mock.calls.ListTargetBranches
	mock.lockListTargetBranches.RUnlock()
	return calls
}

// RemoveTargetBranch calls RemoveTargetBranchFunc.
func (mock *repoStoreMock) RemoveTargetBranch(ctx context.Context, repoID uuid.UUID, branch string) error {
	if mock.RemoveTargetBranchFunc == nil {
		panic("repoStoreMock.RemoveTargetBranchFunc: method is nil but repoStore.RemoveTargetBranch was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		RepoID uuid.UUID
		Branch string
	}{
		Ctx:    ctx,
		RepoID: repoID,
		Branch: branch,
	}
	mock.lockRemoveTargetBranch.Lock()
	mock.calls.RemoveTargetBranch = append(mock.calls.RemoveTargetBranch, callInfo)
	mock.lockRemoveTargetBranch.Unlock()
	return mock.RemoveTargetBranchFunc(ctx, repoID, branch)
}

// RemoveTargetBranchCalls gets all the calls that were made to RemoveTargetBranch.
// Check the length with:
//
//	len(mockedrepoStore.RemoveTargetBranchCalls())
func (mock *repoStoreMock) RemoveTargetBranchCalls() []struct {
	Ctx    context.Context
	RepoID uuid.UUID
	Branch string
} {
	var calls []struct {
		Ctx    context.Context
		RepoID uuid.UUID
		Branch string
	}
	mock.lockRemoveTargetBranch.RLock()
	calls = mock.calls.RemoveTargetBranch
	mock.lockRemoveTargetBranch.RUnlock()
	return calls
}

// UpdateRepo calls UpdateRepoFunc.
func (mock *repoStoreMock) UpdateRepo(ctx context.Context, id uuid.UUID, params reposstore.UpdateRepoParams) (reposstore.Repo, error) {
	if mock.UpdateRepoFunc == nil {
		panic("repoStoreMock.UpdateRepoFunc: method is nil but repoStore.UpdateRepo was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		ID     uuid.UUID
		Params reposstore.UpdateRepoParams
	}{
		Ctx:    ctx,
		ID:     id,
		Params: params,
	}
	mock.lockUpdateRepo.Lock()
	mock.calls.UpdateRepo = append(mock.calls.UpdateRepo, callInfo)
	mock.lockUpdateRepo.Unlock()
	return mock.UpdateRepoFunc(ctx, id, params)
}

// UpdateRepoCalls gets all the calls that were made to UpdateRepo.
// Check the length with:
//
//	len(mockedrepoStore.UpdateRepoCalls())
func (mock *repoStoreMock) UpdateRepoCalls() []struct {
	Ctx    context.Context
	ID     uuid.UUID
	Params reposstore.UpdateRepoParams
} {
	var calls []struct {
		Ctx    context.Context
		ID     uuid.UUID
		Params reposstore.UpdateRepoParams
	}
	mock.lockUpdateRepo.RLock()
	calls = mock.calls.UpdateRepo
	mock.lockUpdateRepo.RUnlock()
	return calls
}

// UpdateSyncState calls UpdateSyncStateFunc.
func (mock *repoStoreMock) UpdateSyncState(ctx context.Context, id uuid.UUID, state reposstore.SyncState, lastSyncedAt *time.Time, syncErr *string) (reposstore.Repo, error) {
	if mock.UpdateSyncStateFunc == nil {
		panic("repoStoreMock.UpdateSyncStateFunc: method is nil but repoStore.UpdateSyncState was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		ID           uuid.UUID
		State        reposstore.SyncState
		LastSyncedAt *time.Time
		SyncErr      *string
	}{
		Ctx:          ctx,
		ID:           id,
		State:        state,
		LastSyncedAt: lastSyncedAt,
		SyncErr:      syncErr,
	}
	mock.lockUpdateSyncState.Lock()
	mock.calls.UpdateSyncState = append(mock.calls.UpdateSyncState, callInfo)
	mock.lockUpdateSyncState.Unlock()
	return mock.UpdateSyncStateFunc(ctx, id, state, lastSyncedAt, syncErr)
}

// UpdateSyncStateCalls gets all the calls that were made to UpdateSyncState.
// Check the length with:
//
//	len(mockedrepoStore.UpdateSyncStateCalls())
func (mock *repoStoreMock) UpdateSyncStateCalls() []struct {
	Ctx          context.Context
	ID           uuid.UUID
	State        reposstore.SyncState
	LastSyncedAt *time.Time
	SyncErr      *string
} {
	var calls []struct {
		Ctx          context.Context
		ID           uuid.UUID
		State        reposstore.SyncState
		LastSyncedAt *time.Time
		SyncErr      *string
	}
	mock.lockUpdateSyncState.RLock()
	calls = mock.calls.UpdateSyncState
	mock.lockUpdateSyncState.RUnlock()
	return calls
}

// Ensure, that workBranchListerMock does implement workBranchLister.
// If this is not the case, regenerate this file with moq.
var _ workBranchLister = &workBranchListerMock{}

// workBranchListerMock is a mock implementation of workBranchLister.
//
//	func TestSomethingThatUsesworkBranchLister(t *testing.T) {
//
//		// make and configure a mocked workBranchLister
//		mockedworkBranchLister := &workBranchListerMock{
//			ListFunc: func(ctx context.Context, filter workbranchstore.ListFilter, limit int32, offset int32) ([]workbranchstore.WorkBranch, int64, error) {
//				panic("mock out the List method")
//			},
//		}
//
//		// use mockedworkBranchLister in code that requires workBranchLister
//		// and then make assertions.
//
//	}
type workBranchListerMock struct {
	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, filter workbranchstore.ListFilter, limit int32, offset int32) ([]workbranchstore.WorkBranch, int64, error)

	// calls tracks calls to the methods.
	calls struct {
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Filter is the filter argument value.
			Filter workbranchstore.ListFilter
			// Limit is the limit argument value.
			Limit int32
			// Offset is the offset argument value.
			Offset int32
		}
	}
	lockList sync.RWMutex
}

// List calls ListFunc.
func (mock *workBranchListerMock) List(ctx context.Context, filter workbranchstore.ListFilter, limit int32, offset int32) ([]workbranchstore.WorkBranch, int64, error) {
	if mock.ListFunc == nil {
		panic("workBranchListerMock.ListFunc: method is nil but workBranchLister.List was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Filter workbranchstore.ListFilter
		Limit  int32
		Offset int32
	}{
		Ctx:    ctx,
		Filter: filter,
		Limit:  limit,
		Offset: offset,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, filter, limit, offset)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedworkBranchLister.ListCalls())
func (mock *workBranchListerMock) ListCalls() []struct {
	Ctx    context.Context
	Filter workbranchstore.ListFilter
	Limit  int32
	Offset int32
} {
	var calls []struct {
		Ctx    context.Context
		Filter workbranchstore.ListFilter
		Limit  int32
		Offset int32
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Ensure, that credentialResolverMock does implement credentialResolver.
// If this is not the case, regenerate this file with moq.
var _ credentialResolver = &credentialResolverMock{}

// credentialResolverMock is a mock implementation of credentialResolver.
//
//	func TestSomethingThatUsescredentialResolver(t *testing.T) {
//
//		// make and configure a mocked credentialResolver
//		mockedcredentialResolver := &credentialResolverMock{
//			GetByHostFunc: func(ctx context.Context, host string) (credentialstore.Credential, error) {
//				panic("mock out the GetByHost method")
//			},
//		}
//
//		// use mockedcredentialResolver in code that requires credentialResolver
//		// and then make assertions.
//
//	}
type credentialResolverMock struct {
	// GetByHostFunc mocks the GetByHost method.
	GetByHostFunc func(ctx context.Context, host string) (credentialstore.Credential, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetByHost holds details about calls to the GetByHost method.
		GetByHost []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Host is the host argument value.
			Host string
		}
	}
	lockGetByHost sync.RWMutex
}

// GetByHost calls GetByHostFunc.
func (mock *credentialResolverMock) GetByHost(ctx context.Context, host string) (credentialstore.Credential, error) {
	if mock.GetByHostFunc == nil {
		panic("credentialResolverMock.GetByHostFunc: method is nil but credentialResolver.GetByHost was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Host string
	}{
		Ctx:  ctx,
		Host: host,
	}
	mock.lockGetByHost.Lock()
	mock.calls.GetByHost = append(mock.calls.GetByHost, callInfo)
	mock.lockGetByHost.Unlock()
	return mock.GetByHostFunc(ctx, host)
}

// GetByHostCalls gets all the calls that were made to GetByHost.
// Check the length with:
//
//	len(mockedcredentialResolver.GetByHostCalls())
func (mock *credentialResolverMock) GetByHostCalls() []struct {
	Ctx  context.Context
	Host string
} {
	var calls []struct {
		Ctx  context.Context
		Host string
	}
	mock.lockGetByHost.RLock()
	calls = mock.calls.GetByHost
	mock.lockGetByHost.RUnlock()
	return calls
}

// Ensure, that upstreamCheckerMock does implement upstreamChecker.
// If this is not the case, regenerate this file with moq.
var _ upstreamChecker = &upstreamCheckerMock{}

// upstreamCheckerMock is a mock implementation of upstreamChecker.
//
//	func TestSomethingThatUsesupstreamChecker(t *testing.T) {
//
//		// make and configure a mocked upstreamChecker
//		mockedupstreamChecker := &upstreamCheckerMock{
//			CheckRepoFunc: func(ctx context.Context, host string, token string, upstreamURL string) error {
//				panic("mock out the CheckRepo method")
//			},
//		}
//
//		// use mockedupstreamChecker in code that requires upstreamChecker
//		// and then make assertions.
//
//	}
type upstreamCheckerMock struct {
	// CheckRepoFunc mocks the CheckRepo method.
	CheckRepoFunc func(ctx context.Context, host string, token string, upstreamURL string) error

	// calls tracks calls to the methods.
	calls struct {
		// CheckRepo holds details about calls to the CheckRepo method.
		CheckRepo []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Host is the host argument value.
			Host string
			// Token is the token argument value.
			Token string
			// UpstreamURL is the upstreamURL argument value.
			UpstreamURL string
		}
	}
	lockCheckRepo sync.RWMutex
}

// CheckRepo calls CheckRepoFunc.
func (mock *upstreamCheckerMock) CheckRepo(ctx context.Context, host string, token string, upstreamURL string) error {
	if mock.CheckRepoFunc == nil {
		panic("upstreamCheckerMock.CheckRepoFunc: method is nil but upstreamChecker.CheckRepo was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Host        string
		Token       string
		UpstreamURL string
	}{
		Ctx:         ctx,
		Host:        host,
		Token:       token,
		UpstreamURL: upstreamURL,
	}
	mock.lockCheckRepo.Lock()
	mock.calls.CheckRepo = append(mock.calls.CheckRepo, callInfo)
	mock.lockCheckRepo.Unlock()
	return mock.CheckRepoFunc(ctx, host, token, upstreamURL)
}

// CheckRepoCalls gets all the calls that were made to CheckRepo.
// Check the length with:
//
//	len(mockedupstreamChecker.CheckRepoCalls())
func (mock *upstreamCheckerMock) CheckRepoCalls() []struct {
	Ctx         context.Context
	Host        string
	Token       string
	UpstreamURL string
} {
	var calls []struct {
		Ctx         context.Context
		Host        string
		Token       string
		UpstreamURL string
	}
	mock.lockCheckRepo.RLock()
	calls = mock.calls.CheckRepo
	mock.lockCheckRepo.RUnlock()
	return calls
}

// Ensure, that clonerMock does implement cloner.
// If this is not the case, regenerate this file with moq.
var _ cloner = &clonerMock{}

// clonerMock is a mock implementation of cloner.
//
//	func TestSomethingThatUsescloner(t *testing.T) {
//
//		// make and configure a mocked cloner
//		mockedcloner := &clonerMock{
//			CloneFunc: func(ctx context.Context, host string, mirrorDir string, upstreamURL string) ([]byte, error) {
//				panic("mock out the Clone method")
//			},
//			LsRemoteFunc: func(ctx context.Context, host string, upstreamURL string) ([]byte, error) {
//				panic("mock out the LsRemote method")
//			},
//		}
//
//		// use mockedcloner in code that requires cloner
//		// and then make assertions.
//
//	}
type clonerMock struct {
	// CloneFunc mocks the Clone method.
	CloneFunc func(ctx context.Context, host string, mirrorDir string, upstreamURL string) ([]byte, error)

	// LsRemoteFunc mocks the LsRemote method.
	LsRemoteFunc func(ctx context.Context, host string, upstreamURL string) ([]byte, error)

	// calls tracks calls to the methods.
	calls struct {
		// Clone holds details about calls to the Clone method.
		Clone []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Host is the host argument value.
			Host string
			// MirrorDir is the mirrorDir argument value.
			MirrorDir string
			// UpstreamURL is the upstreamURL argument value.
			UpstreamURL string
		}
		// LsRemote holds details about calls to the LsRemote method.
		LsRemote []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Host is the host argument value.
			Host string
			// UpstreamURL is the upstreamURL argument value.
			UpstreamURL string
		}
	}
	lockClone    sync.RWMutex
	lockLsRemote sync.RWMutex
}

// Clone calls CloneFunc.
func (mock *clonerMock) Clone(ctx context.Context, host string, mirrorDir string, upstreamURL string) ([]byte, error) {
	if mock.CloneFunc == nil {
		panic("clonerMock.CloneFunc: method is nil but cloner.Clone was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Host        string
		MirrorDir   string
		UpstreamURL string
	}{
		Ctx:         ctx,
		Host:        host,
		MirrorDir:   mirrorDir,
		UpstreamURL: upstreamURL,
	}
	mock.lockClone.Lock()
	mock.calls.Clone = append(mock.calls.Clone, callInfo)
	mock.lockClone.Unlock()
	return mock.CloneFunc(ctx, host, mirrorDir, upstreamURL)
}

// CloneCalls gets all the calls that were made to Clone.
// Check the length with:
//
//	len(mockedcloner.CloneCalls())
func (mock *clonerMock) CloneCalls() []struct {
	Ctx         context.Context
	Host        string
	MirrorDir   string
	UpstreamURL string
} {
	var calls []struct {
		Ctx         context.Context
		Host        string
		MirrorDir   string
		UpstreamURL string
	}
	mock.lockClone.RLock()
	calls = mock.calls.Clone
	mock.lockClone.RUnlock()
	return calls
}

// LsRemote calls LsRemoteFunc.
func (mock *clonerMock) LsRemote(ctx context.Context, host string, upstreamURL string) ([]byte, error) {
	if mock.LsRemoteFunc == nil {
		panic("clonerMock.LsRemoteFunc: method is nil but cloner.LsRemote was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Host        string
		UpstreamURL string
	}{
		Ctx:         ctx,
		Host:        host,
		UpstreamURL: upstreamURL,
	}
	mock.lockLsRemote.Lock()
	mock.calls.LsRemote = append(mock.calls.LsRemote, callInfo)
	mock.lockLsRemote.Unlock()
	return mock.LsRemoteFunc(ctx, host, upstreamURL)
}

// LsRemoteCalls gets all the calls that were made to LsRemote.
// Check the length with:
//
//	len(mockedcloner.LsRemoteCalls())
func (mock *clonerMock) LsRemoteCalls() []struct {
	Ctx         context.Context
	Host        string
	UpstreamURL string
} {
	var calls []struct {
		Ctx         context.Context
		Host        string
		UpstreamURL string
	}
	mock.lockLsRemote.RLock()
	calls = mock.calls.LsRemote
	mock.lockLsRemote.RUnlock()
	return calls
}

// Ensure, that ingestEnqueuerMock does implement ingestEnqueuer.
// If this is not the case, regenerate this file with moq.
var _ ingestEnqueuer = &ingestEnqueuerMock{}

// ingestEnqueuerMock is a mock implementation of ingestEnqueuer.
//
//	func TestSomethingThatUsesingestEnqueuer(t *testing.T) {
//
//		// make and configure a mocked ingestEnqueuer
//		mockedingestEnqueuer := &ingestEnqueuerMock{
//			EnqueueFunc: func(ctx context.Context, repoID uuid.UUID, targetBranch string, kind ingest.Kind) error {
//				panic("mock out the Enqueue method")
//			},
//		}
//
//		// use mockedingestEnqueuer in code that requires ingestEnqueuer
//		// and then make assertions.
//
//	}
type ingestEnqueuerMock struct {
	// EnqueueFunc mocks the Enqueue method.
	EnqueueFunc func(ctx context.Context, repoID uuid.UUID, targetBranch string, kind ingest.Kind) error

	// calls tracks calls to the methods.
	calls struct {
		// Enqueue holds details about calls to the Enqueue method.
		Enqueue []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RepoID is the repoID argument value.
			RepoID uuid.UUID
			// TargetBranch is the targetBranch argument value.
			TargetBranch string
			// Kind is the kind argument value.
			Kind ingest.Kind
		}
	}
	lockEnqueue sync.RWMutex
}

// Enqueue calls EnqueueFunc.
func (mock *ingestEnqueuerMock) Enqueue(ctx context.Context, repoID uuid.UUID, targetBranch string, kind ingest.Kind) error {
	if mock.EnqueueFunc == nil {
		panic("ingestEnqueuerMock.EnqueueFunc: method is nil but ingestEnqueuer.Enqueue was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		RepoID       uuid.UUID
		TargetBranch string
		Kind         ingest.Kind
	}{
		Ctx:          ctx,
		RepoID:       repoID,
		TargetBranch: targetBranch,
		Kind:         kind,
	}
	mock.lockEnqueue.Lock()
	mock.calls.Enqueue = append(mock.calls.Enqueue, callInfo)
	mock.lockEnqueue.Unlock()
	return mock.EnqueueFunc(ctx, repoID, targetBranch, kind)
}

// EnqueueCalls gets all the calls that were made to Enqueue.
// Check the length with:
//
//	len(mockedingestEnqueuer.EnqueueCalls())
func (mock *ingestEnqueuerMock) EnqueueCalls() []struct {
	Ctx          context.Context
	RepoID       uuid.UUID
	TargetBranch string
	Kind         ingest.Kind
} {
	var calls []struct {
		Ctx          context.Context
		RepoID       uuid.UUID
		TargetBranch string
		Kind         ingest.Kind
	}
	mock.lockEnqueue.RLock()
	calls = mock.calls.Enqueue
	mock.lockEnqueue.RUnlock()
	return calls
}

// Ensure, that jobListerMock does implement jobLister.
// If this is not the case, regenerate this file with moq.
var _ jobLister = &jobListerMock{}

// jobListerMock is a mock implementation of jobLister.
//
//	func TestSomethingThatUsesjobLister(t *testing.T) {
//
//		// make and configure a mocked jobLister
//		mockedjobLister := &jobListerMock{
//			ListJobsFunc: func(ctx context.Context, filter ingest.ListJobsFilter, limit int32, offset int32) ([]ingest.JobRecord, int64, error) {
//				panic("mock out the ListJobs method")
//			},
//		}
//
//		// use mockedjobLister in code that requires jobLister
//		// and then make assertions.
//
//	}
type jobListerMock struct {
	// ListJobsFunc mocks the ListJobs method.
	ListJobsFunc func(ctx context.Context, filter ingest.ListJobsFilter, limit int32, offset int32) ([]ingest.JobRecord, int64, error)

	// calls tracks calls to the methods.
	calls struct {
		// ListJobs holds details about calls to the ListJobs method.
		ListJobs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Filter is the filter argument value.
			Filter ingest.ListJobsFilter
			// Limit is the limit argument value.
			Limit int32
			// Offset is the offset argument value.
			Offset int32
		}
	}
	lockListJobs sync.RWMutex
}

// ListJobs calls ListJobsFunc.
func (mock *jobListerMock) ListJobs(ctx context.Context, filter ingest.ListJobsFilter, limit int32, offset int32) ([]ingest.JobRecord, int64, error) {
	if mock.ListJobsFunc == nil {
		panic("jobListerMock.ListJobsFunc: method is nil but jobLister.ListJobs was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Filter ingest.ListJobsFilter
		Limit  int32
		Offset int32
	}{
		Ctx:    ctx,
		Filter: filter,
		Limit:  limit,
		Offset: offset,
	}
	mock.lockListJobs.Lock()
	mock.calls.ListJobs = append(mock.calls.ListJobs, callInfo)
	mock.lockListJobs.Unlock()
	return mock.ListJobsFunc(ctx, filter, limit, offset)
}

// ListJobsCalls gets all the calls that were made to ListJobs.
// Check the length with:
//
//	len(mockedjobLister.ListJobsCalls())
func (mock *jobListerMock) ListJobsCalls() []struct {
	Ctx    context.Context
	Filter ingest.ListJobsFilter
	Limit  int32
	Offset int32
} {
	var calls []struct {
		Ctx    context.Context
		Filter ingest.ListJobsFilter
		Limit  int32
		Offset int32
	}
	mock.lockListJobs.RLock()
	calls = mock.calls.ListJobs
	mock.lockListJobs.RUnlock()
	return calls
}

// Ensure, that repoDeleterMock does implement repoDeleter.
// If this is not the case, regenerate this file with moq.
var _ repoDeleter = &repoDeleterMock{}

// repoDeleterMock is a mock implementation of repoDeleter.
//
//	func TestSomethingThatUsesrepoDeleter(t *testing.T) {
//
//		// make and configure a mocked repoDeleter
//		mockedrepoDeleter := &repoDeleterMock{
//			DeleteRepoFunc: func(ctx context.Context, id uuid.UUID) error {
//				panic("mock out the DeleteRepo method")
//			},
//		}
//
//		// use mockedrepoDeleter in code that requires repoDeleter
//		// and then make assertions.
//
//	}
type repoDeleterMock struct {
	// DeleteRepoFunc mocks the DeleteRepo method.
	DeleteRepoFunc func(ctx context.Context, id uuid.UUID) error

	// calls tracks calls to the methods.
	calls struct {
		// DeleteRepo holds details about calls to the DeleteRepo method.
		DeleteRepo []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
	}
	lockDeleteRepo sync.RWMutex
}

// DeleteRepo calls DeleteRepoFunc.
func (mock *repoDeleterMock) DeleteRepo(ctx context.Context, id uuid.UUID) error {
	if mock.DeleteRepoFunc == nil {
		panic("repoDeleterMock.DeleteRepoFunc: method is nil but repoDeleter.DeleteRepo was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDeleteRepo.Lock()
	mock.calls.DeleteRepo = append(mock.calls.DeleteRepo, callInfo)
	mock.lockDeleteRepo.Unlock()
	return mock.DeleteRepoFunc(ctx, id)
}

// DeleteRepoCalls gets all the calls that were made to DeleteRepo.
// Check the length with:
//
//	len(mockedrepoDeleter.DeleteRepoCalls())
func (mock *repoDeleterMock) DeleteRepoCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockDeleteRepo.RLock()
	calls = mock.calls.DeleteRepo
	mock.lockDeleteRepo.RUnlock()
	return calls
}
