// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package credential

import (
	"context"
	"github.com/bobcob7/loam/internal/credentialstore"
	"sync"
)

// Ensure, that credentialStoreMock does implement credentialStore.
// If this is not the case, regenerate this file with moq.
var _ credentialStore = &credentialStoreMock{}

// credentialStoreMock is a mock implementation of credentialStore.
//
//	func TestSomethingThatUsescredentialStore(t *testing.T) {
//
//		// make and configure a mocked credentialStore
//		mockedcredentialStore := &credentialStoreMock{
//			GetStatusFunc: func(ctx context.Context, host string) (credentialstore.CredentialStatus, error) {
//				panic("mock out the GetStatus method")
//			},
//			ListStatusesFunc: func(ctx context.Context) ([]credentialstore.CredentialStatus, error) {
//				panic("mock out the ListStatuses method")
//			},
//			SetValidatedFunc: func(ctx context.Context, host string, validated bool) (credentialstore.CredentialStatus, error) {
//				panic("mock out the SetValidated method")
//			},
//			UpsertTokenFunc: func(ctx context.Context, host string, token string) (credentialstore.CredentialStatus, error) {
//				panic("mock out the UpsertToken method")
//			},
//		}
//
//		// use mockedcredentialStore in code that requires credentialStore
//		// and then make assertions.
//
//	}
type credentialStoreMock struct {
	// GetStatusFunc mocks the GetStatus method.
	GetStatusFunc func(ctx context.Context, host string) (credentialstore.CredentialStatus, error)

	// ListStatusesFunc mocks the ListStatuses method.
	ListStatusesFunc func(ctx context.Context) ([]credentialstore.CredentialStatus, error)

	// SetValidatedFunc mocks the SetValidated method.
	SetValidatedFunc func(ctx context.Context, host string, validated bool) (credentialstore.CredentialStatus, error)

	// UpsertTokenFunc mocks the UpsertToken method.
	UpsertTokenFunc func(ctx context.Context, host string, token string) (credentialstore.CredentialStatus, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetStatus holds details about calls to the GetStatus method.
		GetStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Host is the host argument value.
			Host string
		}
		// ListStatuses holds details about calls to the ListStatuses method.
		ListStatuses []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// SetValidated holds details about calls to the SetValidated method.
		SetValidated []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Host is the host argument value.
			Host string
			// Validated is the validated argument value.
			Validated bool
		}
		// UpsertToken holds details about calls to the UpsertToken method.
		UpsertToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Host is the host argument value.
			Host string
			// Token is the token argument value.
			Token string
		}
	}
	lockGetStatus    sync.RWMutex
	lockListStatuses sync.RWMutex
	lockSetValidated sync.RWMutex
	lockUpsertToken  sync.RWMutex
}

// GetStatus calls GetStatusFunc.
func (mock *credentialStoreMock) GetStatus(ctx context.Context, host string) (credentialstore.CredentialStatus, error) {
	if mock.GetStatusFunc == nil {
		panic("credentialStoreMock.GetStatusFunc: method is nil but credentialStore.GetStatus was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Host string
	}{
		Ctx:  ctx,
		Host: host,
	}
	mock.lockGetStatus.Lock()
	mock.calls.GetStatus = append(mock.calls.GetStatus, callInfo)
	mock.lockGetStatus.Unlock()
	return mock.GetStatusFunc(ctx, host)
}

// GetStatusCalls gets all the calls that were made to GetStatus.
// Check the length with:
//
//	len(mockedcredentialStore.GetStatusCalls())
func (mock *credentialStoreMock) GetStatusCalls() []struct {
	Ctx  context.Context
	Host string
} {
	var calls []struct {
		Ctx  context.Context
		Host string
	}
	mock.lockGetStatus.RLock()
	calls = mock.calls.GetStatus
	mock.lockGetStatus.RUnlock()
	return calls
}

// ListStatuses calls ListStatusesFunc.
func (mock *credentialStoreMock) ListStatuses(ctx context.Context) ([]credentialstore.CredentialStatus, error) {
	if mock.ListStatusesFunc == nil {
		panic("credentialStoreMock.ListStatusesFunc: method is nil but credentialStore.ListStatuses was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListStatuses.Lock()
	mock.calls.ListStatuses = append(mock.calls.ListStatuses, callInfo)
	mock.lockListStatuses.Unlock()
	return mock.ListStatusesFunc(ctx)
}

// ListStatusesCalls gets all the calls that were made to ListStatuses.
// Check the length with:
//
//	len(mockedcredentialStore.ListStatusesCalls())
func (mock *credentialStoreMock) ListStatusesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListStatuses.RLock()
	calls = mock.calls.ListStatuses
	mock.lockListStatuses.RUnlock()
	return calls
}

// SetValidated calls SetValidatedFunc.
func (mock *credentialStoreMock) SetValidated(ctx context.Context, host string, validated bool) (credentialstore.CredentialStatus, error) {
	if mock.SetValidatedFunc == nil {
		panic("credentialStoreMock.SetValidatedFunc: method is nil but credentialStore.SetValidated was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Host      string
		Validated bool
	}{
		Ctx:       ctx,
		Host:      host,
		Validated: validated,
	}
	mock.lockSetValidated.Lock()
	mock.calls.SetValidated = append(mock.calls.SetValidated, callInfo)
	mock.lockSetValidated.Unlock()
	return mock.SetValidatedFunc(ctx, host, validated)
}

// SetValidatedCalls gets all the calls that were made to SetValidated.
// Check the length with:
//
//	len(mockedcredentialStore.SetValidatedCalls())
func (mock *credentialStoreMock) SetValidatedCalls() []struct {
	Ctx       context.Context
	Host      string
	Validated bool
} {
	var calls []struct {
		Ctx       context.Context
		Host      string
		Validated bool
	}
	mock.lockSetValidated.RLock()
	calls = mock.calls.SetValidated
	mock.lockSetValidated.RUnlock()
	return calls
}

// UpsertToken calls UpsertTokenFunc.
func (mock *credentialStoreMock) UpsertToken(ctx context.Context, host string, token string) (credentialstore.CredentialStatus, error) {
	if mock.UpsertTokenFunc == nil {
		panic("credentialStoreMock.UpsertTokenFunc: method is nil but credentialStore.UpsertToken was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Host  string
		Token string
	}{
		Ctx:   ctx,
		Host:  host,
		Token: token,
	}
	mock.lockUpsertToken.Lock()
	mock.calls.UpsertToken = append(mock.calls.UpsertToken, callInfo)
	mock.lockUpsertToken.Unlock()
	return mock.UpsertTokenFunc(ctx, host, token)
}

// UpsertTokenCalls gets all the calls that were made to UpsertToken.
// Check the length with:
//
//	len(mockedcredentialStore.UpsertTokenCalls())
func (mock *credentialStoreMock) UpsertTokenCalls() []struct {
	Ctx   context.Context
	Host  string
	Token string
} {
	var calls []struct {
		Ctx   context.Context
		Host  string
		Token string
	}
	mock.lockUpsertToken.RLock()
	calls = mock.calls.UpsertToken
	mock.lockUpsertToken.RUnlock()
	return calls
}

// Ensure, that tokenValidatorMock does implement tokenValidator.
// If this is not the case, regenerate this file with moq.
var _ tokenValidator = &tokenValidatorMock{}

// tokenValidatorMock is a mock implementation of tokenValidator.
//
//	func TestSomethingThatUsestokenValidator(t *testing.T) {
//
//		// make and configure a mocked tokenValidator
//		mockedtokenValidator := &tokenValidatorMock{
//			ValidateTokenFunc: func(ctx context.Context, host string, token string) error {
//				panic("mock out the ValidateToken method")
//			},
//		}
//
//		// use mockedtokenValidator in code that requires tokenValidator
//		// and then make assertions.
//
//	}
type tokenValidatorMock struct {
	// ValidateTokenFunc mocks the ValidateToken method.
	ValidateTokenFunc func(ctx context.Context, host string, token string) error

	// calls tracks calls to the methods.
	calls struct {
		// ValidateToken holds details about calls to the ValidateToken method.
		ValidateToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Host is the host argument value.
			Host string
			// Token is the token argument value.
			Token string
		}
	}
	lockValidateToken sync.RWMutex
}

// ValidateToken calls ValidateTokenFunc.
func (mock *tokenValidatorMock) ValidateToken(ctx context.Context, host string, token string) error {
	if mock.ValidateTokenFunc == nil {
		panic("tokenValidatorMock.ValidateTokenFunc: method is nil but tokenValidator.ValidateToken was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Host  string
		Token string
	}{
		Ctx:   ctx,
		Host:  host,
		Token: token,
	}
	mock.lockValidateToken.Lock()
	mock.calls.ValidateToken = append(mock.calls.ValidateToken, callInfo)
	mock.lockValidateToken.Unlock()
	return mock.ValidateTokenFunc(ctx, host, token)
}

// ValidateTokenCalls gets all the calls that were made to ValidateToken.
// Check the length with:
//
//	len(mockedtokenValidator.ValidateTokenCalls())
func (mock *tokenValidatorMock) ValidateTokenCalls() []struct {
	Ctx   context.Context
	Host  string
	Token string
} {
	var calls []struct {
		Ctx   context.Context
		Host  string
		Token string
	}
	mock.lockValidateToken.RLock()
	calls = mock.calls.ValidateToken
	mock.lockValidateToken.RUnlock()
	return calls
}
