// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package chunker

import (
	"context"
	"github.com/bobcob7/loam/internal/parser"
	"sync"
)

// Ensure, that fileParserMock does implement fileParser.
// If this is not the case, regenerate this file with moq.
var _ fileParser = &fileParserMock{}

// fileParserMock is a mock implementation of fileParser.
//
//	func TestSomethingThatUsesfileParser(t *testing.T) {
//
//		// make and configure a mocked fileParser
//		mockedfileParser := &fileParserMock{
//			ParseFunc: func(ctx context.Context, lang parser.Language, src []byte) (*parser.Tree, error) {
//				panic("mock out the Parse method")
//			},
//		}
//
//		// use mockedfileParser in code that requires fileParser
//		// and then make assertions.
//
//	}
type fileParserMock struct {
	// ParseFunc mocks the Parse method.
	ParseFunc func(ctx context.Context, lang parser.Language, src []byte) (*parser.Tree, error)

	// calls tracks calls to the methods.
	calls struct {
		// Parse holds details about calls to the Parse method.
		Parse []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Lang is the lang argument value.
			Lang parser.Language
			// Src is the src argument value.
			Src []byte
		}
	}
	lockParse sync.RWMutex
}

// Parse calls ParseFunc.
func (mock *fileParserMock) Parse(ctx context.Context, lang parser.Language, src []byte) (*parser.Tree, error) {
	if mock.ParseFunc == nil {
		panic("fileParserMock.ParseFunc: method is nil but fileParser.Parse was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Lang parser.Language
		Src  []byte
	}{
		Ctx:  ctx,
		Lang: lang,
		Src:  src,
	}
	mock.lockParse.Lock()
	mock.calls.Parse = append(mock.calls.Parse, callInfo)
	mock.lockParse.Unlock()
	return mock.ParseFunc(ctx, lang, src)
}

// ParseCalls gets all the calls that were made to Parse.
// Check the length with:
//
//	len(mockedfileParser.ParseCalls())
func (mock *fileParserMock) ParseCalls() []struct {
	Ctx  context.Context
	Lang parser.Language
	Src  []byte
} {
	var calls []struct {
		Ctx  context.Context
		Lang parser.Language
		Src  []byte
	}
	mock.lockParse.RLock()
	calls = mock.calls.Parse
	mock.lockParse.RUnlock()
	return calls
}

// Ensure, that BudgeterMock does implement Budgeter.
// If this is not the case, regenerate this file with moq.
var _ Budgeter = &BudgeterMock{}

// BudgeterMock is a mock implementation of Budgeter.
//
//	func TestSomethingThatUsesBudgeter(t *testing.T) {
//
//		// make and configure a mocked Budgeter
//		mockedBudgeter := &BudgeterMock{
//			ContextWindowFunc: func() int {
//				panic("mock out the ContextWindow method")
//			},
//		}
//
//		// use mockedBudgeter in code that requires Budgeter
//		// and then make assertions.
//
//	}
type BudgeterMock struct {
	// ContextWindowFunc mocks the ContextWindow method.
	ContextWindowFunc func() int

	// calls tracks calls to the methods.
	calls struct {
		// ContextWindow holds details about calls to the ContextWindow method.
		ContextWindow []struct {
		}
	}
	lockContextWindow sync.RWMutex
}

// ContextWindow calls ContextWindowFunc.
func (mock *BudgeterMock) ContextWindow() int {
	if mock.ContextWindowFunc == nil {
		panic("BudgeterMock.ContextWindowFunc: method is nil but Budgeter.ContextWindow was just called")
	}
	callInfo := struct {
	}{}
	mock.lockContextWindow.Lock()
	mock.calls.ContextWindow = append(mock.calls.ContextWindow, callInfo)
	mock.lockContextWindow.Unlock()
	return mock.ContextWindowFunc()
}

// ContextWindowCalls gets all the calls that were made to ContextWindow.
// Check the length with:
//
//	len(mockedBudgeter.ContextWindowCalls())
func (mock *BudgeterMock) ContextWindowCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockContextWindow.RLock()
	calls = mock.calls.ContextWindow
	mock.lockContextWindow.RUnlock()
	return calls
}
